<?php
    $this->layout('account.phtml', [
        'title' => 'Annulation de votre paiement',
        'canonical' => url_full('Payments#canceled'),
    ]);
?>

<section class="section section--text">
    <p class="paragraph--featured">
        Votre paiement a bien été annulé.
    </p>

    <p class="paragraph--center">
        <a class="call-to-action" href="<?= url('account') ?>">
            Revenir à votre compte
        </a>
    </p>
</section>
