<?php
    $this->layout('account.phtml', [
        'title' => 'Annulation de votre paiement',
        'canonical' => url_full('Payments#canceled'),
    ]);
?>

<section class="section">
    <p class="paragraph--featured paragraph--limit">
        Votre paiement a bien été annulé.
    </p>

    <form method="post" action="<?= url('account logout') ?>">
        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

        <p class="paragraph--center">
            <button class="button--primary" type="submit">
                Revenir à l’application
            </button>
        </p>
    </form>
</section>
