<?php
    $this->layout('account.phtml', [
        'title' => 'Annulation de votre paiement',
        'canonical' => url_full('Payments#canceled'),
    ]);
?>

<section class="panel">
    <div class="wrapper wrapper--small flow flow--larger">
        <div class="panel panel--primary panel--rounded flow flow--larger text--center">
            <p class="text--big text--bold">
                Votre paiement a bien été annulé.
            </p>

            <form method="post" action="<?= url('account logout') ?>">
                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

                <button class="button--primary" type="submit">
                    <?= icon('arrow-left') ?>

                    <?php if ($current_account && $current_account->preferred_service === 'freshrss'): ?>
                        Revenir à FreshRSS
                    <?php else: ?>
                        Revenir à Flus
                    <?php endif; ?>
                </button>
            </form>
        </div>
    </div>
</section>
