<?php
    $this->layout('base.phtml', [
        'title' => 'Participer à la cagnotte commune de Flus',
        'canonical' => url_full('payments#init'),
        'description' => 'Flus propose une cagnotte commune à laquelle n’importe qui peut participer pour fournir des abonnements gratuits à celles et ceux qui n’en ont pas les moyens.',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('illustrations/savings.svg'),
            'twitter_card' => 'summary_large_image',
        ],
    ]);
?>

<div class="title">
    <h1 class="title__header">
        Cagnotte commune
    </h1>
</div>

<div class="section__intro">
    <p>
        La cagnotte commune sera activée dès la sortie de la prochaine version
        de Flus. Elle sera mise à disposition de n’importe qui souhaitant
        bénéficier d’un abonnement gratuit.
    </p>

    <p>
        <strong>Vous pouvez y contribuer dès maintenant afin de soutenir mon
            travail.</strong>
    </p>
</div>

<form
     method="post"
     action="<?= url('payments#payCommonPot') ?>"
     class="form--common-pot"
 >
    <div class="form-group <?= isset($errors['amount']) ? 'form-group--invalid' : '' ?>">
        <label for="amount">
            Montant
        </label>

        <div class="form-group__stack">
            <input
                id="amount"
                name="amount"
                type="number"
                step="0.5"
                min="1"
                max="1000"
                value="<?= $amount ?>"
                required
                <?= isset($errors['amount']) ? 'autofocus' : '' ?>
            />

            <span>
                euros
            </span>
        </div>

        <?php if (isset($errors['amount'])): ?>
            <p class="form-group__error">
                <?= $errors['amount'] ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group <?= isset($errors['email']) ? 'form-group--invalid' : '' ?>">
        <label for="email">
            Adresse courriel
        </label>

        <input
            id="email"
            name="email"
            type="email"
            value="<?= $email ?>"
            required
        />

        <?php if (isset($errors['email'])): ?>
            <p class="form-group__error">
                <?= $errors['email'] ?>
            </p>
        <?php endif; ?>
    </div>

    <fieldset>
        <legend>Adresse postale</legend>

        <p class="fieldset__caption">
            Cette adresse m’est nécessaire pour pouvoir vous adresser une
            facture en bonne et due forme.
        </p>

        <div class="columns">
            <div class="columns__item">
                <div class="form-group <?= isset($errors['address_first_name']) ? 'form-group--invalid' : '' ?>">
                    <label for="first-name">
                        Prénom
                    </label>

                    <input
                        id="first-name"
                        name="address[first_name]"
                        type="text"
                        value="<?= $address['first_name'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_first_name'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_first_name'] ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>

            <div class="columns__item">
                <div class="form-group <?= isset($errors['address_last_name']) ? 'form-group--invalid' : '' ?>">
                    <label for="last-name">
                        Nom
                    </label>

                    <input
                        id="last-name"
                        name="address[last_name]"
                        type="text"
                        value="<?= $address['last_name'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_last_name'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_last_name'] ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="form-group <?= isset($errors['address_address1']) ? 'form-group--invalid' : '' ?>">
            <label for="address1">
                Adresse
            </label>

            <input
                id="address1"
                name="address[address1]"
                type="text"
                value="<?= $address['address1'] ?>"
                required
            />

            <?php if (isset($errors['address_address1'])): ?>
                <p class="form-group__error">
                    <?= $errors['address_address1'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="columns">
            <div class="columns__item columns__item--postcode">
                <div class="form-group <?= isset($errors['address_postcode']) ? 'form-group--invalid' : '' ?>">
                    <label for="postcode">
                        Code postal
                    </label>

                    <input
                        id="postcode"
                        name="address[postcode]"
                        type="text"
                        value="<?= $address['postcode'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_postcode'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_postcode'] ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>

            <div class="columns__item columns__item--city">
                <div class="form-group <?= isset($errors['address_city']) ? 'form-group--invalid' : '' ?>">
                    <label for="city">
                        Ville
                    </label>

                    <input
                        id="city"
                        name="address[city]"
                        type="text"
                        value="<?= $address['city'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_city'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_city'] ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="form-group form-group--cgv <?= isset($errors['cgv']) ? 'form-group--invalid' : '' ?>">
        <p class="form-group__caption">
            Avant d’aller plus loin, vous devriez prendre le temps de
            <a href="<?= url('home#cgv') ?>" target="_blank" rel="noopener noreferrer nofollow">
                lire les Conditions Générales de Vente (<abbr>CGV</abbr>)</a>
            pour vous assurer que celles-ci vous conviennent. Vous serez
            ensuite redirigé·e vers <a href="https://stripe.com/fr">Stripe</a>
            pour le paiement.
        </p>

        <label for="cgv">
            <input
                id="cgv"
                name="accept_cgv"
                type="checkbox"
                required
            />

            Accepter les Conditions Générales de Vente et le traitement de vos
            données par la société Stripe.
        </label>

        <?php if (isset($errors['cgv'])): ?>
            <p class="form-group__error">
                <?= $errors['cgv'] ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            Participer à la cagnotte
        </button>
    </div>
</form>
