<h1>Participer à la cagnotte commune</h1>

<form method="post" action="<?= url('payments#pay') ?>">
    <div class="form-group">
        <label for="amount">
            Montant
        </label>

        <input
            id="amount"
            name="amount"
            type="number"
            step="0.5"
            min="1"
            max="1000"
            value="<?= $amount ?>"
            required
        />

        <?php if (isset($errors['amount'])): ?>
            <p class="form-group__error">
                <?= $errors['amount'] ?>
            </p>
        <?php endif; ?>
    </div>

    <div class="form-group">
        <label for="email">
            Courriel
        </label>

        <input
            id="email"
            name="email"
            type="email"
            value="<?= $email ?>"
            required
        />

        <?php if (isset($errors['email'])): ?>
            <p class="form-group__error">
                <?= $errors['email'] ?>
            </p>
        <?php endif; ?>
    </div>

    <fieldset>
        <legend>Adresse postale</legend>

        <div class="form-group">
            <label for="first-name">
                Prénom et nom
            </label>

            <div class="columns">
                <div class="columns__item">
                    <input
                        id="first-name"
                        name="address[first_name]"
                        type="text"
                        value="<?= $address['first_name'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_first_name'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_first_name'] ?>
                        </p>
                    <?php endif; ?>
                </div>

                <div class="columns__item">
                    <input
                        id="last-name"
                        name="address[last_name]"
                        type="text"
                        value="<?= $address['last_name'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_last_name'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_last_name'] ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="address1">
                Adresse
            </label>

            <input
                id="address1"
                name="address[address1]"
                type="text"
                value="<?= $address['address1'] ?>"
                required
            />

            <?php if (isset($errors['address_address1'])): ?>
                <p class="form-group__error">
                    <?= $errors['address_address1'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form-group">
            <label for="postcode">
                Code postal et ville
            </label>

            <div class="columns">
                <div class="columns__item">
                    <input
                        id="postcode"
                        name="address[postcode]"
                        type="text"
                        value="<?= $address['postcode'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_postcode'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_postcode'] ?>
                        </p>
                    <?php endif; ?>
                </div>

                <div class="columns__item">
                    <input
                        id="city"
                        name="address[city]"
                        type="text"
                        value="<?= $address['city'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_city'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_city'] ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </fieldset>

    <div class="form__group">
        <button type="submit">
            Participer
        </button>
    </div>
</form>
