<?php
    $this->layout('account.phtml', [
        'title' => 'Merci pour votre soutien !',
        'canonical' => url_full('Payments#succeeded'),
    ]);
?>

<section class="section">
    <p class="paragraph--featured paragraph--limit">
        Votre paiement a bien été pris en compte, merci pour votre soutien&nbsp;!
    </p>

    <form method="post" action="<?= url('account logout') ?>">
        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

        <p class="paragraph--center">
            <button class="button--primary" type="submit">
                Revenir à l’application
            </button>
        </p>
    </form>

    <img
        class="illustration illustration--centered"
        alt=""
        src="<?= url_static('illustrations/super_thank_you.svg') ?>"
        height="300"
    />
</section>
