#!/bin/env php
<?php

if (php_sapi_name() !== 'cli') {
    die('This script must be called from command line.');
}

$app_path = __DIR__;

include $app_path . '/vendor/autoload.php';

\Minz\Configuration::load('dotenv', $app_path);

$request = \Minz\Request::initFromCli($argv);

$application = new \Website\Application();
$response = $application->run($request);

\Minz\Response::sendToCli($response);
