<?php
    $this->layout('admin.phtml', [
        'title' => 'Paiements en ' . $year,
    ]);
?>

<div class="header">
    <h1 class="header__title">Paiements en <?= $year ?></h1>
</div>

<p class="paragraph--center">
    <a href="<?= url('admin accounts') ?>">
        Voir les comptes
    </a>
</p>

<a href="<?= url('new admin payment') ?>">
    Créer un paiement
</a>

<?php foreach ($payments_by_months as $month => $payments): ?>
    <h2><?= format_month($month, '%B') ?></h2>

    <table>
        <tbody>
            <?php foreach ($payments as $payment): ?>
                <tr <?= !$payment->completed_at ? 'class="row--ghost"' : ''?> >
                    <td class="cell--right">
                        <?= format_amount($payment->amount) ?>
                    </td>

                    <td>
                        <?php if ($payment->type === 'subscription' && $payment->frequency === 'month'): ?>
                            Abonnement mois
                        <?php elseif ($payment->type === 'subscription' && $payment->frequency === 'year'): ?>
                            Abonnement année
                        <?php elseif ($payment->type === 'common_pot'): ?>
                            Cagnotte
                        <?php elseif ($payment->type === 'credit'): ?>
                            Crédit
                        <?php else: ?>
                            Heu… non
                        <?php endif; ?>
                    </td>

                    <td>
                        <?= $payment->email ?>
                    </td>

                    <td>
                        <?php if ($payment->completed_at): ?>
                            <?= format_date($payment->completed_at, '%d %b') ?>
                        <?php else: ?>
                            <a href="<?= url('admin payment', ['id' => $payment->id]) ?>">
                                non payé
                            </a>
                        <?php endif; ?>
                    </td>

                    <td>
                        <?php if ($payment->invoice_number): ?>
                            <a href="<?= url('invoice download pdf', ['id' => $payment->id]) ?>">
                                <?= $payment->invoice_number ?>
                            </a>
                        <?php endif; ?>
                    </td>

                    <?php if ($payment->payment_intent_id): ?>
                        <td>
                            <a href="https://dashboard.stripe.com/payments/<?= $payment->payment_intent_id ?>">
                                💰&nbsp;Stripe
                            </a>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endforeach; ?>
