<?php
    $this->layout('admin.phtml', [
        'title' => 'Paiements en ' . $year,
    ]);
?>

<div class="header">
    <h1 class="header__title">Paiements en <?= $year ?></h1>
</div>

<p class="paragraph--center">
    <a href="<?= url('admin accounts') ?>">
        Comptes
    </a>
    ⋅
    <a target="_blank" href="<?= url('admin', ['format' => 'csv']) ?>">
        CSV
    </a>
    ⋅
    <a target="_blank" href="<?= url('admin', ['format' => 'recettes']) ?>">
        Livre des recettes
    </a>
</p>

<a href="<?= url('new admin payment') ?>">
    Créer un paiement
</a>

<?php foreach (['12', '11', '10', '09', '08', '07', '06', '05', '04', '03', '02', '01'] as $month): ?>
    <?php
        $payments = $payments_by_months[$month] ?? [];
        $count_free_renewals = $count_free_renewals_per_month[$month] ?? 0;

        if (empty($payments) && $count_free_renewals === 0) {
            continue;
        }

        $month_total_amount = 0;
        foreach ($payments as $payment) {
            if (!$payment->is_paid) {
                continue;
            }

            if ($payment->type === 'credit') {
                $month_total_amount -= $payment->totalAmount();
            } else {
                $month_total_amount += $payment->totalAmount();
            }
        }
    ?>

    <h2><?= format_month(intval($month), 'MMMM') ?>&nbsp;—&nbsp;<?= format_amount($month_total_amount) ?></h2>

    <?php if ($count_free_renewals > 0): ?>
        <p>
            <?= $count_free_renewals ?> renouvellement(s) gratuit(s)
        </p>
    <?php endif; ?>

    <table>
        <tbody>
            <?php foreach ($payments as $payment): ?>
                <tr <?= !$payment->completed_at ? 'class="row--ghost"' : ''?> >
                    <td class="cell--right">
                        <?= format_amount($payment->totalAmount()) ?>
                    </td>

                    <td>
                        <?php if ($payment->type === 'subscription' && $payment->frequency === 'month'): ?>
                            Abonnement mois
                        <?php elseif ($payment->type === 'subscription' && $payment->frequency === 'year'): ?>
                            Abonnement année
                        <?php elseif ($payment->type === 'common_pot'): ?>
                            Cagnotte
                        <?php elseif ($payment->type === 'credit'): ?>
                            Crédit
                        <?php else: ?>
                            Heu… non
                        <?php endif; ?>
                    </td>

                    <td>
                        <?php $account = $payment->account(); ?>
                        <a href="<?= url('admin account', ['id' => $account->id]) ?>">
                            <?= $account->email ?>
                        </a>
                    </td>

                    <td>
                        <?php if ($payment->completed_at): ?>
                            <?= _d($payment->completed_at, 'dd MMM') ?>
                            <?php if ($payment->type !== 'credit'): ?>
                                <a href="<?= url('new admin credit', ['credited_payment_id' => $payment->id]) ?>">
                                    💸
                                </a>
                            <?php endif; ?>
                        <?php elseif ($payment->is_paid): ?>
                            traitement en cours
                        <?php else: ?>
                            <a href="<?= url('admin payment', ['id' => $payment->id]) ?>">
                                non payé
                            </a>
                        <?php endif; ?>
                    </td>

                    <td>
                        <?php if ($payment->invoice_number): ?>
                            <a href="<?= url('invoice download pdf', ['id' => $payment->id]) ?>">
                                <?= $payment->invoice_number ?>
                            </a>
                        <?php endif; ?>
                    </td>

                    <?php if ($payment->payment_intent_id): ?>
                        <td>
                            <a href="https://dashboard.stripe.com/payments/<?= $payment->payment_intent_id ?>">
                                💰&nbsp;Stripe
                            </a>
                        </td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endforeach; ?>
