<?php
    $this->layout('admin.phtml', [
        'title' => 'Créer un nouveau paiement',
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">
            Nouveau paiement
        </h1>
    </div>

    <form
        method="post"
        action="<?= url('create admin payment') ?>"
        class="form--common-pot"
    >
        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

        <div class="form-group <?= isset($errors['email']) ? 'form-group--invalid' : '' ?>">
            <label for="email">
                Adresse courriel
            </label>

            <input
                id="email"
                name="email"
                type="email"
                value="<?= $email ?>"
                required
            />

            <?php if (isset($errors['email'])): ?>
                <p class="form-group__error">
                    <?= $errors['email'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div
            id="form-group-amount"
            class="form-group <?= isset($errors['amount']) ? 'form-group--invalid' : '' ?>"
        >
            <label for="amount">
                Sélectionner un montant
            </label>

            <input
                id="amount"
                class="amount-selector__input"
                name="amount"
                type="number"
                step="1"
                min="1"
                max="120"
                value="<?= $amount ?>"
            />

            <?php if (isset($errors['amount'])): ?>
                <p class="form-group__error">
                    <?= $errors['amount'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                Créer le paiement
            </button>
        </div>
    </form>

    <p class="paragraph--center">
        <a href="<?= url('admin') ?>">
            Revenir à l’administration
        </a>
    </p>
</section>
