<?php
    $this->layout('admin.phtml', [
        'title' => 'Affichage d’un paiement',
        'current_page' => 'admin payments',
    ]);
?>

<section class="panel">
    <div class="wrapper wrapper--small flow flow--larger">
        <h1>
            Paiement du <?= _d($payment->created_at, 'dd MMMM') ?><br />
            <?= $payment->account()->email ?>
        </h1>

        <?php if ($error): ?>
            <p class="form__error">
                Erreur&nbsp;:
                <?= $error ?>
            </p>
        <?php endif; ?>

        <?php if ($payment->is_paid): ?>
            <p class="panel panel--grey panel--rounded text--bold">
                Ce paiement a été payé.
            </p>
        <?php else: ?>
            <p class="panel panel--grey panel--rounded text--bold">
                Ce paiement n’a pas été encore été payé.
            </p>

            <div class="cols cols--center cols--gap">
                <form method="post" action="<?= url('confirm admin payment', ['id' => $payment->id]) ?>" >
                    <button type="submit" class="button--primary">
                        Confirmer le paiement
                    </button>

                    <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                </form>

                <?php if (!$payment->invoice_number): ?>
                    <p>
                        ou
                    </p>

                    <form method="post" action="<?= url('destroy admin payment', ['id' => $payment->id]) ?>">
                        <button type="submit">
                            Supprimer le paiement
                        </button>

                        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                    </form>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</section>
