<?php
    $this->layout('admin.phtml', [
        'title' => 'Affichage d’un paiement',
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">
            Paiement du <?= format_date($payment->created_at, '%d %B') ?><br />
            <?= $payment->email ?>
        </h1>
    </div>

    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <?php if ($payment->completed_at): ?>
        <p class="paragraph--featured">
            Ce paiement a été confirmé.
        </p>
    <?php else: ?>
        <p class="paragraph--featured">
            Ce paiement n’a pas été encore été confirmé.
        </p>

        <div class="columns columns--center">
            <div class="columns__item">
                <form method="post" action="<?= url('complete admin payment', ['id' => $payment->id]) ?>" >
                    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                    <div class="form-group">
                        <label for="completed-at">
                            Payé le
                        </label>

                        <input
                            id="completed-at"
                            name="completed_at"
                            type="date"
                            value="<?= format_date($completed_at, '%Y-%m-%d') ?>"
                        />
                    </div>

                    <div class="form__actions">
                        <button type="submit" class="button--primary">
                            Confirmer le paiement
                        </button>
                    </div>
                </form>
            </div>

            <div class="columns__item">
            </div>
        </div>
    <?php endif; ?>

    <p class="paragraph--center">
        <a href="<?= url('admin') ?>">
            Revenir à l’administration
        </a>
    </p>
</section>
