<?php
    $this->layout('admin.phtml', [
        'title' => 'Affichage d’un paiement',
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">
            Paiement du <?= format_date($payment->created_at, '%d %B') ?><br />
            <?= $payment->account()->email ?>
        </h1>
    </div>

    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <?php if ($payment->is_paid): ?>
        <p class="paragraph--featured">
            Ce paiement a été payé.
        </p>
    <?php else: ?>
        <p class="paragraph--featured">
            Ce paiement n’a pas été encore été payé.
        </p>

        <div class="columns columns--center">
            <div class="columns__item">
                <form method="post" action="<?= url('confirm admin payment', ['id' => $payment->id]) ?>" >
                    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                    <div class="form__actions">
                        <button type="submit" class="button--primary">
                            Confirmer le paiement
                        </button>
                    </div>
                </form>
            </div>

            <div class="columns__item">
                <?php if (!$payment->invoice_number): ?>
                    <form method="post" action="<?= url('destroy admin payment', ['id' => $payment->id]) ?>">
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

                        ou
                        <button type="submit" class="button--ghost">
                            Supprimer le paiement
                        </button>
                    </form>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>

    <p class="paragraph--center">
        <a href="<?= url('admin') ?>">
            Revenir à l’administration
        </a>
    </p>
</section>
