<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <link rel="shortcut icon" href="<?= url_static('favicon-32px.png') ?>">
        <meta name="robots" content="noindex, nofollow">

        <link rel="stylesheet" href="<?= url_static('account.css') ?>">
        <link rel="stylesheet" href="<?= url_static('forms.css') ?>">

        <script src="<?= url_static('stimulus.min.js') ?>" defer></script>
        <script src="<?= url_static('amount-selector.js') ?>" defer></script>

        <title><?= $title ?></title>
    </head>

    <body>
        <div class="layout">
            <header class="layout__header">
                <a href="<?= url('account') ?>">
                    <img
                        class="logo"
                        src="<?= url_static('logo.svg') ?>"
                        width="125"
                        height="42"
                        alt="Flus"
                     />
                </a>

                <div class="layout__header-separator"></div>

                <form method="post" action="<?= url('account logout') ?>">
                    <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                    <button class="button--default" type="submit">
                        Revenir à l’application
                    </button>
                </form>
            </header>

            <nav class="layout__nav">
                <ul>
                    <li class="layout__nav-item--subscription">
                        <a
                            href="<?= url('subscription init') ?>"
                            <?= $current_page === 'subscription' ? 'aria-current="page"' : '' ?>
                        >
                            Abonnement
                        </a>
                    </li>

                    <li class="layout__nav-item--profile">
                        <a
                            href="<?= url('account address') ?>"
                            <?= $current_page === 'profile' ? 'aria-current="page"' : '' ?>
                        >
                            Profil
                        </a>
                    </li>
                </ul>
            </nav>

            <main class="layout__content" id="contenu">
                <?= $this->safe('content') ?>
            </main>
        </div>
    </body>
</html>
