<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <link rel="shortcut icon" href="<?= url_static('favicon-32px.png') ?>">
        <meta name="robots" content="noindex, nofollow">

        <link rel="stylesheet" href="<?= url_static('admin.css') ?>">
        <link rel="stylesheet" href="<?= url_static('forms.css') ?>">

        <script src="<?= url_static('stimulus.min.js') ?>" defer></script>
        <script src="<?= url_static('admin/payment-type-selector.js') ?>" defer></script>

        <title><?= $title ?></title>
    </head>

    <body>
        <div class="layout">
            <header class="layout__header">
                <a href="<?= url('admin') ?>">
                    <img
                        class="logo"
                        src="<?= url_static('logo.svg') ?>"
                        width="125"
                        height="42"
                        alt="Flus"
                     />
                </a>

                <?php if ($current_user): ?>
                    <div class="layout__header-separator"></div>

                    <a class="layout__header-link" href="<?= url('home') ?>">
                        revenir au site
                    </a>

                    <form method="post" action="<?= url('logout') ?>">
                        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                        <button class="button--ghost" type="submit">
                            Se déconnecter
                        </button>
                    </form>
                <?php endif; ?>
            </header>

            <main class="layout__content" id="contenu">
                <?= $this->safe('content') ?>
            </main>
        </div>
    </body>
</html>
