<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <title><?= $title ?></title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <?php if (isset($description)): ?>
            <meta name="description" content="<?= $description ?>" />
        <?php endif; ?>

        <link rel="canonical" href="<?= $canonical ?>">
        <link rel="alternate" href="<?= url_full('home') ?>carnet/feeds/all.atom.xml" type="application/atom+xml" title="Articles du carnet de flus" />
        <link rel="shortcut icon" href="<?= url_static('favicon-32px.png') ?>">

        <link rel="stylesheet" href="<?= url_static('assets/stylesheets/application.css') ?>">
        <script src="<?= url_static('assets/javascripts/application.js') ?>" defer></script>

        <?php if ($plausible_url): ?>
            <script src="<?= $plausible_url ?>/js/script.js" defer data-domain="<?= $current_host ?>"></script>
        <?php endif; ?>

        <?php if (isset($og)): ?>
            <meta property="og:title" content="<?= $title ?>" />
            <meta property="og:type" content="<?= $og['type'] ?>" />
            <meta property="og:description" content="<?= $description ?>" />
            <meta property="og:locale" content="fr_FR" />
            <meta property="og:url" content="<?= $canonical ?>" />
            <meta property="og:image" content="<?= $og['image'] ?>" />
            <meta name="twitter:card" content="<?= $og['twitter_card'] ?>">
            <meta name="fediverse:creator" content="@flus@piaille.fr" />
        <?php endif; ?>
    </head>

    <body>
        <nav class="accessibility-nav" aria-label="Menu de liens d’évitement">
            <a href="#contenu" class="button button--primary">
                Aller au contenu
            </a>
        </nav>

        <div class="layout">
            <header class="layout__header" role="banner">
                <nav
                    class="header__navigation"
                    data-controller="navigation"
                    aria-label="Menu de navigation principal"
                    role="navigation"
                >
                    <button
                        class="navigation__menubutton button button--ghost only-mobile"
                        data-action="navigation#switch"
                        data-target="navigation.button"
                        aria-expanded="false"
                    >
                        <?= icon('bars') ?>
                        <?= icon('times') ?>

                        <span class="sr-only">
                            Ouvrir le menu de navigation
                        </span>
                    </button>

                    <ul class="navigation__container">
                        <li>
                            <a
                                class="navigation__link"
                                href="<?= url('features') ?>"
                                <?= $current_page === 'features' ? 'aria-current="page"' : '' ?>
                            >
                                Fonctionnalités
                            </a>
                        </li>

                        <li>
                            <a
                                class="navigation__link"
                                href="<?= url('pricing') ?>"
                                <?= $current_page === 'pricing' ? 'aria-current="page"' : '' ?>
                            >
                                Tarifs
                            </a>
                        </li>

                        <li>
                            <a
                                class="navigation__link"
                                href="<?= url_full('home') ?>carnet/"
                            >
                                Blog
                            </a>
                        </li>

                        <li>
                            <a
                                class="navigation__link"
                                href="<?= url('contact') ?>"
                                <?= $current_page === 'contact' ? 'aria-current="page"' : '' ?>
                            >
                                Contact
                            </a>
                        </li>

                        <li class="only-mobile">
                            <a
                                class="navigation__link"
                                href="https://app.flus.fr/login"
                            >
                                Se connecter
                            </a>
                        </li>

                        <li class="only-mobile">
                            <a
                                class="navigation__link"
                                href="https://app.flus.fr/registration"
                            >
                                S’inscrire
                            </a>
                        </li>
                    </ul>
                </nav>

                <div class="header__logo">
                    <a
                        href="<?= url('home') ?>"
                        <?= $current_page === 'home' ? 'aria-current="page"' : '' ?>
                        rel="home"
                        title="Flus - Accueil"
                    >
                        <img
                            src="<?= url_static('logo-white.svg') ?>"
                            height="40"
                            alt="Flus"
                        />
                    </a>
                </div>

                <div class="col--extend text--right no-mobile">
                    <a class="button button--primary" href="https://app.flus.fr/registration">
                        <?= icon('arrow-left', 'rotate180') ?>
                        S’inscrire
                    </a>

                    <a class="button button--ghost" href="https://app.flus.fr/login">
                        Se connecter
                    </a>
                </div>
            </header>

            <main class="layout__content" id="contenu" role="main" tabindex="-1">
                <?= $this->safe('content') ?>
            </main>

            <footer class="layout__footer" role="contentinfo">
                <div class="wrapper wrapper--larger wrapper--center flow flow--large">
                    <div class="cols cols--center cols--gap-large">
                        <a href="<?= url('home') ?>" rel="home" title="Flus - Accueil">
                            <img
                                class="footer__logo"
                                alt="Flus"
                                src="<?= url_static('logo.svg') ?>"
                            />
                        </a>

                        <ul class="list--nostyle list--inline col--extend cols cols--center cols--hcenter cols--gap">
                            <li>
                                <a class="footer__link" href="<?= url('features') ?>">
                                    Fonctionnalités
                                </a>
                            </li>

                            <li>
                                <a class="footer__link" href="<?= url('pricing') ?>">
                                    Tarifs
                                </a>
                            </li>

                            <li>
                                <a class="footer__link" href="<?= url_full('home') ?>carnet/">
                                    Blog
                                </a>
                            </li>

                            <li>
                                <a class="footer__link" href="<?= url('contact') ?>">
                                    Contact
                                </a>
                            </li>
                        </ul>

                        <p>
                            <a class="button button--primary" href="https://app.flus.fr/registration">
                                <?= icon('arrow-left', 'rotate180') ?>
                                S’inscrire sur Flus
                            </a>
                        </p>
                    </div>

                    <hr class="footer__separator">

                    <ul class="list--nostyle list--inline text--small text--center">
                        <li>
                            <a class="footer__link" href="<?= url('credits') ?>">
                                Crédits
                            </a>
                        </li>

                        <li>
                            <a class="footer__link" href="<?= url('security') ?>">
                                Sécurité
                            </a>
                        </li>

                        <li>
                            <a class="footer__link" href="<?= url('legal') ?>">
                                Informations légales
                            </a>
                        </li>

                        <li>
                            <a class="footer__link" href="<?= url('sitemap') ?>">
                                Plan du site
                            </a>
                        </li>

                        <li>
                            <a class="footer__link" href="https://github.com/flusio">
                                Code source
                            </a>
                        </li>

                        <li>
                            <a class="footer__link" href="https://status.flus.fr">
                                Statut des services
                            </a>
                        </li>
                    </ul>

                    <p class="text--center">
                        Retrouvez Flus sur

                        <a class="footer__link" rel="me" href="https://www.linkedin.com/company/flus-fr">
                            <img width="25" alt="" src="<?= url_static('icon-linkedin.svg') ?>" />
                            LinkedIn
                        </a>

                        et

                        <a class="footer__link" rel="me" href="https://piaille.fr/@flus">
                            <img width="25" alt="" src="<?= url_static('icon-mastodon.svg') ?>" />
                            Mastodon
                        </a>
                    </p>

                    <p class="footer__license text--small text--center">
                        Licence libre

                        <a href="https://github.com/flusio/Flus/blob/main/LICENSE.txt">
                            AGPL-3.0
                        </a>
                    </p>
                </div>
            </footer>
        </div>
    </body>
</html>
