<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <link rel="canonical" href="<?= $canonical ?>">
        <link rel="shortcut icon" href="<?= url_static('favicon-32px.png') ?>">

        <link rel="stylesheet" href="<?= url_static('style.css') ?>">

        <script src="<?= url_static('stimulus.min.js') ?>" defer></script>
        <script src="<?= url_static('popup.js') ?>" defer></script>

        <?php if ($load_form_statics): ?>
            <link rel="stylesheet" href="<?= url_static('forms.css') ?>">
        <?php endif; ?>

        <link href="https://flus.fr/carnet/feeds/all.atom.xml" type="application/atom+xml" rel="alternate" title="Articles du carnet de flus" />

        <title><?= $title ?></title>

        <?php if (isset($description)): ?>
            <meta name="description" content="<?= $description ?>" />
        <?php endif; ?>

        <?php if (isset($og)): ?>
            <meta property="og:title" content="<?= $title ?>" />
            <meta property="og:type" content="<?= $og['type'] ?>" />
            <meta property="og:description" content="<?= $description ?>" />
            <meta property="og:locale" content="fr_FR" />
            <meta property="og:url" content="<?= $canonical ?>" />
            <meta property="og:image" content="<?= $og['image'] ?>" />
            <meta name="twitter:card" content="<?= $og['twitter_card'] ?>">
            <meta name="twitter:site" content="@flus_fr">
        <?php endif; ?>
    </head>

    <body>
        <div class="layout">
            <header class="layout__header">
                <nav class="nav">
                    <details
                        class="nav__popup popup only-mobile"
                        data-controller="popup"
                        data-action="click@window->popup#close"
                    >
                        <summary class="popup__opener" title="Ouvrir le menu">
                            <i class="icon icon--bars"></i>

                            <span class="sr-only">
                                Ouvrir le menu
                            </span>
                        </summary>

                        <ul class="popup__container">
                            <li class="popup__item popup__item--close">
                                <button
                                    type="button"
                                    class="popup__button"
                                    data-action="popup#toggle"
                                    aria-label="Fermer"
                                    title="Fermer cette fenêtre"
                                >
                                    <i class="icon icon--only icon--times"></i>
                                </button>
                            </li>

                            <li class="popup__item <?= $current_page === 'home' ? 'popup__item--active' : '' ?>">
                                <a class="popup__link" href="<?= url('home') ?>">
                                    Accueil
                                </a>
                            </li>

                            <li class="popup__item <?= $current_page === 'project' ? 'popup__item--active' : '' ?>">
                                <a class="popup__link" href="<?= url('project') ?>">
                                    Projet
                                </a>
                            </li>

                            <li class="popup__item <?= $current_page === 'pricing' ? 'popup__item--active' : '' ?>">
                                <a class="popup__link" href="<?= url('pricing') ?>">
                                    Tarifs
                                </a>
                            </li>

                            <li class="popup__item">
                                <a class="popup__link" href="https://flus.fr/carnet/">
                                    Carnet
                                </a>
                            </li>
                        </ul>
                    </details>

                    <a class="nav__link no-mobile" href="<?= url('home') ?>">
                        <img
                            class="nav__image"
                            src="<?= url_static('logo.svg') ?>"
                            height="40"
                            alt="Flus"
                         />
                    </a>

                    <div class="nav__space"></div>

                    <ul class="nav__container no-mobile">
                        <li class="nav__item <?= $current_page === 'project' ? 'nav__item--active' : '' ?>">
                            <a class="nav__link" href="<?= url('project') ?>">
                                Projet
                            </a>
                        </li>

                        <li class="nav__item <?= $current_page === 'pricing' ? 'nav__item--active' : '' ?>">
                            <a class="nav__link" href="<?= url('pricing') ?>">
                                Tarifs
                            </a>
                        </li>

                        <li class="nav__item">
                            <a class="nav__link" href="https://flus.fr/carnet/">
                                Carnet
                            </a>
                        </li>
                    </ul>

                    <a class="nav__link nav__link--featured" href="https://app.flus.fr/login">
                        Se connecter
                    </a>
                </nav>
            </header>

            <main class="layout__content" id="contenu">
                <?= $this->safe('content') ?>
            </main>

            <footer class="layout__footer">
                <p>
                    <a class="call-to-action" href="https://app.flus.fr/registration">
                        S’inscrire sur Flus
                    </a>
                </p>

                <p class="paragraph--center">
                    <a href="<?= url('contact') ?>">Contact</a>&nbsp;·&nbsp;<a href="<?= url('security') ?>">Sécurité</a>&nbsp;·&nbsp;<a href="<?= url('credits') ?>">Crédits</a>&nbsp;·&nbsp;<a href="<?= url('legal') ?>">Mentions légales</a>
                </p>

                <p class="paragraph--center">
                    <a href="https://flus.io">Accéder à Flus 1</a>&nbsp;·&nbsp;<a href="https://status.flus.io/">Statut des services</a>
                </p>

                <p class="copyright">
                    Licence libre <a href="https://github.com/flusio/flus.fr/blob/main/LICENSE.txt">AGPL-3.0</a> (<a href="https://github.com/flusio">code source</a>)
                </p>
            </footer>
        </div>
    </body>
</html>
