<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <title><?= $title ?></title>

        <meta name="viewport" content="initial-scale=1.0" />
        <meta name="robots" content="noindex">

        <link rel="shortcut icon" href="<?= url_static('favicon-32px.png') ?>">

        <link rel="stylesheet" href="<?= url_static('style/main.css') ?>">

        <?php if ($plausible_url): ?>
            <script defer data-domain="<?= $current_host ?>" src="<?= $plausible_url ?>/js/script.js"></script>
        <?php endif; ?>
    </head>

    <body>
        <div class="layout">
            <main class="layout__content" id="contenu">
                <?= $this->safe('content') ?>

                <?php if ($environment !== 'production' && $error): ?>
                    <pre class="error-box"><?= (string)$error ?></pre>
                <?php endif; ?>
            </main>
        </div>
    </body>
</html>
