<?php
    $this->layout('admin.phtml', [
        'title' => 'Comptes utilisateurices',
        'current_page' => 'admin accounts',
    ]);
?>

<section class="panel">
    <div class="wrapper flow flow--larger">
        <h1>
            <?= count($accounts) ?> comptes utilisateurices
        </h1>

        <?php if ($accounts): ?>
            <ul class="list--nostyle list--border list--strip list--padded">
                <?php foreach ($accounts as $account): ?>
                    <li class="flow flow--small">
                        <div class="cols cols--gap cols--center">
                            <div class="col--extend">
                                <strong>
                                    <?= $this->protect($account->email) ?>
                                </strong>
                            </div>

                            <div>
                                <a class="button button--block" href="<?= url('admin account', ['id' => $account->id]) ?>">
                                    Voir le compte
                                </a>
                            </div>
                        </div>

                        <div class="cols cols--gap cols--center">
                            <div class="col--extend">
                                <?php if ($account->isFree()): ?>
                                    Compte gratuit
                                <?php else: ?>
                                    Expire le <?= _d($account->expired_at, 'dd MMMM yyyy') ?>
                                <?php endif; ?>

                                —
                                <?php if ($account->preferred_service === 'freshrss'): ?>
                                    FreshRSS
                                <?php else: ?>
                                    Flus
                                <?php endif; ?>
                            </div>

                            <div>
                                <?= $account->count_payments ?> paiements
                            </div>
                        </div>
                    </tr>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <div class="wrapper wrapper--small">
                <p class="panel panel--grey panel--rounded text--center text--bold">
                    Il n’y a aucun compte à afficher.
                </p>
            </div>
        <?php endif; ?>
    </div>
</section>
