<?php
    $this->layout('admin.phtml', [
        'title' => 'Compte utilisateurice',
    ]);
?>

<div class="header">
    <h1 class="header__title">
        Abonnement de <?= $this->protect($account->email) ?>
    </h1>
</div>

<p class="paragraph--center">
    <a href="<?= url('admin accounts') ?>">
        Retourner aux comptes
    </a>
</p>

<div class="section__intro">
    <p>
        <?php if ($account->isFree()): ?>
            Cette personne bénéficie d’un abonnement gratuit.
        <?php elseif ($account->hasExpired()): ?>
            <strong>
                Son abonnement a expiré le <?= _d($account->expired_at, 'dd MMMM yyyy') ?>.
            </strong>
        <?php else: ?>
            Son abonnement expirera le <strong><?= _d($account->expired_at, 'dd MMMM yyyy') ?>.</strong>
        <?php endif; ?>
    </p>
</div>

<form method="post" action="<?= url('update admin account', ['id' => $account->id]) ?>">
    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

    <div class="form-group">
        <label for="expired-at">
            Expire le
        </label>

        <input
            id="expired-at"
            name="expired-at"
            type="date"
            value="<?= $expired_at->format('Y-m-d') ?>"
            required
        />
    </div>

    <div class="form__actions">
        <button type="submit" class="button--default">
            Sauvegarder le changement
        </button>
    </div>
</form>

<hr />

<div class="header">
    <h2 class="header__title">
        Paiements passés
    </h2>
</div>

<?php if ($payments): ?>
    <table>
        <tbody>
            <?php foreach ($payments as $payment): ?>
                <tr <?= !$payment->completed_at ? 'class="row--ghost"' : ''?> >
                    <td class="cell--right">
                        <?= format_amount($payment->amount) ?>
                    </td>

                    <td>
                        <?php if ($payment->type === 'subscription' && $payment->frequency === 'month'): ?>
                            Abonnement mois
                        <?php elseif ($payment->type === 'subscription' && $payment->frequency === 'year'): ?>
                            Abonnement année
                        <?php elseif ($payment->type === 'common_pot'): ?>
                            Cagnotte
                        <?php elseif ($payment->type === 'credit'): ?>
                            Crédit
                        <?php else: ?>
                            Heu… non
                        <?php endif; ?>
                    </td>

                    <td>
                        <?php if ($payment->completed_at): ?>
                            <?= _d($payment->completed_at, 'dd MMM yyyy') ?>
                        <?php else: ?>
                            traitement en cours
                        <?php endif; ?>
                    </td>

                    <td>
                        <?php if ($payment->invoice_number): ?>
                            <a href="<?= url('invoice download pdf', ['id' => $payment->id]) ?>">
                                <?= $payment->invoice_number ?>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p class="paragraph--center paragraph--secondary">
        Il n’y a aucun paiement à afficher.
    </p>
<?php endif; ?>
