<?php
    $this->layout('admin.phtml', [
        'title' => 'Compte utilisateurice',
    ]);
?>

<div class="header">
    <h1 class="header__title">
        Abonnement de <?= $this->protect($account->email) ?>
    </h1>
</div>

<p class="paragraph--center">
    <a href="<?= url('admin accounts') ?>">
        Retourner aux comptes
    </a>
</p>

<div class="section__intro">
    <p>
        <?php if ($account->isFree()): ?>
            Cette personne bénéficie d’un abonnement gratuit.
        <?php elseif ($account->hasExpired()): ?>
            <strong>
                Son abonnement a expiré le <?= format_date($account->expired_at, '%d %B %Y') ?>.
            </strong>
        <?php else: ?>
            Son abonnement expirera le <strong><?= format_date($account->expired_at, '%d %B %Y') ?>.</strong>
        <?php endif; ?>
    </p>
</div>

<hr />

<div class="header">
    <h2 class="header__title">
        Paiements passés
    </h2>
</div>

<?php if ($payments): ?>
    <table>
        <tbody>
            <?php foreach ($payments as $payment): ?>
                <tr <?= !$payment->completed_at ? 'class="row--ghost"' : ''?> >
                    <td class="cell--right">
                        <?= format_amount($payment->amount) ?>
                    </td>

                    <td>
                        <?php if ($payment->type === 'subscription' && $payment->frequency === 'month'): ?>
                            Abonnement mois
                        <?php elseif ($payment->type === 'subscription' && $payment->frequency === 'year'): ?>
                            Abonnement année
                        <?php elseif ($payment->type === 'common_pot'): ?>
                            Cagnotte
                        <?php else: ?>
                            Heu… non
                        <?php endif; ?>
                    </td>

                    <td>
                        <?php if ($payment->completed_at): ?>
                            <?= format_date($payment->completed_at, '%d %b %Y') ?>
                        <?php else: ?>
                            non payée
                        <?php endif; ?>
                    </td>

                    <td>
                        <?php if ($payment->invoice_number): ?>
                            <a href="<?= url('download_pdf_from_admin', ['id' => $payment->id]) ?>">
                                <?= $payment->invoice_number ?>
                            </a>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p class="paragraph--center paragraph--secondary">
        Il n’y a aucun paiement à afficher.
    </p>
<?php endif; ?>
