<?php
    $this->layout('admin.phtml', [
        'title' => 'Connexion à l’administration',
    ]);
?>

<section class="panel">
    <div class="wrapper wrapper--small flow flow--larger">
        <h1>
            Connexion à l’administration
        </h1>

        <form method="post" action="<?= url('create_session') ?>" class="flow flow--large">
            <?php if ($error): ?>
                <p class="form__error">
                    <?= $error ?>
                </p>
            <?php endif; ?>

            <div class="flow flow--small">
                <label for="password">Mot de passe</label>

                <input
                    type="password"
                    name="password"
                    id="password"
                    required
                    autofocus
                    value="<?= isset($password) ? $password : '' ?>"
                />
            </div>

            <div class="text--center">
                <button type="submit" class="button--primary">
                    Se connecter
                </button>
            </div>

            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

            <?php if (isset($from)): ?>
                <input type="hidden" name="from" value="<?= $from ?>" />
            <?php endif; ?>
        </form>

        <p class="text--center">
            <a href="<?= url('home') ?>">
                Retour à l’accueil
            </a>
        </p>
    </div>
</section>
