services:
    php:
        image: flusfr:dev
        build: .
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ..:/var/www/html:z
        user: $USER
        links:
            - stripe-mock

    job_worker:
        image: flusfr:dev
        build: .
        restart: unless-stopped
        command: php cli jobs watch
        volumes:
            - ..:/var/www/html:z
        user: $USER

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ..:/var/www/html:z
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
        links:
            - php

    mailpit:
        image: axllent/mailpit
        restart: unless-stopped
        ports:
            - "8025:8025"
            - "1025:1025"

    stripe-mock:
        image: stripe/stripe-mock:latest
        restart: unless-stopped
        ports:
            - "12111-12112:12111-12112"
