version: '3'

services:
    php:
        build: .
        restart: unless-stopped
        ports:
            - "9000:9000"
        volumes:
            - ..:/var/www/html:z
        env_file:
            - ../.env
        user: $USER
        links:
            - stripe-mock

    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ..:/var/www/html:z
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:z
        links:
            - php

    stripe-mock:
        image: stripe/stripe-mock:latest
        restart: unless-stopped
        ports:
            - "12111-12112:12111-12112"
