<?php
    $this->layout('base.phtml', [
        'title' => 'Visite guidée : les signets · Flus',
        'canonical' => url_full('tour', ['page' => 'signets']),
        'current_page' => 'tour',
        'description' => 'Stockez dans vos signets les liens que vous consulterez plus tard',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('flus.png'),
            'twitter_card' => 'summary',
        ],
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">Visite guidée : les signets</h1>
    </div>

    <p class="paragraph--featured paragraph--short">
        Stockez dans vos signets les liens que vous consulterez plus tard.
    </p>

    <div class="screenshot tour__video">
        <video controls class="illustration screenshot__image">
            <source src="https://flus.fr/carnet/visite/signets.webm" type="video/webm">
            <source src="https://flus.fr/carnet/visite/signets.mp4" type="video/mp4">

            <p>
                Votre navigateur ne prend pas en charge cette vidéo. Vous pouvez
                <a href="#video-transcript">lire la transcription</a> à la place.
            </p>
        </video>
    </div>

    <details id="video-transcript" class="tour__video-transcript">
        <summary>Transcription de la vidéo</summary>

        <p>
            Un navigateur Web est ouvert sur le journal en ligne
            «&nbsp;<a href="https://lesjours.fr/obsessions/cahiers-doleances-grand-debat/ep1-gilets-jaunes/">Les Jours</a>&nbsp;».
        </p>

        <p>
            La souris se dirige vers le haut du navigateur pour ouvrir le menu
            de l’extension Flus.
        </p>

        <p>
            Elle clique sur le bouton «&nbsp;Ajouter aux signets&nbsp;» qui est
            apparu. Après un court temps de chargement, l’extension indique que
            le lien a été ajouté à Flus.
        </p>

        <p>
            La souris se dirige ensuite vers la section des onglets du
            navigateur pour en changer et ouvrir Flus sur la page
            «&nbsp;Journal&nbsp;».
        </p>

        <p>
            Enfin, la souris ouvre la page des signets de Flus et met en
            évidence que le lien s’y trouve bien.
        </p>
    </details>

    <p class="paragraph--short">
        Bonne nouvelle&nbsp;: il existe un monde dans lequel vous ne craignez
        plus de perdre vos innombrables onglets ouverts.
    </p>

    <nav class="tour__navigation">
        <p class="tour__navigation-info">
            Continuez la visite avec…
        </p>

        <a class="tour__navigation-next call-to-action" href="<?= url('tour page', ['page' => 'collections']) ?>">
            Les collections →
        </a>

        <br />

        <a class="tour__navigation-previous" href="<?= url('tour page', ['page' => 'flux']) ?>">
            ← Les flux
        </a>

        <p class="tour__navigation-info">
            ou…
        </p>

        <a class="tour__navigation-home" href="<?= url('home') ?>">
            Revenir à l’accueil
        </a>
    </nav>
</section>
