<?php
    $this->layout('base.phtml', [
        'title' => 'Visite guidée : les collections · Flus',
        'canonical' => url_full('tour', ['page' => 'collections']),
        'current_page' => 'tour',
        'description' => 'Commentez et partagez votre veille grâce aux collections',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('flus.png'),
            'twitter_card' => 'summary',
        ],
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">Visite guidée : les collections</h1>
    </div>

    <p class="paragraph--featured paragraph--short">
        Commentez et partagez votre veille grâce aux collections.
    </p>

    <div class="screenshot tour__video">
        <video controls class="illustration screenshot__image">
            <source src="https://flus.fr/carnet/visite/collections.webm" type="video/webm">
            <source src="https://flus.fr/carnet/visite/collections.mp4" type="video/mp4">

            <p>
                Votre navigateur ne prend pas en charge cette vidéo. Vous pouvez
                <a href="#video-transcript">lire la transcription</a> à la place.
            </p>
        </video>
    </div>

    <details id="video-transcript" class="tour__video-transcript">
        <summary>Transcription de la vidéo</summary>

        <p>
            Un navigateur Web est ouvert sur la page des collections de Flus.
            On y voit une collection intitulée «&nbsp;Mes partages&nbsp;»,
            ainsi que quelques collections suivies.
        </p>

        <p>
            La souris clique sur le bouton «&nbsp;Créer une collection&nbsp;»
            et une fenêtre modale s’ouvre pour demander quelques informations.
        </p>

        <p>
            La collection est nommée «&nbsp;Mes favoris&nbsp;» et décrite
            par «&nbsp;Tous les liens qui m’inspirent&nbsp;». La souris valide
            la création de la collection.
        </p>

        <p>
            Le navigateur est redirigé vers la page de cette nouvelle
            collection qui apparaît donc vide.
        </p>

        <p>
            La souris ouvre la page du journal, puis le remplit avec 3 liens
            venant des signets. Elle clique ensuite sur le bouton
            «&nbsp;Ajouter aux collections&nbsp;» de l’un de ces liens.
        </p>

        <p>
            Elle sélectionne ensuite la collection qui a été créée
            préalablement, puis ajoute le commentaire «&nbsp;C’était vraiment
            très intéressant&nbsp;!&nbsp;» Elle valide le tout, ce qui a pour
            effet de marquer le lien comme lu et de le retirer du journal.
        </p>

        <p>
            La souris rouvre la page des collections, puis celle de la
            collection elle-même. On voit que le lien a bien été ajouté à la
            collection et il apparaît qu’un commentaire y est associé.
        </p>

        <p>
            La souris ouvre enfin la page des commentaires du lien et montre le
            commentaire qui a été rédigé depuis le journal.
        </p>
    </details>

    <p class="paragraph--short">
        Les collections servent également à organiser vos liens personnels afin
        de les retrouver facilement. N’hésitez pas à en abuser&nbsp;!
    </p>

    <nav class="tour__navigation">
        <p class="tour__navigation-info">
            Continuez la visite avec…
        </p>

        <a class="tour__navigation-next call-to-action" href="<?= url('tour page', ['page' => 'pocket']) ?>">
            Pocket →
        </a>

        <br />

        <a class="tour__navigation-previous" href="<?= url('tour page', ['page' => 'signets']) ?>">
            ← Les signets
        </a>

        <p class="tour__navigation-info">
            ou…
        </p>

        <a class="tour__navigation-home" href="<?= url('home') ?>">
            Revenir à l’accueil
        </a>
    </nav>
</section>
