<?php
    $this->layout('base.phtml', [
        'title' => 'Visite guidée : les flux · Flus',
        'canonical' => url_full('tour', ['page' => 'flux']),
        'current_page' => 'tour',
        'description' => 'Suivez les sites, émissions de podcasts, chaînes YouTube que vous aimez pour ne rien manquer',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('flus.png'),
            'twitter_card' => 'summary',
        ],
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">Visite guidée : les flux</h1>
    </div>

    <p class="paragraph--featured paragraph--short">
        Suivez les sites, émissions de podcasts, chaînes YouTube que vous aimez
        pour ne rien manquer.
    </p>

    <div class="screenshot tour__video">
        <video controls class="illustration screenshot__image">
            <source src="https://flus.fr/carnet/visite/flux.webm" type="video/webm">
            <source src="https://flus.fr/carnet/visite/flux.mp4" type="video/mp4">

            <p>
                Votre navigateur ne prend pas en charge cette vidéo. Vous pouvez
                <a href="#video-transcript">lire la transcription</a> à la place.
            </p>
        </video>
    </div>

    <details id="video-transcript" class="tour__video-transcript">
        <summary>Transcription de la vidéo</summary>

        <p>
            Un navigateur Web est ouvert sur la chaîne YouTube
            «&nbsp;<a href="https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA">Science Étonnante</a>&nbsp;».
        </p>

        <p>
            La souris se dirige vers le champ <abbr>URL</abbr> du navigateur et
            copie sa valeur.
        </p>

        <p>
            La souris se dirige ensuite vers la section des onglets du
            navigateur pour en changer et ouvrir Flus sur la page
            «&nbsp;Nouveau lien&nbsp;».
        </p>

        <p>
            La souris sélectionne le champ présent sur la page, y colle
            l’<abbr>URL</abbr> copiée préalablement et valide le formulaire.
        </p>

        <p>
            Deux éléments s’affichent à l’écran&nbsp;: un lien pointant vers la
            page YouTube et le flux découvert automatiquement depuis ce lien.
            La souris clique sur ce second élément, ce qui ouvre le flux dans
            Flus.
        </p>

        <p>
            Les liens présents au sein du flux sont survolés, puis la souris
            clique sur le bouton «&nbsp;Suivre&nbsp;» présent en haut de la
            page.
        </p>

        <p>
            Enfin, la souris clique sur l’onglet «&nbsp;Collections&nbsp;» de
            Flus et met en évidence que le flux de Science Étonnante est
            maintenant suivi par l’utilisateur.
        </p>
    </details>

    <p class="paragraph--short">
        N’importe quel site publiant un flux se trouve dans Flus. Vous devriez
        rapidement y trouver votre bonheur.
    </p>

    <nav class="tour__navigation">
        <p class="tour__navigation-info">
            Continuez la visite avec…
        </p>

        <a class="tour__navigation-next call-to-action" href="<?= url('tour page', ['page' => 'signets']) ?>">
            Les signets →
        </a>

        <br />

        <a class="tour__navigation-previous" href="<?= url('tour page', ['page' => 'journal']) ?>">
            ← Le journal
        </a>

        <p class="tour__navigation-info">
            ou…
        </p>

        <a class="tour__navigation-home" href="<?= url('home') ?>">
            Revenir à l’accueil
        </a>
    </nav>
</section>
