<?php
    $this->layout('base.phtml', [
        'title' => 'Visite guidée : OPML · Flus',
        'canonical' => url_full('tour', ['page' => 'opml']),
        'current_page' => 'tour',
        'description' => 'Importez vos flux depuis un fichier OPML',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('flus.png'),
            'twitter_card' => 'summary',
        ],
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">Visite guidée : <abbr>OPML</abbr></h1>
    </div>

    <p class="paragraph--featured paragraph--short">
        Importez vos flux depuis un fichier <abbr>OPML</abbr>.
    </p>

    <div class="screenshot tour__video">
        <video controls class="illustration screenshot__image">
            <source src="https://flus.fr/carnet/visite/opml.webm" type="video/webm">
            <source src="https://flus.fr/carnet/visite/opml.mp4" type="video/mp4">

            <p>
                Votre navigateur ne prend pas en charge cette vidéo. Vous pouvez
                <a href="#video-transcript">lire la transcription</a> à la place.
            </p>
        </video>
    </div>

    <details id="video-transcript" class="tour__video-transcript">
        <summary>Transcription de la vidéo</summary>

        <p>
            Un navigateur Web est ouvert sur la page des collections de Flus.
            Seules deux collections sont affichées, mais aucune n’est une
            collection suivie.
        </p>

        <p>
            La souris se dirige vers le menu secondaire situé dans l’en-tête de
            Flus. Elle ouvre le menu «&nbsp;Compte et données&nbsp;», puis
            «&nbsp;Importer vos données depuis un fichier <abbr>OPML</abbr>&nbsp;».
        </p>

        <p>
            Flus affiche un bouton «&nbsp;Importer un fichier&nbsp;». La
            souris clique dessus et sélectionne un fichier depuis le navigateur
            de fichiers qui vient de s’ouvrir.
        </p>

        <p>
            Après un instant de chargement, Flus confirme que les données ont
            été importées depuis le fichier. La souris clique sur le bouton
            «&nbsp;Ok&nbsp;!&nbsp;»
        </p>

        <p>
            Le navigateur est redirigé vers la page des collections. On y voit
            désormais 8 collections suivies, réparties dans 3 groupes qui ont
            été déterminés depuis le fichier <abbr>OPML</abbr>.
        </p>
    </details>

    <p class="paragraph--short">
        La plupart des logiciels d’agrégation de flux exportent vos données
        sous ce format de fichier standardisé. Vous pouvez changer d’outil sans
        prise de tête.
    </p>

    <nav class="tour__navigation">
        <p class="tour__navigation-info">
            Vous voici à la fin de la visite. Prochaine étape&nbsp;:
        </p>

        <a class="tour__navigation-registration call-to-action" href="https://app.flus.fr/registration">
            Créer votre compte
        </a>

        <p class="tour__navigation-info">
            … ou reprendre&nbsp;?
        </p>

        <a class="tour__navigation-next" href="<?= url('tour page', ['page' => 'journal']) ?>">
            Le journal →
        </a>

        <br />

        <a class="tour__navigation-previous" href="<?= url('tour page', ['page' => 'pocket']) ?>">
            ← Pocket
        </a>
    </nav>
</section>
