<?php
    $this->layout('base.phtml', [
        'title' => 'Visite guidée : Pocket · Flus',
        'canonical' => url_full('tour', ['page' => 'pocket']),
        'current_page' => 'tour',
        'description' => 'Importez vos liens Pocket en quelques clics',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('flus.png'),
            'twitter_card' => 'summary',
        ],
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">Visite guidée : Pocket</h1>
    </div>

    <p class="paragraph--featured paragraph--short">
        Importez vos liens Pocket en quelques clics.
    </p>

    <div class="screenshot tour__video">
        <video controls class="illustration screenshot__image">
            <source src="https://flus.fr/carnet/visite/pocket.webm" type="video/webm">
            <source src="https://flus.fr/carnet/visite/pocket.mp4" type="video/mp4">

            <p>
                Votre navigateur ne prend pas en charge cette vidéo. Vous pouvez
                <a href="#video-transcript">lire la transcription</a> à la place.
            </p>
        </video>
    </div>

    <details id="video-transcript" class="tour__video-transcript">
        <summary>Transcription de la vidéo</summary>

        <p>
            Un navigateur Web est ouvert sur la page du journal de Flus.
        </p>

        <p>
            La souris se dirige vers le menu secondaire situé dans l’en-tête de
            Flus. Elle ouvre le menu «&nbsp;Compte et données&nbsp;», puis
            «&nbsp;Importer vos données depuis Pocket&nbsp;».
        </p>

        <p>
            Flus affiche un bouton «&nbsp;Se connecter à Pocket&nbsp;». La
            souris clique dessus.
        </p>

        <p>
            Le navigateur est redirigé vers Pocket, où il est demandé
            d’autoriser l’accès de Flus aux données Pocket. La souris confirme
            cet accès en cliquant sur le bouton «&nbsp;Autoriser&nbsp;».
        </p>

        <p>
            Le navigateur est renvoyé vers Flus qui fait patienter pendant un
            court instant, puis affiche un écran avec plusieurs options. La
            souris conserve les options par défaut et clique sur le bouton
            «&nbsp;Démarrer l’importation&nbsp;».
        </p>

        <p>
            Après un instant de chargement, Flus confirme que les données ont
            été importées depuis Pocket. La souris clique sur le bouton
            «&nbsp;Ok&nbsp;!&nbsp;»
        </p>

        <p>
            Le navigateur est redirigé vers la page des collections de Flus et
            4 collections apparaissent dont «&nbsp;Favoris Pocket&nbsp;» et
            «&nbsp;Liens Pocket&nbsp;».
        </p>

        <p>
            Pour terminer, la souris ouvre la collection «&nbsp;Liens Pocket&nbsp;»
            et met en évidence les liens qui ont été importés.
        </p>
    </details>

    <p class="paragraph--short">
        Pocket est un service populaire de «&nbsp;<em lang="en">bookmarking</em>&nbsp;»,
        mais il n’est malheureusement pas libre. Il est temps de récupérer vos
        données.
    </p>

    <nav class="tour__navigation">
        <p class="tour__navigation-info">
            Continuez la visite avec…
        </p>

        <a class="tour__navigation-next call-to-action" href="<?= url('tour page', ['page' => 'opml']) ?>">
            <abbr>OPML</abbr> →
        </a>

        <br />

        <a class="tour__navigation-previous" href="<?= url('tour page', ['page' => 'collections']) ?>">
            ← Les collections
        </a>

        <p class="tour__navigation-info">
            ou…
        </p>

        <a class="tour__navigation-home" href="<?= url('home') ?>">
            Revenir à l’accueil
        </a>
    </nav>
</section>
