<p>
    Bonjour,
</p>

<p>
    Votre paiement pour Flus a bien été pris en compte et je vous en
    remercie&nbsp;! Vous trouverez ci-joint le reçu associé à ce paiement.
</p>

<p>
    En vous souhaitant une bonne journée&nbsp;/&nbsp;soirée&nbsp;!
</p>

<p>
    Marien
</p>

<p>
    <i>
        <abbr>PS</abbr>&nbsp;: ce courriel vous a été envoyé parce que vous
        –&nbsp;ou quelqu’un d’autre&nbsp;– avez effectué un paiement sur le
        site <?= url_full('home#index') ?>
    </i>
</p>
