<?php
    $this->layout('error.phtml', [
        'title' => 'Erreur interne',
        'error' => $error,
    ]);
?>

<section class="panel">
    <div class="wrapper wrapper--small wrapper--center text--center flow flow--larger">
        <div class="panel panel--topaz panel--rounded flow flow--large">
            <h1>
                Erreur interne
            </h1>

            <div class="flow">
                <p>
                    Une erreur interne non prévue est survenue durant le traitement
                    de votre requête. Vous n’êtes pas responsable de cette erreur.
                </p>

                <p>
                    Si vous le souhaitez, vous pouvez
                    <a href="mailto:support@flus.fr">
                        me prévenir de cette erreur par courriel
                    </a>.
                </p>
            </div>

            <p>
                <a class="button button--primary" href="<?= url('home') ?>">
                    <?= icon('arrow-left') ?>

                    Revenir à la page d’accueil
                </a>
            </p>
        </div>

        <img
            alt=""
            src="<?= url_static('illustrations/server_down.svg') ?>"
            height="250"
        />
    </div>
</section>

