<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <link rel="stylesheet" href="<?= url_static('maintenance.css') ?>">
        <title>Flus revient…</title>
    </head>

    <body>
        <img
            class="logo"
            src="<?= url_static('logo.svg') ?>"
            width="221"
            height="75"
            alt="Flus"
         />

        <p>
            Ici, tout bientôt un nouveau site
        </p>
    </body>
</html>
