<?php
    $this->layout('base.phtml', [
        'title' => 'Politique de cookies · Flus',
        'canonical' => url_full('cookies policy'),
    ]);
?>

<nav class="layout__breadcrumb" aria-label="Fil d’Ariane">
    <ul class="list--nostyle">
        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('home') ?>" rel="home">
                Accueil
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('legal') ?>">
                Informations légales
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" aria-current="page" href="<?= url('cookies policy') ?>">
                Politique de cookies
            </a>
        </li>
    </ul>
</nav>

<article>
    <header class="panel panel--primary panel--header">
        <div class="wrapper wrapper--larger wrapper--center text--center flow">
            <h1>Politique de cookies</h1>

            <p>
                Applicable à compter du
                <time datetime="2024-10-19T00:00:00">
                    19 octobre 2024
                </time>
            </p>
        </div>
    </header>

    <div class="panel">
        <div class="wrapper wrapper--text wrapper--center text-container">
            <h2>Préambule</h2>

            <p>
                Un cookie est un petit fichier texte identifié par un nom et
                qui consiste en une suite d’informations transmises à votre
                navigateur lors de votre navigation sur un site web. Grâce à ce
                fichier, des informations concernant votre navigation sur ce
                site seront collectées. Votre navigateur web conservera alors
                ce fichier pendant une certaine durée afin de le renvoyer au
                serveur web à chacune de vos reconnexions. Ces cookies ont
                différentes natures et peuvent avoir différentes finalités.
            </p>

            <p>
                La présente politique de cookies vous informe sur les
                différents types de cookies susceptibles d’être déposés lors de
                votre navigation sur le Site accessible à partir de l’URL
                suivante&nbsp;: flus.fr (ci-après le «&nbsp;Site&nbsp;»).
            </p>

            <p>
                Notre politique de confidentialité vous informe sur les données
                personnelles traitées au moyen de ces cookies&nbsp;:
                <a href="<?= url('privacy policy') ?>">accéder à la politique de confidentialité</a>.
            </p>

            <p>
                Veuillez noter que cette politique de cookies est susceptible
                d’être modifiée ou complétée à tout moment par l’éditeur du
                Site, notamment en vue de se conformer à toute évolution légale
                ou technologique. Dans un tel cas, la date de sa mise à jour
                sera clairement identifiée en tête de la présente politique.
                Ces modifications vous engagent dès lors que vous aurez été
                informés de la mise en ligne de la politique de cookies mise à
                jour, et que vous aurez accepté celle-ci.
            </p>

            <h2>Article 1&nbsp;: Parties</h2>

            <p>
                La présente politique de cookies est applicable entre l’éditeur
                du Site, Marien Fressinaud Mas de Feix, ci-après
                «&nbsp;<strong>Flus</strong>&nbsp;», et toute personne se
                connectant au Site, ci-après
                «&nbsp;<strong>l’Internaute</strong>&nbsp;».
            </p>

            <h2>Article 2&nbsp;: Définitions</h2>

            <ul>
                <li>«&nbsp;<strong>Cookies</strong>&nbsp;»&nbsp;: fichier texte de petite taille déposé sur le navigateur de l’Internaute.</li>
                <li>«&nbsp;<strong>Internaute</strong>&nbsp;»&nbsp;: toute personne se connectant au Site.</li>
                <li>«&nbsp;<strong>Navigateur</strong>&nbsp;»&nbsp;: logiciel informatique permettant de visualiser des pages web et d’utiliser des liens hypertextes dans le but d’aller de pages en pages ou encore de télécharger du contenu en ligne.</li>
                <li>«&nbsp;<strong>Navigation</strong>&nbsp;»&nbsp;: action de l’Internaute consistant à se connecter au Site et à en consulter le contenu.</li>
                <li>«&nbsp;<strong>Site</strong>&nbsp;»&nbsp;: site Internet accessible à l’<abbr>URL</abbr> flus.fr ainsi que les sous-sites, sites miroirs, portails et variations d’<abbr>URL</abbr> y afférant.</li>
                <li>«&nbsp;<strong>Terminal</strong>&nbsp;»&nbsp;: élément matériel utilisé pour vous connecter au Site, pouvant par exemple consister en un ordinateur, une tablette, un téléphone mobile.</li>
            </ul>

            <h2>Article 3&nbsp;: Champ d’application</h2>

            <p>
                La présente politique de cookies est applicable à tout
                Internaute.
            </p>

            <p>
                L’Internaute reconnaît la valeur de preuve des systèmes
                d’enregistrement automatique de Flus et, sauf pour lui
                d’apporter preuve contraire, il renonce à les contester en cas
                de litige.
            </p>

            <p>
                L’acceptation de la présente politique de cookies suppose de la
                part des Internautes qu’ils jouissent de la capacité juridique
                nécessaire pour cela ou qu’ils aient au moins 16 ans, ou à
                défaut qu’ils en aient l’autorisation d’un tuteur ou d’un
                curateur s’ils sont incapables, de leur représentant légal
                s’ils ont moins de 16 ans, ou encore qu’ils soient titulaires
                d’un mandat s’ils agissent pour le compte d’une personne
                morale.
            </p>

            <h2>Article 4&nbsp;: Cookies</h2>

            <p>
                Cet article a vocation à vous décrire chacun des Cookies
                susceptibles d’être déposés sur votre Navigateur, leurs
                finalités et leur durée de validité.
            </p>

            <h3>4.1. Présentation générale des Cookies</h3>

            <h4>4.1.1. Les Cookies internes et tiers</h4>

            <p>
                Comme indiqué précédemment, les Cookies sont téléchargés sur
                votre Terminal via votre Navigateur lors de votre consultation
                du Site. Lors de votre Navigation ultérieure sur le Site au moyen du
                même Terminal, ce Terminal sera reconnu par notre Site.
            </p>

            <p>
                Ces Cookies peuvent être internes. Dans cette hypothèse, ces
                Cookies sont intégralement gérés par Flus. Nous avons donc la
                charge de la gestion de ces Cookies et sommes habilités à vous
                renseigner sur chacun d’entre eux.
            </p>

            <p>
                Ces Cookies peuvent également être déposés par des tiers. Dans
                cette hypothèse, Flus ne dispose d’aucune faculté s’agissant du
                paramétrage de ces Cookies. Il conviendra de vous rapprocher de
                chacun de ces tiers pour obtenir de plus amples informations
                sur la façon dont ils utilisent les Cookies.
            </p>

            <h4>4.1.2. Les Cookies persistants et cookies de session</h4>

            <p>
                Chaque Cookie diffère de part sa durée de vie. À ce titre, un
                Cookie pourra être persistant ou bien simplement de session.
            </p>

            <p>
                Un Cookie persistant est un Cookie stocké sur votre Navigateur
                jusqu’à ce que sa durée de conservation expire ou jusqu’à ce
                que vous fassiez le choix de le supprimer antérieurement à
                cette date d’expiration.
            </p>

            <p>
                Un Cookie de session est un Cookie qui sera quant à lui
                supprimé lorsque vous fermez votre Navigateur.
            </p>

            <h3>4.2. Cookies nécessaires</h3>

            <p>
                Conformément aux recommandations de la
                <a href="http://cnil.fr/">Commission nationale de l’informatique et des libertés</a>
                (Cnil), certains Cookies sont dispensés du recueil préalable de
                votre consentement dans la mesure où ils sont strictement
                nécessaires au fonctionnement du site Internet ou ont pour
                finalité exclusive de permettre ou faciliter la communication
                par voie électronique.
            </p>

            <p>
                L’emploi de ces cookies est fondé sur notre intérêt légitime à
                veiller au bon fonctionnement technique, à l’accessibilité et à
                l’utilisation du Site, et à vous fournir les services demandés.
                Il s’agit notamment des cookies d’identifiant de session,
                d’authentification, de session d’équilibrage de charge ainsi
                que des cookies de personnalisation de votre interface.
                Ces Cookies sont susceptibles d’être déposés par des Tiers
                listés dans le tableau ci-après.
            </p>

            <p>
                Il vous est possible, au moyen de la procédure décrite
                ci-après, de bloquer ces Cookies. Toutefois, cette catégorie de
                Cookies vous permettant d’accéder à l’ensemble des
                fonctionnalités du site, il est possible que votre blocage de
                ceux-ci provoque des dysfonctionnements de certaines parties du
                Site.
            </p>

            <p>
                Les Cookies nécessaires ont vocation à être conservés sur le
                Navigateur de l’Internaute pour une durée variable. Cette durée
                de vie dépendra de chaque Cookie et est détaillée dans le
                tableau ci-après&nbsp;:
            </p>

            <table>
                <tr>
                    <th>Nom du Cookie</th>
                    <th>Fournisseur</th>
                    <th>Fonctions</th>
                    <th>Durée de conservation</th>
                </tr>

                <tr>
                    <td><code>App</code></td>
                    <td>Flus</td>
                    <td>Utilisé afin de mémoriser la connexion de l’Internaute au Site.</td>
                    <td>Session</td>
                </tr>

                <tr>
                    <td><code>session_token</code></td>
                    <td>Flus</td>
                    <td>Utilisé afin de mémoriser la connexion de l’Internaute au Site au delà de la session.</td>
                    <td>1 mois</td>
                </tr>

                <tr>
                    <td><code>__stripe_mid</code></td>
                    <td><a href="https://stripe.com/fr/legal/cookies-policy">Stripe</a></td>
                    <td>Utilisé à des fins de détection et de prévention de la fraude bancaire.</td>
                    <td>1 an</td>
                </tr>

                <tr>
                    <td><code>__stripe_sid</code></td>
                    <td><a href="https://stripe.com/fr/legal/cookies-policy">Stripe</a></td>
                    <td>Utilisé à des fins de détection et de prévention de la fraude bancaire.</td>
                    <td>30 minutes</td>
                </tr>
            </table>

            <p>
                Dans la mesure du possible, les Cookies placés par des tiers
                sont supprimés par nos soins une fois la finalité du traitement
                atteinte.
            </p>

            <p>
                Ces données sont conservées dans des conditions sécurisées,
                selon les moyens actuels de la technique, dans le respect des
                dispositions du Règlement général à la protection des données
                et de la législation nationale en vigueur.
            </p>

            <h2>Article 5&nbsp;: Informations complémentaires</h2>

            <p>
                Pour toute information complémentaire relative à notre
                utilisation des Cookies ou encore à la configuration des
                Cookies sur votre navigateur, nous vous invitons à nous
                contacter depuis le formulaire de contact&nbsp;:
                <a href="<?= url('contact') ?>">accéder au formulaire de contact.</a>
            </p>

            <p>
                Vous trouverez également tout un ensemble d’informations
                relatives au traitement fait par Flus de vos données
                personnelles en consultant notre politique de confidentialité&nbsp;:
                <a href="<?= url('privacy policy') ?>">accéder à la politique de confidentialité</a>.
            </p>

            <p>
                Il vous est possible de bloquer ou configurer la manière de
                conserver les Cookies. Vous pouvez vous référer à la procédure
                concernant votre Navigateur sur le site de la Cnil&nbsp;:
                <a href="https://www.cnil.fr/fr/cookies-et-autres-traceurs/comment-se-proteger/maitriser-votre-navigateur">
                    accéder à la procédure de blocage des Cookies.
                </a>
            </p>

            <hr />

            <p class="text--center">
                <a class="button button--primary" href="<?= url('legal') ?>">
                    Retourner aux informations légales
                </a>
            </p>
        </div>
    </div>
</article>
