<?php
    $this->layout('base.phtml', [
        'title' => 'Conditions générales · Flus',
        'canonical' => url_full('general terms'),
    ]);
?>

<nav class="layout__breadcrumb" aria-label="Fil d’Ariane">
    <ul class="list--nostyle">
        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('home') ?>" rel="home">
                Accueil
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('legal') ?>">
                Informations légales
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" aria-current="page" href="<?= url('general terms') ?>">
                Conditions générales
            </a>
        </li>
    </ul>
</nav>

<article>
    <header class="panel panel--primary panel--header">
        <div class="wrapper wrapper--larger wrapper--center text--center flow">
            <h1>Conditions générales</h1>

            <p>
                Mise à jour le
                <time datetime="2025-02-22T00:00:00">
                    22 février 2025
                </time>
            </p>
        </div>
    </header>

    <div class="panel">
        <div class="wrapper wrapper--text wrapper--center text-container">
            <h1>Article 1&nbsp;: Parties</h1>

            <p>
                Les présentes Conditions générales sont applicables entre
                Marien Fressinaud Mas de Feix, entrepreneur individuel exerçant
                sous le nom commercial «&nbsp;FLUS&nbsp;», immatriculé au RCS
                de Grenoble sous le numéro 878 196 278, dont le siège social
                est situé au 4 bis rue Germain, 38100 Grenoble, France,
                email&nbsp;: support@flus.fr,
                formulaire de contact&nbsp;:
                <a href="<? url('contact') ?>">
                    <?= url_full('contact') ?>
                </a>,
                ci-après dénommé «&nbsp;<strong>Flus</strong>&nbsp;» et toute
                personne, physique ou morale, de droit privé ou de droit
                public, contractant avec Flus pour bénéficier des Services,
                ci-après «&nbsp;<strong>l’Utilisateur</strong>&nbsp;»,
                dénommées ensemble «&nbsp;<strong>les Parties</strong>&nbsp;».
            </p>

            <h1>Article 2&nbsp;: Définitions</h1>

            <ul>
                <li>«&nbsp;<strong>Abonnement</strong>&nbsp;»&nbsp;: droit d’accès temporaire à l’Application.</li>
                <li>«&nbsp;<strong>Anomalie</strong>&nbsp;»&nbsp;: désigne tout dysfonctionnement de l’Application ne provenant pas d’une erreur de manipulation de l’Utilisateur.</li>
                <li>«&nbsp;<strong>Application</strong>&nbsp;»&nbsp;: logiciel édité par Flus accessible sur le Site ou sur des Appareils.</li>
                <li>«&nbsp;<strong>Appareils</strong>&nbsp;»&nbsp;: supports mobiles, tels que tablette et smartphone, sur lesquels l’Application peut être utilisée par l’Utilisateur.</li>
                <li>«&nbsp;<strong>Incident</strong>&nbsp;»&nbsp;: tout dysfonctionnement de l’Application provenant d’une erreur de manipulation de l’Utilisateur.</li>
                <li>«&nbsp;<strong>Utilisateur</strong>&nbsp;»&nbsp;: toute personne, physique ou morale, de droit privé ou de droit public, inscrite sur le Site pour bénéficier des Services.</li>
                <li>«&nbsp;<strong>Contenu de l’Application</strong>&nbsp;»&nbsp;: éléments de toute nature publiés sur l’Application, protégés ou non par un droit de propriété intellectuelle, tel que textes, images, designs, présentations, vidéos, schémas, structures, bases de données ou logiciels.</li>
                <li>«&nbsp;<strong>Service</strong>&nbsp;»&nbsp;: service proposé par Flus et consistant en la mise à disposition d’une Application de veille de l’actualité personnalisée permettant notamment à l’Utilisateur de suivre l’actualité de son choix et d’agréger, stocker et partager des flux de syndication ainsi que des liens hypertextes.</li>
                <li>«&nbsp;<strong>Site</strong>&nbsp;»&nbsp;: site internet accessible à l’<abbr>URL</abbr> flus.fr ainsi que les sous-sites, sites miroirs, portails et variations d’<abbr>URL</abbr> y afférents.</li>
                <li>«&nbsp;<strong>Flus</strong>&nbsp;»&nbsp;: Marien Fressinaud Mas de Feix pris en sa qualité d’éditeur de l’Application.</li>
            </ul>

            <h1>Article 3&nbsp;: Champ d’application</h1>

            <p>
                L’utilisation de l’Application suppose l’inscription, la
                création d’un espace personnel et l’acceptation par
                l’Utilisateur des présentes Conditions générales. Lors de
                l’inscription sur l’Application, l’acceptation des présentes
                Conditions générales sera manifestée par le fait de cocher la
                case correspondant à la phrase suivante&nbsp;: «&nbsp;<em>Je
                reconnais avoir lu et accepté les conditions générales de
                services et d’utilisation</em>&nbsp;». L’Utilisateur reconnaît
                du même fait en avoir pris pleinement connaissance et les accepter
                sans restriction.
            </p>

            <p>
                Le fait de cocher la case susvisée sera réputé avoir la même
                valeur qu’une signature manuscrite de la part de l’Utilisateur.
                L’Utilisateur reconnaît la valeur de preuve des systèmes
                d’enregistrement automatique de Flus et, sauf pour lui
                d’apporter preuve contraire, il renonce à les contester en cas
                de litige.
            </p>

            <p>
                Les présentes Conditions générales sont applicables aux
                relations entre les Parties à l’exclusion de toutes autres
                conditions, et notamment celles de l’Utilisateur.
            </p>

            <p>
                L’acceptation des présentes Conditions générales suppose de la
                part de l’Utilisateur qu’il jouisse de la capacité juridique
                nécessaire pour cela, ou à défaut qu’il en ait l’autorisation
                d’un tuteur ou d’un curateur s’il est incapable, de son
                représentant légal s’il est mineur, ou encore qu’il soit
                titulaire d’un mandat s’il agit pour le compte d’une personne
                morale.
            </p>

            <h1>Article 4&nbsp;: Objet</h1>

            <p>
                Les présentes Conditions générales ont pour objet de définir
                les conditions dans lesquelles Flus met à disposition de
                l’Utilisateur l’Application afin que ce dernier puisse
                bénéficier des Services. Flus propose des Services permettant à
                l’Utilisateur d’effectuer une veille personnalisée
                au moyen d’un espace personnel sur l’Application depuis lequel
                il peut collecter, organiser, commenter et partager des liens
                hypertextes.
            </p>

            <p>
                L’Utilisateur a la possibilité de souscrire un Abonnement lui
                permettant de profiter des Services pendant une durée
                déterminée. Les Services auxquels donne accès l’Abonnement sont
                définis sur le Site et/ou l’Application.
            </p>

            <h1>Article 5&nbsp;: Abonnement</h1>

            <h2>5.1. Souscription d’un Abonnement</h2>

            <p>
                Afin de bénéficier des Services et d’utiliser l’Application au
                terme de la période d’offre promotionnelle d’essai telle que
                définie à l’article 5.4, l’Utilisateur devra souscrire à un
                Abonnement auprès de Flus en utilisant le formulaire prévu à
                cet effet sur le Site et/ou l’Application.
            </p>

            <h2>5.2. Prix de l’Abonnement</h2>

            <p>
                Le prix de l’Abonnement est annuel et librement fixé par
                l’Utilisateur, tant au moment de la souscription initiale qu’au
                moment du renouvellement de l’Abonnement. Le cas échéant, ce
                prix doit être fixé par l’Utilisateur dans une fourchette de
                prix compris entre zéro (0) et cent-vingt (120) euros hors
                taxes.
            </p>

            <p>
                L’Utilisateur peut également opter pour l’un des prix ci-après,
                fixés unilatéralement par Flus&nbsp;:
            </p>

            <ul>
                <li>Abonnement «&nbsp;solidaire&nbsp;»&nbsp;: quinze (15) euros hors taxe par an&nbsp;;</li>
                <li>Abonnement «&nbsp;équilibre&nbsp;»&nbsp;: trente (30) euros hors taxe par an&nbsp;;</li>
                <li>Abonnement «&nbsp;soutien&nbsp;»&nbsp;: dont le prix, indiqué en euros hors taxe par an, est évolutif et calculé par Flus en fonction du nombre total d’Utilisateurs et des objectifs financiers présentés sur le Site. Le prix de l’Abonnement «&nbsp;soutien&nbsp;» sera indiqué par Flus sur le Site et l’Application et sera régulièrement mis-à-jour.</li>
            </ul>

            <p>
                L’ensemble des prix de l’Abonnement proposés à l’Utilisateur
                figure sur le Site. Les prix fixés unilatéralement par Flus
                peuvent être modifiés à tout moment pour toute souscription
                ultérieure. Les prix affichés ne sont valables qu’au jour de la
                souscription et ne portent pas effet pour l’avenir.
            </p>

            <h2>5.3. Validation du choix</h2>

            <p>
                Dans le cadre de la souscription d’un Abonnement, l’Utilisateur
                devra renseigner ses informations de facturation. L’Utilisateur
                aura alors la faculté de vérifier l’Abonnement choisi, ainsi
                que son prix éventuel et sa durée. Si sa commande lui convient,
                il pourra la valider en cliquant sur le bouton prévu à cet
                effet sur le Site et/ou l’Application.
            </p>

            <h2>5.4. Offre promotionnelle d’essai</h2>

            <p>
                À l’inscription de l’Utilisateur, Flus fait bénéficier ce
                dernier d’une offre promotionnelle d’essai des Services d’une
                durée de trente-et-un (31) jours. Cette offre promotionnelle
                d’essai est gratuite. Le délai est calculé en jours francs
                suivant la date de l’inscription de l’Utilisateur. Au terme de
                cette offre promotionnelle d’essai des Services, l’Utilisateur
                sera invité par Flus à souscrire à un Abonnement afin de
                pouvoir continuer à bénéficier des Services.
            </p>

            <h2>5.5. Paiement par l’Utilisateur</h2>

            <p>
                Une fois la commande validée, l’Utilisateur sera le cas échéant
                invité à effectuer le paiement correspondant en étant redirigé
                à cet effet sur l’interface de paiement sécurisée comportant la
                mention «&nbsp;<em>Commande avec obligation de paiement</em>&nbsp;»
                ou toute formule analogue. Le paiement correspondant ne sera
                prélevé à l’Utilisateur qu’une fois la période d’offre
                promotionnelle d’essai révolue.
            </p>

            <h2>5.6. Confirmation de la souscription par Flus</h2>

            <p>
                Une fois l’Abonnement souscrit et, le cas échéant, le paiement
                effectivement reçu par Flus, ce dernier s’engage à en accuser
                réception à l’Utilisateur par voie électronique, dans un délai
                maximal de vingt-quatre (24) heures. Dans le même délai, Flus
                s’engage à adresser à l’Utilisateur un courrier électronique
                récapitulatif de la commande et lui en confirmant le
                traitement, reprenant toutes les informations y afférant.
            </p>

            <h2>5.7. Durée de l’Abonnement</h2>

            <p>
                L’Abonnement est conclu pour une durée déterminée. Il prend
                effet pour une durée d’un (1) an à compter de la confirmation
                par Flus de la souscription de l’Abonnement effectuée par
                l’Utilisateur. À défaut de renouvellement par l’Utilisateur,
                l’Abonnement arrivé à terme n’est pas reconduit par Flus.
            </p>

            <h2>5.8. Résiliation anticipée de l’Abonnement</h2>

            <p>
                En cas de manquement de l’Utilisateur à une quelconque des
                stipulations des présentes Conditions générales, et notamment
                des articles 5, 6 et 8, Flus pourra résilier l’Abonnement de
                plein droit et sans intervention du juge. La résiliation de
                l’Abonnement au tort de l’Utilisateur est sans préjudices des
                éventuels dommages-intérêts auxquels Flus pourrait prétendre du
                fait du manquement de l’Utilisateur.
            </p>

            <h1>Article 6&nbsp;: Prix et Paiement</h1>

            <h2>6.1. Prix</h2>

            <p>
                Les prix applicables sont ceux affichés sur le Site et/ou
                l’Application au jour de la souscription de l’Abonnement. Ces
                prix peuvent être modifiés à tout moment par Flus. Les prix
                affichés ne sont valables qu’au jour de la souscription par
                l’Utilisateur et ne portent pas effet pour l’avenir.
            </p>

            <p>
                Les prix indiqués sur le Site et/ou l’Application sont entendus
                en euros, hors taxes.
            </p>

            <h2>6.2. Modalité de paiement</h2>

            <p>
                L’Utilisateur peut effectuer son règlement par carte bancaire
                ou virement bancaire. Les paiements par carte bancaire se font
                au moyen de transactions sécurisées fournies par Stripe.
            </p>

            <p>
                Dans le cadre des paiements par carte bancaire, Flus n’a accès
                à aucune donnée relative aux moyens de paiement de
                l’Utilisateur. Le paiement est effectué directement entre les
                mains de l’établissement bancaire.
            </p>

            <h2>6.3. Facturation</h2>

            <p>
                Flus adressera ou mettra à disposition de l’Utilisateur une
                facture par voie électronique après chaque paiement.
                L’Utilisateur accepte expressément de recevoir les factures par
                voie électronique.
            </p>

            <h2>6.4. Délais de paiement et Défaut de paiement</h2>

            <p>
                Les dates de paiement convenues ne peuvent être retardées sous
                quelque prétexte que ce soit, y compris en cas de litige.
            </p>

            <p>
                Toute somme non payée à l’échéance impliquera que l’Abonnement
                de l’Utilisateur n’est pas renouvelé. Il ne pourra ainsi plus
                prétendre bénéficier des Services proposés par Flus.
            </p>

            <h1>Article 7&nbsp;: Obligations de Flus</h1>

            <h2>7.1. Mise à disposition de l’Application</h2>

            <p>
                Flus s’engage à mettre à disposition de l’Utilisateur
                l’Application permettant d’utiliser les Services et
                fonctionnalités telles que définies par Flus au moment de la
                souscription de l’Abonnement.
            </p>

            <h2>7.2. Services</h2>

            <p>
                Flus propose aux Utilisateurs les Services suivants,
                accessibles depuis l’Application&nbsp;:
            </p>

            <ul>
                <li>accès à un portail fonctionnel de veille&nbsp;;</li>
                <li>accès à un espace personnel permettant de collecter, organiser, commenter et partager des liens hypertextes&nbsp;;</li>
                <li>suivre des flux de syndication&nbsp;;</li>
                <li>gérer le renouvellement et/ou l’arrêt de son Abonnement aux Services.</li>
            </ul>

            <p>
                Les modalités de chaque Service sont précisées sur
                l’Application. Cette liste de Services pourra être réduite,
                modifiée ou complétée par Flus, unilatéralement et sans
                préavis.
            </p>

            <h2>7.3. Accès à l’Application</h2>

            <p>
                L’accès à l’Application s’effectue soit à partir du Site, soit
                à partir des Appareils de l’Utilisateur. Flus s’engage à ce que
                l’Utilisateur puisse se connecter à l’Application à tout
                moment, à l’exclusion des périodes de maintenance ou en cas
                d’Anomalie.
            </p>

            <h2>7.4. Hébergement et sécurité</h2>

            <p>
                Flus s’engage à assurer à sa charge, au profit de
                l’Utilisateur, au terme d’une obligation de moyens, une
                prestation d’hébergement de l’Application.
            </p>

            <p>
                L’hébergement comprend&nbsp;:
            </p>

            <ul>
                <li>la surveillance du/des serveur(s)&nbsp;;</li>
                <li>la surveillance du bon fonctionnement de l’infrastructure nécessaire à l’hébergement.</li>
            </ul>

            <h2>7.5. Performance de l’Application</h2>

            <p>
                L’Utilisateur est averti des aléas techniques inhérents à
                l’utilisation d’une Application et des interruptions d’accès
                qui peuvent en résulter.
            </p>

            <p>
                Flus s’engage à mettre en place des contrôles efficaces de
                nature à procurer une garantie raisonnable pour que
                l’Utilisateur puisse accéder et utiliser l’Application aux
                heures déterminées aux présentes et pour tester
                systématiquement la configuration de l’Application afin
                qu’elle reflète bien les fonctionnalités nécessaires à
                l’Utilisateur et des temps de réponse appropriés.
            </p>

            <p>
                Cependant, et compte tenu des spécificités du réseau Internet,
                Flus ne garantit ni l’accès sans interruption, ni la vitesse
                d’accès. Le cas échéant, Flus s’engage à enclencher les
                procédures internes nécessaires à la résolution de l’Anomalie
                dès qu’il a pris connaissance de celle-ci.
            </p>

            <p>
                En outre, Flus ne saurait être tenu pour responsable de
                l’altération, la perte, la destruction ou encore le vol de
                données, dès lors que ces incidents trouvent leur origine dans
                la configuration technique et/ou organisationnelle mise en
                place par l’Utilisateur. À ce titre, Flus s’exonère de toute
                responsabilité liée au système d’information et/ou aux
                Appareils de l’Utilisateur.
            </p>

            <h2>7.6. Maintenance</h2>

            <p>
                Flus s’engage à détecter si le dysfonctionnement de
                l’Application provient d’une Anomalie ou d’un Incident et à
                remédier à toute Anomalie, afin de permettre à l’Utilisateur un
                usage normal de l’Application.
            </p>

            <p>
                Sont exclues des prestations couvertes par la présente
                clause&nbsp;:
            </p>

            <ul>
                <li>les prestations qui se révéleraient ne pas être liées directement à l’Application&nbsp;;</li>
                <li>les prestations de formation ou d’assistance à l’utilisation de l’Application&nbsp;;</li>
                <li>les questions relatives à la personnalisation de l’Application, à l’environnement matériel&nbsp;;</li>
                <li>les sauvegardes/restaurations des données&nbsp;;</li>
                <li>le fonctionnement et les performances du réseau et des périphériques&nbsp;;</li>
                <li>les produits et prestations complémentaires.</li>
            </ul>

            <p>
                À compter du signalement d’une Anomalie ou d’un Incident par
                l’Utilisateur, Flus s’engage à prendre en compte et à réaliser
                la correction ou, à tout le moins, mettre en place une solution
                de contournement dans un délai raisonnable et au plus tard dans
                les quinze (15) jours ouvrés.
            </p>

            <h2>7.7. Nouvelles versions</h2>

            <p>
                Flus peut, régulièrement, à sa convenance et à son entière
                discrétion, mettre à jour le contenu, les fonctionnalités et
                l’interface utilisateur de ses Services au moyen de corrections
                d’erreurs, d’améliorations et d’autres modifications à sa
                charge.
            </p>

            <p>
                De la même manière, Flus mettra à jour l’Application pour
                satisfaire à toute prescription légale ou règlementaire qui
                rendrait une mise à jour de l’Application nécessaire pour sa
                bonne exploitation.
            </p>

            <p>
                L’Utilisateur bénéficiera de la fourniture gratuite des
                versions évolutives de l’Application dans le cadre de
                l’Abonnement auquel il aura souscrit.
            </p>

            <h2>7.8. Accès aux données en cas de rupture du contrat</h2>

            <p>
                En cas de rupture du contrat, Flus s’engage à maintenir un
                accès à l’Utilisateur à l’ensemble de ses données pour une
                durée de trente (30) jours.
            </p>

            <p>
                Cette durée pourra être prolongée sur demande expresse de
                l’Utilisateur à Flus et sous réserve de l’acceptation de cette
                demande par Flus.
            </p>

            <p>
                Passé cette durée de conservation, l’accès par l’Utilisateur à
                ses données archivées ne sera plus possible et ces données
                seront supprimées. Flus s’engage à procéder à leur suppression
                définitive.
            </p>

            <h1>Article 8&nbsp;: Déclarations et obligations de l’Utilisateur</h1>

            <h2>8.1 Déclarations de l’Utilisateur</h2>

            <p>
                L’Utilisateur assure avoir pris connaissance, préalablement à
                la signature des présentes Conditions générales, des
                caractéristiques techniques de l’Application et des Services
                proposées par Flus.
            </p>

            <p>
                En conséquence, l’Utilisateur reconnaît que ses besoins et les
                Services proposés par Flus sont en adéquation, qu’il a
                connaissance du contenu et des conditions d’exécution desdits
                Services et qu’il a souscrit aux Services prestés par Flus en
                connaissance de cause et en disposant de toutes les
                informations nécessaires lui permettant de produire un
                consentement libre et éclairé.
            </p>

            <h2>8.2 Autorisations</h2>

            <p>
                L’Utilisateur est seul responsable des autorisations et
                déclarations relatives à la souscription et à l’utilisation de
                l’Application. L’Utilisateur déclare qu’il dispose des droits
                et autorisations nécessaires à cette fin. Le cas échéant,
                l’Utilisateur déclare avoir effectué au préalable toute
                démarche nécessaire, telles que demandes d’autorisations et
                déclarations administratives.
            </p>

            <p>
                Le défaut de telles déclarations et autorisations ne pourra en
                aucun cas remettre en cause la validité des présentes.
                L’Utilisateur restera notamment tenu de régler à Flus les
                prestations commandées.
            </p>

            <p>
                L’Utilisateur garantit Flus contre tout recours qui serait
                entrepris à son encontre en cas de défaut de telles
                déclarations et/ou autorisations. Il s’engage à ce titre à
                rembourser intégralement à Flus tous les frais supportés en
                raison du défaut de déclarations et/ou d’autorisations.
            </p>

            <h2>8.3 Charte d’utilisation de l’Application</h2>

            <p>
                L’Utilisateur s’engage à utiliser l’Application conformément à
                la finalité des présentes Conditions générales et à respecter
                les instructions qui lui seraient données par Flus quant à
                l’installation, l’utilisation et l’entretien de l’Application.
                Notamment, l’Utilisateur s’engage à ne réaliser aucune action
                susceptible de&nbsp;:
            </p>

            <ul>
                <li>porter atteinte ou avoir de propos contraires à l’ordre public, aux bonnes mœurs ou pouvant heurter la sensibilité des mineurs&nbsp;;</li>
                <li>porter atteinte de quelque manière que ce soit aux droits à la réputation, à la vie privée, au droit ou à l’image d’un tiers&nbsp;;</li>
                <li>être dénigrant, diffamatoire, porter atteinte à l’image, à la réputation d’une marque ou d’une quelconque personne physique ou morale, de quelque manière que ce soit&nbsp;;</li>
                <li>avoir des propos à caractère pornographique ou pédophile&nbsp;;</li>
                <li>porter atteinte à la sécurité ou à l’intégrité d’un État ou d’un territoire, quel qu’il soit&nbsp;;</li>
                <li>porter atteinte aux droits de propriété intellectuelle de quelque personne que ce soit&nbsp;;</li>
                <li>inciter à la haine, à la violence, au suicide, au racisme, à l’antisémitisme, à la xénophobie, à l’homophobie, faire l’apologie des crimes de guerre ou des crimes contre l’humanité&nbsp;;</li>
                <li>inciter à commettre un crime, un délit ou un acte de terrorisme&nbsp;;</li>
                <li>inciter à la discrimination d’une personne ou d’un groupe de personnes en raison de son appartenance à une ethnie, à une religion, à une race, ou du fait de son orientation sexuelle ou de son handicap&nbsp;;</li>
                <li>conseiller une pratique douteuse ou frauduleuse.</li>
            </ul>

            <p>
                Tout traitement, transmission, publication, diffusion ou
                représentation des Services par l’Utilisateur est effectué sous
                sa seule et entière responsabilité. L’Utilisateur s’engage, en
                particulier, à ne traiter, diffuser, télécharger ou transmettre
                par l’intermédiaire de l’Application que des données dont
                l’exploitation ne viole aucun droit de propriété intellectuelle
                ou industrielle ni tout autre droit privatif, ou ne constitue
                pas la commission d’une infraction pénale.
            </p>

            <p>
                L’Utilisateur s’engage également à ne pas entraver ou perturber
                l’Application et les serveurs de Flus et à se conformer aux
                conditions requises, aux procédures, aux règles générales qui
                lui sont communiquées par Flus pour l’utilisation de
                l’Application.
            </p>

            <p>
                Tout comportement contraire de l’Utilisateur, tout usage
                illégal ou de manière générale non autorisé de l’Application
                entraînera la suppression immédiate du compte de l’Utilisateur,
                nonobstant pour Flus toute possibilité d’action en justice et
                demande de dommages et intérêts.
            </p>

            <p>
                L’Utilisateur garantit en conséquence Flus contre tout dommage
                susceptible de lui être causé du fait de son utilisation de
                l’Application, en ce compris les éventuels frais d’avocat et de
                procédure, et s’engage à ce titre à intervenir à toute instance
                judiciaire engagée à son encontre du fait de son utilisation de
                l’Application.
            </p>

            <h1>Article 9&nbsp;: Réclamations et Rétractations</h1>

            <h2>9.1 Service clientèle</h2>

            <p>
                Le service clientèle de Flus est accessible au moyen du
                formulaire de contact accessible à l’adresse suivante&nbsp;:
                <a href="https://flus.fr/contact">flus.fr/contact</a>
                ou par le biais du formulaire de contact intégré à
                l’Application. Flus s’engage à apporter une réponse sous cinq
                (5) jours ouvrés.
            </p>

            <h2>9.2 Renonciation au droit de rétractation</h2>

            <p>
                Conformément à la législation en vigueur en matière de vente à
                distance, et notamment l’article L.221-28 du code de la
                consommation, le droit de rétractation ne s’applique pas aux
                contrats de fourniture d’un contenu numérique non fourni sur un
                support matériel dont l’exécution a commencé après accord
                préalable exprès de l’Utilisateur et renoncement exprès à son
                droit de rétractation.
            </p>

            <p>
                Par conséquent, pour bénéficier des Services objets des
                présentes Conditions générales, lors de la souscription de
                l’Abonnement, l’Utilisateur renoncera à son droit de
                rétractation en cochant la case correspondant à la phrase
                suivante «&nbsp;<em>Je renonce expressément à mon droit de
                rétractation de 14 jours pour les prestations dont je
                bénéficierais avant l’écoulement de ce délai</em>&nbsp;».
                L’Utilisateur recevra alors une confirmation par e-mail de son
                renoncement au droit de rétractation.
            </p>

            <h1>Article 10&nbsp;: Espace personnel</h1>

            <h2>10.1 Création de l’espace personnel</h2>

            <p>
                La création d’un espace personnel constitue un préalable
                indispensable pour utiliser l’Application, objet des présentes
                Conditions générales. À cette fin, l’Utilisateur sera invité à
                fournir un certain nombre d’informations personnelles.
                Certaines de ces informations sont réputées indispensables à la
                création de l’espace personnel. Le refus, par un Utilisateur,
                de fournir lesdites informations aura pour effet d’empêcher la
                création de l’espace personnel ainsi que, incidemment, la
                souscription d’un Abonnement et l’utilisation de l’Application.
            </p>

            <p>
                Lors de la création de l’espace personnel, l’Utilisateur est
                invité à choisir un mot de passe. Ce mot de passe constitue la
                garantie de la confidentialité des informations contenues dans
                l’espace personnel. L’Utilisateur s’interdit donc de le
                transmettre ou de le communiquer à un tiers. À défaut, Flus ne
                pourra être tenu pour responsable des accès non autorisés à
                l’espace personnel d’un Utilisateur.
            </p>

            <p>
                L’Utilisateur s’engage en outre à procéder à une vérification
                régulière des données qui le concernent et à procéder en ligne,
                depuis son espace personnel, aux actualisations et
                modifications nécessaires.
            </p>

            <h2>10.2 Contenu de l’espace personnel</h2>

            <p>
                L’espace personnel permet à l’Utilisateur d’accéder aux
                Services et, notamment, de collecter, organiser, commenter et
                partager des liens hypertextes. L’Utilisateur peut consulter et
                renouveler son Abonnement depuis son espace personnel.
            </p>

            <p>
                Les pages relatives aux espaces personnels sont librement
                imprimables par le titulaire du compte en question mais ne
                constituent nullement une preuve admissible par un tribunal.
                Elles n’ont qu’un caractère informatif destiné à assurer une
                gestion efficace de son Abonnement par l’Utilisateur.
            </p>

            <p>
                Flus s’engage à conserver de façon sécurisée tous les éléments
                contractuels dont la conservation est requise par la loi ou la
                réglementation en vigueur.
            </p>

            <h2>10.3 Suppression de l’espace personnel</h2>

            <p>
                Flus se réserve le droit de supprimer le compte de tout
                Utilisateur qui contreviendrait aux présentes Conditions
                générales, notamment lorsque l’Utilisateur fournit des
                informations inexactes, incomplètes, mensongères ou
                frauduleuses, ainsi que lorsque l’espace personnel d’un
                Utilisateur sera resté inactif depuis au moins une (1) année.
                Ladite suppression ne sera pas susceptible de constituer une
                faute de Flus ou un quelconque dommage pour l’Utilisateur ainsi
                exclu, lequel ne pourra prétendre à aucune indemnité de ce
                fait.
            </p>

            <p>
                Cette exclusion est sans préjudice de la possibilité, pour
                Flus, d’entreprendre des poursuites d’ordre judiciaire à
                l’encontre de l’Utilisateur, lorsque les faits l’auront
                justifié.
            </p>

            <h1>Article 11&nbsp;: Données personnelles</h1>

            <p>
                Dans le cadre de sa prestation, Flus va être amené à traiter
                des données à caractère personnel de ses Utilisateurs.
            </p>

            <h2>11.1 Identité du responsable du traitement</h2>

            <p>
                Le responsable de la collecte et des données traitées sur
                l’Application est Flus.
            </p>

            <h2>11.2 Données collectées</h2>

            <h3>11.2.1 Données collectées auprès des Utilisateurs</h3>

            <p>
                Dans le cadre de ses relations contractuelles, Flus peut être
                amené à collecter et traiter des informations de ses
                Utilisateurs, à savoir&nbsp;: les noms, prénoms, adresses
                postales, adresses mails.
            </p>

            <h3>11.2.2 Finalités de la collecte de données personnelles</h3>

            <p>
                Les données collectées lors de la relation contractuelle font
                l’objet d’un traitement automatisé ayant pour finalité de&nbsp;:
            </p>

            <ul>
                <li>exécuter les engagements contractuels&nbsp;;</li>
                <li>contacter et inscrire les Utilisateurs&nbsp;;</li>
                <li>éviter toute activité illicite ou illégale&nbsp;;</li>
                <li>faire respecter les conditions générales&nbsp;;</li>
                <li>engager des procédures judiciaires&nbsp;;</li>
                <li>vérifier l’identité des Utilisateurs.</li>
            </ul>

            <h3>11.2.3 Bases juridiques du traitement</h3>

            <p>
                Les données collectées ont pour base juridique une relation
                contractuelle.
            </p>

            <h3>11.2.4 Destinataires des données</h3>

            <p>
                Les données collectées sont consultables uniquement par Flus
                dans les limites strictement nécessaires à l’exécution des
                engagements contractuels.
            </p>

            <p>
                Ces données, que ce soit sous forme individuelle ou agrégée, ne
                sont jamais rendues librement visualisables par une personne
                physique tierce.
            </p>

            <h3>11.2.5 Durée de conservation des données personnelles</h3>

            <p>
                Les données personnelles collectées sont conservées pendant le
                temps de la relation contractuelle, et pendant le temps durant
                lequel la responsabilité de Flus peut être engagée.
            </p>

            <p>
                Passé le délai de conservation, Flus s’engage à supprimer
                définitivement les données des personnes concernées sans en
                conserver une copie.
            </p>

            <h3>11.2.6 Sécurité et confidentialité des données personnelles</h3>

            <p>
                Les données personnelles sont conservées dans des conditions
                sécurisées, selon les moyens actuels de la technique, dans le
                respect des dispositions du Règlement général sur la protection
                des données et de la législation nationale en vigueur.
            </p>

            <p>
                L’accès aux locaux de Flus est également sécurisé.
            </p>

            <h3>11.2.7 Minimisation des données</h3>

            <p>
                Flus peut également collecter et traiter toute donnée transmise
                volontairement par ses Utilisateurs.
            </p>

            <p>
                Flus oriente ses Utilisateurs afin qu’il fournisse des données
                à caractère personnel strictement nécessaires à l’exécution des
                engagements contractuels.
            </p>

            <p>
                Flus s’engage à ne conserver et traiter que les données
                strictement nécessaires à ses activités professionnelles, et
                supprimera toute donnée reçue non utile à ses activités dans
                les plus brefs délais.
            </p>

            <h2>11.3 Respect des droits</h2>

            <p>
                Les Utilisateurs de Flus disposent des droits suivants
                concernant leurs données personnelles, qu’ils peuvent exercer
                en utilisant
                <a href="https://flus.fr/contact">le formulaire de contact en ligne</a>,
                ou en écrivant à l’adresse email support@flus.fr.
            </p>

            <p>
                Pour les aider dans leurs démarches, ils pourront utiliser
                <a href="https://www.cnil.fr/fr/modeles/courrier">
                    les modèles de courriers élaborés par la Cnil.
                </a>
            </p>

            <h3>11.3.1 Droit d’information, d’accès et de communication des données</h3>

            <p>
                Les Utilisateurs de Flus ont la possibilité d’accéder aux
                données personnelles qui les concernent.
            </p>

            <p>
                En raison de l’obligation de sécurité et de confidentialité
                dans le traitement des données à caractère personnel qui
                incombe à Flus, les demandes seront uniquement traitées si les
                Utilisateurs rapportent la preuve de leur identité.
                Cette preuve peut être établie en effectuant la demande depuis
                le formulaire de contact de l’Application qui nécessite que
                l’Utilisateur soit connecté au préalable. Elle pourra également
                être établie si la demande provient directement depuis
                l’adresse email que l’Utilisateur utilise pour se connecter sur
                l’Application.
            </p>

            <h3>11.3.2 Droit de rectification, de suppression et droit à l’oubli des données</h3>

            <p>
                Les Utilisateurs de Flus ont la possibilité de demander la
                rectification, la mise à jour, le verrouillage ou encore
                l’effacement de leurs données personnelles qui peuvent s’avérer
                le cas échéant inexactes, erronées, incomplètes ou obsolètes.
            </p>

            <p>
                Les Utilisateurs de Flus peuvent également définir des
                directives générales et particulières relatives au sort des
                données à caractère personnel après leur décès. Le cas échéant,
                les héritiers d’une personne décédée peuvent exiger de prendre
                en considération le décès de leur proche et/ou de procéder aux
                mises à jour nécessaires.
            </p>

            <h3>11.3.3 Droit d’opposition au traitement de données</h3>

            <p>
                Les Utilisateurs de Flus ont la possibilité de s’opposer à un
                traitement de leurs données personnelles.
            </p>

            <h3>11.3.4 Droit à la portabilité des données</h3>

            <p>
                Les Utilisateurs de Flus ont le droit de recevoir les données
                personnelles qu’ils ont fournies à Flus dans un format
                transférable, ouvert et lisible.
            </p>

            <h3>11.3.5 Droit à la limitation du traitement</h3>

            <p>
                Les Utilisateurs de Flus ont le droit de demander que le
                traitement de leurs données personnelles par Flus soit limité.
                Ainsi, leurs données ne pourront qu’être conservées et non plus
                utilisées par Flus.
            </p>

            <h3>11.3.6 Délais de réponse</h3>

            <p>
                Flus s’engage à répondre à toute demande d’accès, de
                rectification ou d’opposition ou toute autre demande
                complémentaire d’informations dans un délai raisonnable qui ne
                saurait dépasser 1 mois à compter de la réception de la
                demande.
            </p>

            <h3>11.3.7 Plainte auprès de l’autorité compétente</h3>

            <p>
                Si les Utilisateurs de Flus considèrent que Flus ne respecte
                pas ses obligations au regard de leurs données à caractère
                personnel, ils peuvent adresser une plainte ou une demande
                auprès de l’autorité compétente. En France, l’autorité
                compétente est la Cnil à laquelle ils peuvent
                <a href="https://www.cnil.fr/fr/plaintes">adresser une demande ici.</a>
            </p>

            <h2>11.4 Transfert des données collectées</h2>

            <h3>11.4.1 Transfert à des partenaires</h3>

            <p>
                Flus a recours à des prestataires habilités pour faciliter la
                collecte et le traitement des données de ses Utilisateurs. Ces
                prestataires peuvent être situés en dehors de l’Union
                Européenne.
            </p>

            <p>
                Flus s’est préalablement assuré de la mise en œuvre par ses
                prestataires de garanties adéquates et du respect de conditions
                strictes en matière de confidentialité, d’usage et de
                protection des données.
            </p>

            <p>
                Flus fait appel aux sous-traitants suivants&nbsp;:
            </p>

            <table>
                <tr>
                    <th>Partenaire</th>
                    <th>Pays destinataire</th>
                    <th>Traitement réalisé</th>
                    <th>Garanties</th>
                </tr>

                <tr>
                    <td>Hetzner Online GmbH</td>
                    <td>Allemagne et Finlande</td>
                    <td>Hébergement du Site web</td>
                    <td><a href="https://www.hetzner.com/legal/privacy-policy/">www.hetzner.com/legal/privacy-policy/</a></td>
                </tr>

                <tr>
                    <td>Scaleway</td>
                    <td>France</td>
                    <td>Envoi des emails transactionnels</td>
                    <td><a href="https://www.scaleway.com/en/contracts/">www.scaleway.com/en/contracts</a></td>
                </tr>

                <tr>
                    <td>Plausible</td>
                    <td>Allemagne et Union Européenne</td>
                    <td>Service d’analyse des sites internet</td>
                    <td><a href="https://plausible.io/data-policy">plausible.io/data-policy</a></td>
                </tr>

                <tr>
                    <td>Stripe</td>
                    <td>États-Unis</td>
                    <td>Prestataire de paiement en ligne</td>
                    <td><a href="https://stripe.com/fr/privacy">stripe.com/fr/privacy</a></td>
                </tr>

                <tr>
                    <td>rsync.net</td>
                    <td>Suisse</td>
                    <td>Hébergement des sauvegardes chiffrées</td>
                    <td><a href="https://www.rsync.net/resources/regulatory/privacy.html">www.rsync.net/resources/regulatory/privacy.html</a></td>
                </tr>
            </table>

            <h3>11.4.2 Transfert sur réquisition ou décision judiciaire</h3>

            <p>
                Les Utilisateurs consentent également à ce que Flus communique
                les données collectées à toute personne, sur réquisition d’une
                autorité étatique ou sur décision judiciaire.
            </p>

            <h3>11.4.3 Transfert dans le cadre d’une fusion ou d’une acquisition</h3>

            <p>
                Si Flus est impliquée dans une fusion, une vente d’actifs, une
                opération de financement, une liquidation ou banqueroute ou
                dans une acquisition de tout ou partie de son activité par une
                autre société, le consentement des Utilisateurs sera
                explicitement demandé par voie électronique pour que les
                données collectées soient transmises par Flus à cette société
                et que cette société opère les traitements de données
                personnelles visés dans les présentes Conditions générales de
                service au lieu et place de Flus.
            </p>

            <h1>Article 12&nbsp;: Responsabilité de Flus</h1>

            <h2>12.1 Nature des obligations de Flus</h2>

            <p>
                Flus s’engage à apporter le soin et la diligence nécessaire à
                la fourniture de Services de qualité conforme aux
                spécifications des présentes Conditions générales. Flus ne
                répond que d’une obligation de moyens concernant les Services
                objets des présentes.
            </p>

            <p>
                Flus peut interrompre momentanément les Services pour en
                assurer la maintenance, sans que l’Utilisateur puisse prétendre
                de ce fait à une quelconque indemnité.
            </p>

            <h2>12.2 Force majeure – Faute de l’Utilisateur</h2>

            <p>
                Flus n’engagera pas sa responsabilité en cas de force majeure
                ou de faute de l’Utilisateur, telles que définies au présent
                article&nbsp;:
            </p>

            <h3>12.2.1 Force majeure</h3>

            <p>
                Au sens des présentes Conditions générales, sera considéré
                comme un cas de force majeure opposable à l’Utilisateur tout
                empêchement, limitation ou dérangement des Services du fait
                d’incendie, d’épidémie, d’explosion, de tremblement de terre,
                de fluctuations de la bande passante, de manquement imputable
                au fournisseur d’accès, de défaillance des réseaux de
                transmission, d’effondrement des installations, d’utilisation
                illicite ou frauduleuse des mots de passe, codes ou références
                fournis à l’Utilisateur, de piratage informatique, d’une faille
                de sécurité imputable à l’hébergeur du Site ou aux
                développeurs, d’inondation, de panne d’électricité, de guerre,
                d’embargo, de loi, d’injonction, de demande ou d’exigence de
                tout gouvernement, de réquisition, de grève, de boycott, ou
                autres circonstances hors du contrôle raisonnable de Flus. Dans
                de telles circonstances, Flus sera dispensé de l’exécution de
                ses obligations dans la limite de cet empêchement, de cette
                limitation ou de ce dérangement.
            </p>

            <h3>12.2.2 Faute de l’Utilisateur</h3>

            <p>
                Au sens des présentes Conditions générales, sera considérée
                comme une faute de l’Utilisateur opposable à ce dernier toute
                mauvaise utilisation des Services, faute, négligence, omission
                ou défaillance de sa part ou de celle de ses préposés,
                non-respect des conseils donnés par Flus, toute divulgation ou
                utilisation illicite du mot de passe, des codes et références
                de l’Utilisateur, ainsi que le renseignement d’informations
                erronées ou l’absence de mise à jour de telles informations
                dans son espace personnel. Sera également considérée comme une
                faute de l’Utilisateur la mise en œuvre de tout procédé
                technique, tels que des robots ou des requêtes automatiques,
                dont la mise en œuvre contreviendrait à la lettre ou à l’esprit
                des présentes Conditions générales.
            </p>

            <h2>12.3 Problèmes techniques – Liens hypertextes</h2>

            <p>
                En cas d’impossibilité d’accès à l’Application, en raison de
                problèmes techniques de toutes natures, l’Utilisateur ne pourra
                se prévaloir d’un dommage et ne pourra prétendre à aucune
                indemnité. L’indisponibilité, même prolongée et sans aucune
                durée limitative, d’un ou plusieurs services en ligne, ne peut
                être constitutive d’un préjudice pour l’Utilisateur et ne peut
                aucunement donner lieu à l’octroi de dommages et intérêts de la
                part de Flus.
            </p>

            <p>
                Les liens hypertextes présents sur l’Application peuvent
                renvoyer sur d’autres sites internet. La responsabilité de Flus
                ne saurait être engagée si le contenu de ces sites contrevient
                aux législations en vigueur. De même la responsabilité de Flus
                ne saurait être engagée si la visite, par l’Utilisateur, de
                l’un de ces sites, lui causait un préjudice.
            </p>

            <h2>12.4 Dommages-intérêts à la charge de Flus</h2>

            <p>
                A défaut de dispositions légales ou réglementaires contraires,
                la responsabilité de Flus est limitée au préjudice direct,
                personnel et certain subi par l’Utilisateur et lié à la
                défaillance en cause. Flus ne pourra en aucun cas être tenu
                responsable des dommages indirects tels que, notamment les
                pertes de données, les préjudices commerciaux, les pertes de
                commandes, les atteintes à l’image de marque, les troubles
                commerciaux et les pertes de bénéfices ou de clients. De même
                et dans les mêmes limites, le montant des dommages et intérêts
                mis à la charge de Flus ne pourra en tout état de cause excéder
                le prix de l’Abonnement auquel l’Utilisateur aura souscrit.
            </p>

            <h2>12.5 Liens hypertextes et contenus de l’Application</h2>

            <p>
                Les Contenus de l’Application sont publiés à titre indicatif,
                sans garantie d’exactitude. Flus ne peut en aucun cas être tenu
                responsable du fait d’une omission, d’une inexactitude ou de
                toute erreur contenue dans ces informations et qui serait à
                l’origine d’un dommage direct ou indirect causé à
                l’Utilisateur.
            </p>

            <h2>12.6 Responsabilité en qualité d’hébergeur</h2>

            <p>
                Les données, notamment les flux et les liens hypertextes,
                collectés, stockés, commentés et/ou partagés sur l’Application
                par l’Utilisateur le sont sous sa propre responsabilité.
            </p>

            <p>
                Dans ce cadre, Flus bénéficiera du statut d’hébergeur des
                données au sens de l’article 6-I-2 de la Loi pour la confiance
                dans l’économie numérique du 21 juin 2004. Conformément au
                Règlement (UE) 2022/2065, Flus ne pourra voir sa responsabilité
                civile ou pénale engagée à raison de ces données, à moins que,
                dès le moment où il a eu connaissance de l’activité ou de
                l’information illicite, il n’ait agi promptement pour retirer
                ces informations ou en rendre l’accès impossible.
            </p>

            <h1>Article 13&nbsp;: Propriété intellectuelle</h1>

            <h2>13.1 Protection des Contenus du Site</h2>

            <h3>13.1.1 Protection légale des Contenus du Site</h3>

            <p>
                Les Contenus du Site sont susceptibles d’être protégés par le
                droit d’auteur et le droit des bases de données. Toute
                représentation, reproduction, traduction, adaptation ou
                transformation, intégrale ou partielle, réalisée illégalement
                et sans le consentement de Flus ou de ses ayants droit ou
                ayants cause constitue une violation des Livres I et III du
                Code de la propriété intellectuelle et sera susceptible de
                donner lieu à des poursuites judiciaires pour contrefaçon.
            </p>

            <h3>13.1.2 Protection contractuelle des Contenus du Site</h3>

            <p>
                L’Utilisateur s’engage contractuellement à l’égard de Flus à ne
                pas utiliser, reproduire ou représenter, de quelque manière que
                ce soit, les Contenus du Site, qu’ils soient ou non protégés
                par un droit de propriété intellectuelle, à une autre fin que
                celle de leur lecture par un robot ou un navigateur. Cette
                interdiction n’est pas applicable aux robots d’indexation ayant
                pour seul objet de scanner le contenu du Site aux fins
                d’indexation.
            </p>

            <h2>13.2 Protection des Contenus de l’Application</h2>

            <h3>13.2.1 Contenus publiés par l’Utilisateur</h3>

            <p>
                La publication de Contenus par l’Utilisateur suppose que ce
                dernier dispose des droits et/ou autorisations adéquates. Le
                cas échéant, la publication de Contenus par l’Utilisateur
                n’entraîne aucune cession des éventuels droits dont disposerait
                l’Utilisateur sur ces Contenus, notamment les droits de
                propriété intellectuelle, à Flus.
            </p>

            <h3>13.2.2 Protection légale des Contenus de l’Application</h3>

            <p>
                Les Contenus de l’Application sont susceptibles d’être protégés
                par le droit d’auteur et le droit des bases de données. Toute
                représentation, reproduction, traduction, adaptation ou
                transformation, intégrale ou partielle, réalisée illégalement
                et sans le consentement de Flus ou de ses ayants droit ou
                ayants cause constitue une violation des Livres I et III du
                Code de la propriété intellectuelle et sera susceptible de
                donner lieu à des poursuites judiciaires pour contrefaçon.
            </p>

            <h3>13.2.3 Protection contractuelle des Contenus de l’Application</h3>

            <p>
                L’Utilisateur s’engage contractuellement à l’égard de Flus à ne
                pas utiliser, reproduire ou représenter, de quelque manière que
                ce soit, les Contenus de l’Application, qu’ils soient ou non
                protégés par un droit de propriété intellectuelle, à une autre
                fin que celle de leur lecture par un robot ou un navigateur.
                Cette interdiction n’est pas applicable aux robots d’indexation
                ayant pour seul objet de scanner le contenu de l’Application
                aux fins d’indexation.
            </p>

            <h2>13.3 Licence de l’Application</h2>

            <p>
                L’Application est mise à disposition par Flus sous
                <a href="https://www.gnu.org/licenses/agpl-3.0.fr.html#license-text">
                    licence AGPLv3.
                </a>
                L’Utilisateur accepte la présente licence l’état. Flus ne donne
                pas d’autre garantie que celle de l’existence matérielle des
                droits objets de la présente licence.
            </p>

            <h1>Article 14&nbsp;: Stipulations finales</h1>

            <h2>14.1 Droit applicable</h2>

            <p>
                Les présentes Conditions générales sont soumises à
                l’application du droit français.
            </p>

            <h2>14.2 Modifications des présentes Conditions générales</h2>

            <p>
                Les présentes Conditions générales peuvent être modifiées à
                tout moment par Flus. Les Conditions générales applicables à
                l’Utilisateur sont celles en vigueur au jour de sa connexion
                sur l’Application. En cas de modification des présentes
                Conditions générales, Flus adressera aux Utilisateurs un email
                les informant de leur publication. Toute nouvelle connexion à
                l’espace personnel emportant acceptation, le cas échéant, des
                nouvelles Conditions générales.
            </p>

            <h2>14.3 Litiges</h2>

            <p>
                En vertu de l’ordonnance n°2015-1033 du 20 août 2015, tous
                litiges qui pourraient survenir dans le cadre de l’exécution
                des présentes Conditions générales et dont la solution n’aura
                pu être trouvée préalablement à l’amiable entre les parties
                devra être soumis au Centre de médiation de Grenoble&nbsp;:
                <a href="https://www.centredemediationdegrenoble.com/">
                    www.centredemediationdegrenoble.com
                </a>
            </p>

            <p>
                En outre, l’Utilisateur est informé de l’existence de la
                plateforme de règlement en ligne des litiges, accessibles à
                l’adresse URL suivante&nbsp;:
                <a href="https://ec.europa.eu/consumers/odr/main/?event=main.home2.show&lng=FR">
                    ec.europa.eu/consumers/odr/main/?event=main.home2.show&lng=FR
                </a>
            </p>

            <h2>14.4 Entièreté</h2>

            <p>
                La nullité d’une des clauses des présentes Conditions générales
                n’entraînera pas la nullité des autres clauses ou des
                Conditions générales dans leur globalité, qui garderont leur
                plein effet et portée. Dans une telle hypothèse, les Parties
                devront, dans la mesure du possible, remplacer la stipulation
                annulée par une stipulation valable correspondant à l’esprit et
                à l’objet des présentes.
            </p>

            <h2>14.5 Non-renonciation</h2>

            <p>
                L’absence d’exercice par Flus des droits qui lui sont reconnus
                par les présentes ne pourra en aucun cas être interprétée comme
                une renonciation à faire valoir lesdits droits.
            </p>

            <h2>14.6 Démarchage téléphonique</h2>

            <p>
                L’Utilisateur est informé qu’il a la possibilité de s’inscrire
                sur la liste d’opposition au démarchage téléphonique à
                l’adresse suivante&nbsp;:
                <a href="https://www.bloctel.gouv.fr/">
                    www.bloctel.gouv.fr
                </a>
            </p>

            <h2>14.7 Langues des présentes Conditions générales</h2>

            <p>
                Les présentes Conditions générales sont proposées en français.
            </p>

            <h2>14.8 Clauses abusives</h2>

            <p>
                Les stipulations des présentes Conditions générales
                s’appliquent sous réserve du respect des dispositions
                impératives du Code de la consommation concernant les clauses
                abusives dans les contrats conclus entre un professionnel et un
                consommateur.
            </p>

            <hr />

            <p class="text--center">
                <a class="button button--primary" href="<?= url('legal') ?>">
                    Retourner aux informations légales
                </a>
            </p>
        </div>
    </div>
</article>
