<?php
    $this->layout('base.phtml', [
        'title' => 'Politique de confidentialité · Flus',
        'canonical' => url_full('privacy policy'),
    ]);
?>

<nav class="layout__breadcrumb" aria-label="Fil d’Ariane">
    <ul class="list--nostyle">
        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('home') ?>" rel="home">
                Accueil
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('legal') ?>">
                Informations légales
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" aria-current="page" href="<?= url('privacy policy') ?>">
                Politique de confidentialité
            </a>
        </li>
    </ul>
</nav>

<article>
    <header class="panel panel--primary panel--header">
        <div class="wrapper wrapper--larger wrapper--center text--center flow">
            <h1>Politique de confidentialité</h1>

            <p>
                Mise à jour le
                <time datetime="2025-02-22T00:00:00">
                    22 février 2025
                </time>
            </p>
        </div>
    </header>

    <div class="panel">
        <div class="wrapper wrapper--text wrapper--center text-container">
            <h2>Préambule</h2>

            <p>
                La présente politique de confidentialité vous informe sur la
                manière dont Marien Fressinaud Mas de Feix utilise et protège
                les informations que vous nous transmettez, le cas échéant,
                lorsque vous utilisez le présent site accessible à partir de
                l’<abbr>URL</abbr> suivante&nbsp;: flus.fr (ci-après le
                «&nbsp;Site&nbsp;»).
            </p>

            <p>
                Veuillez noter que cette politique de confidentialité est
                susceptible d’être modifiée ou complétée à tout moment par
                Marien Fressinaud Mas de Feix, notamment en vue de se conformer
                à toute évolution légale ou technologique. Dans un tel cas, la
                date de sa mise à jour sera clairement identifiée en tête de la
                présente politique. Ces modifications engagent l’Internaute dès
                leur mise en ligne. Il convient par conséquent que l’Internaute
                consulte régulièrement la présente politique de confidentialité
                afin de prendre connaissance de ses éventuelles modifications.
            </p>

            <h2>Article 1&nbsp;: Parties</h2>

            <p>
                La présente politique de confidentialité est applicable entre
                l’éditeur du Site à savoir Marien Fressinaud Mas de Feix,
                ci-après «&nbsp;Flus&nbsp;», et toute personne se connectant au
                Site, ci-après «&nbsp;l’Internaute&nbsp;».
            </p>

            <h2>Article 2&nbsp;: Définitions</h2>

            <ul>
                <li>«&nbsp;<strong>Contenus du Site</strong>&nbsp;»&nbsp;: éléments de toute nature publiés sur le Site, protégés ou non par un droit de propriété intellectuelle, tel que textes, images, designs, présentations, vidéos, schémas, structures, bases de données ou logiciels.</li>
                <li>«&nbsp;<strong>Internaute</strong>&nbsp;»&nbsp;: toute personne se connectant au Site.</li>
                <li>«&nbsp;<strong>Site</strong>&nbsp;»&nbsp;: site internet accessible à l’<abbr>URL</abbr> flus.fr, ainsi que les sous-sites, sites miroirs, portails et variations d’<abbr>URL</abbr> y afférant.</li>
            </ul>

            <h2>Article 3&nbsp;: Champ d’application</h2>

            <p>
                La présente politique de confidentialité est applicable à tout
                Internaute. Votre simple navigation sur le Site emporte votre
                acceptation pleine et entière de celle-ci.
            </p>

            <p>
                L’Internaute reconnaît la valeur de preuve des systèmes
                d’enregistrement automatique de Flus et, sauf pour lui
                d’apporter preuve contraire, il renonce à les contester en cas
                de litige.
            </p>

            <p>
                L’acceptation de la présente politique de confidentialité
                suppose de la part des Internautes qu’ils jouissent de la
                capacité juridique nécessaire pour cela ou qu’ils aient au
                moins 16 ans, ou à défaut qu’ils en aient l’autorisation d’un
                tuteur ou d’un curateur s’ils sont incapables, de leur
                représentant légal s’ils ont moins de 16 ans, ou encore qu’ils
                soient titulaires d’un mandat s’ils agissent pour le compte
                d’une personne morale.
            </p>

            <h2>Article 4&nbsp;: Données personnelles</h2>

            <p>
                 Conformément au Règlement général sur la protection des
                 données (<abbr>RGPD</abbr>) adopté par le Parlement européen
                 le 14 avril 2016 et à la législation nationale en vigueur,
                 Flus vous fournit les informations suivantes&nbsp;:
            </p>

            <h3>4.1. Identité du responsable du traitement</h3>

            <p>
                Le responsable de la collecte et des données traitées est
                Marien Fressinaud Mas De Feix, entrepreneur individuel,
                immatriculé sous le <abbr>SIREN</abbr> 878196278, dont le
                siège social se situe au 4 bis rue Germain, 38100 Grenoble.
                Email&nbsp;: support@flus.fr
            </p>

            <h3>4.2. Collecte des données par Flus</h3>

            <h4>4.2.1. Données collectées</h4>

            <h5>4.2.1.1. Données collectées lors de la navigation</h5>

            <p>
                Lors de la navigation sur le Site, vous consentez à ce que Flus
                collecte les informations relatives&nbsp;:
            </p>

            <ul>
                <li>À l’utilisation qui est faite du site&nbsp;;</li>
                <li>À votre contenu consulté et sur lequel vous avez cliqué&nbsp;</li>
                <li>À votre appareil utilisé et à votre environnement logiciel&nbsp;;</li>
                <li>À votre localisation&nbsp;;</li>
                <li>À vos pages web visitées avant l’utilisation du Site (liens entrants vers le Site)&nbsp;;</li>
                <li>À vos données de connexion (horaires, pages consultées, adresse <abbr>IP</abbr>…).</li>
            </ul>

            <h5>4.2.1.2. Données collectées lors de l’utilisation du formulaire de contact</h5>

            <p>
                L’utilisation du formulaire de contact par l’Internaute suppose
                la collecte par Flus des données personnelles suivantes&nbsp;:
            </p>

            <ul>
                <li>Nom&nbsp;;</li>
                <li>Prénom&nbsp;;</li>
                <li>Adresse email.</li>
            </ul>

            <h5>4.2.1.3. Données collectées lors de l’utilisation du formulaire d’inscription</h5>

            <p>
                L’utilisation du formulaire d’inscription par l’Internaute
                suppose la collecte par Flus des données personnelles
                suivantes&nbsp;:
            </p>

            <ul>
                <li>Nom&nbsp;;</li>
                <li>Prénom&nbsp;;</li>
                <li>Pseudo&nbsp;;</li>
                <li>Adresse email.</li>
            </ul>

            <h5>4.2.1.4. Données collectées lors de l’utilisation de la personnalisation du profil</h5>

            <p>
                La personnalisation de son profil par l’Internaute suppose la
                collecte par Flus des données personnelles suivantes&nbsp;:
            </p>

            <ul>
                <li>Pseudo&nbsp;;</li>
                <li>Photo de profil.</li>
            </ul>

            <h4>4.2.2. Finalités de la collecte de données personnelles</h4>

            <p>
                Les données collectées lors de la navigation font l’objet d’un
                traitement automatisé ayant pour finalité de&nbsp;:
            </p>

            <ul>
                <li>Développer, exploiter, améliorer, fournir et gérer le Site.</li>
            </ul>

            <p>
                Les données collectées lors de l’utilisation du formulaire de
                contact font l’objet d’un traitement automatisé ayant pour
                finalité de&nbsp;:
            </p>

            <ul>
                <li>Vérifier l’identité de l’Internaute&nbsp;;</li>
                <li>Apporter une réponse circonstanciée à l’Internaute en le contactant par email.</li>
            </ul>

            <p>
                Les données collectées lors de l’utilisation du formulaire
                d’inscription font l’objet d’un traitement automatisé ayant
                pour finalité de&nbsp;:
            </p>

            <ul>
                <li>Vérifier l’identité de l’Internaute&nbsp;;</li>
                <li>Communiquer avec l’Internaute&nbsp;;</li>
                <li>Procéder à l’inscription de l’Internaute et réaliser la prestation de service&nbsp;;</li>
                <li>Assurer et améliorer la sécurité des services&nbsp;;</li>
                <li>Développer, exploiter, améliorer, fournir et gérer le site&nbsp;;</li>
                <li>Adresser des informations et contacter l’Internaute&nbsp;;</li>
                <li>Éviter toute activité illicite ou illégale&nbsp;;</li>
                <li>Contextualiser et améliorer l’expérience de l’Internaute&nbsp;;</li>
                <li>Faire respecter les conditions relatives à l’utilisation du Site.</li>
            </ul>

            <p>
                Les données collectées lors de la personnalisation du profil
                font l’objet d’un traitement automatisé ayant pour finalité
                de&nbsp;:
            </p>

            <ul>
                <li>Identifier l’auteur de contenu publié.</li>
            </ul>

            <h4>4.2.3. Bases juridiques du traitement</h4>

            <p>
                Les données collectées lors de la navigation ont pour base
                juridique l’intérêt légitime de Flus, à savoir réaliser une
                analyse des comportements sur le Site et obtenir une sécurité
                et un fonctionnement améliorés du Site. S’agissant des données
                issues de l’implantation de certains cookies, l’Internaute est
                invité à se référer à
                <a href="<?= url('cookies policy') ?>">
                    la politique cookies de Flus.
                </a>
            </p>

            <p>
                Les données collectées lors de l’utilisation du formulaire de
                contact ont pour base juridique le consentement des personnes
                concernées.
            </p>

            <p>
                Les données collectées lors de l’utilisation du formulaire
                d’inscription ont pour base juridique une relation
                contractuelle.
            </p>

            <p>
                Les données collectées lors de la personnalisation du profil
                ont pour base juridique une relation contractuelle.
            </p>

            <h4>4.2.4. Destinataires des données</h4>

            <p>
                Les données collectées, à l’exception du pseudo et de la photo
                de profil sont consultables uniquement par les membres de la
                direction de Flus et ne sont jamais rendues librement
                visualisables par une personne physique tierce.
            </p>

            <p>
                Le pseudo et la photo de profil étant collectées afin de
                différencier le Contenu publié par l’Internaute, ces
                informations sont librement visualisables par n’importe quel
                autre Internaute.
            </p>

            <h4>4.2.5. Durée de conservation des données personnelles</h4>

            <p>
                Les données personnelles collectées lors de la navigation sont
                conservées pendant une durée raisonnable nécessaire à la bonne
                administration du Site et pour un maximum de 12 mois, ou
                jusqu’au retrait du consentement des personnes concernées.
            </p>

            <p>
                Les données personnelles collectées lors de l’utilisation du
                formulaire contact sont conservées pendant une durée
                raisonnable nécessaire à la bonne gestion de la demande de
                l’Internaute, et pour un maximum de 12 mois.
            </p>

            <p>
                Les données personnelles collectées lors de l’utilisation du
                formulaire d’inscription sont conservées le temps de la durée
                de la relation contractuelle.
            </p>

            <p>
                Les données personnelles collectées lors de la personnalisation
                du profil sont conservées le temps de la durée de la relation
                contractuelle.
            </p>

            <p>
                À l’issue de chacun de ces délais, Flus archivera ces données
                et les conservera le temps durant lequel sa responsabilité
                pourra être mise en cause.
            </p>

            <p>
                Passé ce délai de conservation, Flus s’engage à supprimer
                définitivement les données des personnes concernées.
            </p>

            <h4>4.2.6. Sécurité et confidentialité des données personnelles</h4>

            <p>
                Les données personnelles sont conservées dans des conditions
                sécurisées, selon les moyens actuels de la technique, dans le
                respect des dispositions du Règlement général pour la
                protection des données et de la législation nationale en
                vigueur.
            </p>

            <h4>4.2.7. Minimisation des données personnelles</h4>

            <p>
                Flus peut également collecter et traiter toute donnée transmise
                volontairement par un Internaute, notamment lors de l’envoi
                d’un email à l’adresse de contact.
            </p>

            <p>
                Flus oriente les Internautes autant que possible lorsqu’ils
                fournissent des données à caractère personnel inutiles ou
                superflues.
            </p>

            <p>
                Flus s’engage à ne conserver et traiter que les données
                strictement nécessaires à ses activités, et supprimera toute
                donnée reçue non utile dans les plus brefs délais.
            </p>

            <h3>4.3. Respect des droits</h3>

            <p>
                Vous disposez des droits suivants concernant vos données
                personnelles, que vous pouvez exercer en utilisant
                <a href="<?= url('contact') ?>">le formulaire de contact du Site</a>,
                ou en nous adressant un email à l’adresse suivante&nbsp;: support@flus.fr.
            </p>

            <p>
                Pour vous aider dans vos démarches, vous trouverez ici
                <a href="https://www.cnil.fr/fr/modeles/courrier">
                    des modèles de courriers élaborés par la Cnil.
                </a>
            </p>

            <h4>4.3.1. Droit d’information, d’accès et de communication des données</h4>

            <p>
                Vous avez la possibilité d’accéder aux données personnelles qui
                vous concernent.
            </p>

            <h4>4.3.2. Droit de rectification, de suppression et droit à l’oubli des données</h4>

            <p>
                Vous avez la possibilité de demander la rectification, la mise
                à jour, le verrouillage ou encore l’effacement de vos données
                personnelles qui peuvent s’avérer le cas échéant inexactes,
                erronées, incomplètes ou obsolètes.
            </p>

            <p>
                Vous pouvez également définir des directives générales et
                particulières relatives au sort des données à caractère
                personnel après votre décès. Le cas échéant, les héritiers
                d’une personne décédée peuvent exiger de prendre en
                considération le décès de leur proche et/ou de procéder aux
                mises à jour nécessaires.
            </p>

            <h4>4.3.3. Droit d’opposition au traitement de données</h4>

            <p>
                Vous avez la possibilité de vous opposer à un traitement de vos
                données personnelles.
            </p>

            <p>
                Pour ce faire, il vous conviendra de nous contacter en
                précisant les données que vous souhaitez voir supprimer ainsi
                que les raisons justifiant cette demande, sauf cas de
                prospection commerciale.
            </p>

            <h4>4.3.4. Droit à la portabilité des données</h4>

            <p>
                Vous avez le droit de recevoir les données personnelles que
                vous nous avez fournies dans un format transférable, ouvert et
                lisible.
            </p>

            <h4>4.3.5. Droit à la limitation du traitement</h4>

            <p>
                Vous avez le droit de demander que le traitement de vos données
                personnelles par Flus soit limité. Ainsi, vos données ne
                pourront qu’être conservées et non plus utilisées par Flus.
            </p>

            <h4>4.3.6. Retrait du consentement</h4>

            <p>
                Votre consentement est indispensable au traitement de vos
                données par Flus. Toutefois, il vous est possible de retirer
                celui-ci à tout moment. Ce retrait conduira à la suppression
                des données personnelles vous concernant.
            </p>

            <p>
                Les services nécessitant le traitement de vos données par Flus
                ne seront néanmoins plus accessibles.
            </p>

            <h4>4.3.7. Délais de réponse</h4>

            <p>
                Flus s’engage à répondre à votre demande d’accès, de
                rectification ou d’opposition ou toute autre demande
                complémentaire d’informations dans un délai raisonnable qui ne
                saurait dépasser 1 mois à compter de la réception de votre
                demande.
            </p>

            <h4>4.3.8. Plainte auprès de l’autorité compétente</h4>

            <p>
                Si vous considérez que Flus ne respecte pas ses obligations au
                regard de vos informations personnelles, vous pouvez adresser
                une plainte ou une demande auprès de l’autorité compétente. En
                France, l’autorité compétente est la Cnil à laquelle vous
                pouvez <a href="https://www.cnil.fr/fr/plaintes">adresser une demande ici.</a>
            </p>

            <h3>4.4. Transfert des données collectées</h3>

            <h4>4.4.1. Transfert à des partenaires</h4>

            <p>
                Flus vous informe que nous avons recours à des prestataires
                habilités pour faciliter le recueil et le traitement des
                données que vous nous avez communiquées. Ces prestataires
                peuvent être situés en dehors de l’Union Européenne et ont
                communication des données recueillies sur le Site.
            </p>

            <p>
                Flus s’est préalablement assuré de la mise en œuvre par ses
                prestataires de garanties adéquates et du respect de conditions
                strictes en matière de confidentialité, d’usage et de
                protection des données.
            </p>

            <p>
                L’Internaute consent à ce que les données collectées soient
                transmises par Flus à ses partenaires et fassent l’objet d’un
                traitement par ces partenaires dans le cadre des services
                tiers, à savoir&nbsp;:
            </p>

            <table>
                <tr>
                    <th>Partenaire</th>
                    <th>Pays destinataire</th>
                    <th>Traitement réalisé</th>
                    <th>Garanties</th>
                </tr>

                <tr>
                    <td>Hetzner Online GmbH</td>
                    <td>Allemagne et Finlande</td>
                    <td>Hébergement du Site web</td>
                    <td><a href="https://www.hetzner.com/legal/privacy-policy/">www.hetzner.com/legal/privacy-policy/</a></td>
                </tr>

                <tr>
                    <td>Scaleway</td>
                    <td>France</td>
                    <td>Envoi des emails transactionnels</td>
                    <td><a href="https://www.scaleway.com/en/contracts/">www.scaleway.com/en/contracts</a></td>
                </tr>

                <tr>
                    <td>Plausible</td>
                    <td>Allemagne et Union Européenne</td>
                    <td>Service d’analyse des sites internet</td>
                    <td><a href="https://plausible.io/data-policy">plausible.io/data-policy</a></td>
                </tr>

                <tr>
                    <td>Stripe</td>
                    <td>États-Unis</td>
                    <td>Prestataire de paiement en ligne</td>
                    <td><a href="https://stripe.com/fr/privacy">stripe.com/fr/privacy</a></td>
                </tr>

                <tr>
                    <td>rsync.net</td>
                    <td>Suisse</td>
                    <td>Hébergement des sauvegardes chiffrées</td>
                    <td><a href="https://www.rsync.net/resources/regulatory/privacy.html">www.rsync.net/resources/regulatory/privacy.html</a></td>
                </tr>
            </table>

            <h4>4.4.2. Transfert sur réquisition ou décision judiciaire</h4>

            <p>
                L’Internaute consent également à ce que Flus communique les
                données collectées à toute personne, sur réquisition d’une
                autorité étatique ou sur décision judiciaire.
            </p>

            <h4>4.4.3. Transfert dans le cadre d’une fusion ou d’une acquisition</h4>

            <p>
                Si Flus est impliqué dans une fusion, une vente d’actifs, une
                opération de financement, une liquidation ou banqueroute ou
                dans une acquisition de tout ou partie de son activité par une
                autre société, le consentement des Utilisateurs sera
                explicitement demandé par voie électronique pour que les
                données collectées soient transmises par Flus à cette société
                et que cette société opère les traitements de données
                personnelles visés dans la présente politique confidentialité
                au lieu et place de Flus.
            </p>

            <h2>Article 5&nbsp;: Propriété intellectuelle</h2>

            <h3>5.1. Protection légale des Contenus du Site</h3>

            <p>
                Les Contenus du Site sont susceptibles d’être protégés par le
                droit d’auteur et le droit des bases de données. Toute
                représentation, reproduction, traduction, adaptation ou
                transformation, intégrale ou partielle, réalisée illégalement
                et sans le consentement de Flus ou de ses ayants droit ou
                ayants cause constitue une violation des Livres I et III du
                Code de la propriété intellectuelle et sera susceptible de
                donner lieu à des poursuites judiciaires pour contrefaçon.
            </p>

            <h3>5.1. Protection contractuelle des Contenus du Site</h3>

            <p>
                L’Internaute s’engage contractuellement à l’égard de Flus à ne
                pas utiliser, reproduire ou représenter, de quelque manière que
                ce soit, les Contenus du Site, qu’ils soient ou non protégés
                par un droit de propriété intellectuelle, à une autre fin que
                celle de leur lecture par un robot ou un navigateur. Cette
                interdiction n’est pas applicable aux robots d’indexation ayant
                pour seul objet de scanner le contenu du Site aux fins
                d’indexation.
            </p>

            <h2>Article 6&nbsp;: Stipulations finales</h2>

            <h3>6.1. Modifications</h3>

            <p>
                La présente Politique de Confidentialité peut être modifiée à
                tout moment par Flus. Les conditions applicables à l’Internaute
                sont celles en vigueur lors de sa connexion sur le Site, toute
                nouvelle connexion au Site emportant acceptation le cas échéant
                des nouvelles conditions.
            </p>

            <h3>6.2. Entièreté</h3>

            <p>
                La nullité d’une des clauses du présent contrat n’entraînera
                pas la nullité des autres clauses du contrat ou du contrat dans
                sa globalité, qui garderont leur plein effet et portée. Dans
                une telle hypothèse, les parties devront dans la mesure du
                possible remplacer la stipulation annulée par une stipulation
                valable correspondant à l’esprit et à l’objet des présentes.
            </p>

            <h3>6.3. Non-renonciation</h3>

            <p>
                L’absence d’exercice par Flus des droits qui lui sont reconnus
                par les présentes ne pourra en aucun cas être interprétée comme
                une renonciation à faire valoir lesdits droits.
            </p>

            <h3>6.4. Langues</h3>

            <p>
                Les présentes conditions sont proposées en français.
            </p>

            <h3>6.5. Clauses abusives</h3>

            <p>
                Les stipulations des présentes conditions s’appliquent sous
                réserve du respect des dispositions impératives du Code de la
                consommation concernant les clauses abusives dans les contrats
                conclus entre un professionnel et un consommateur.
            </p>

            <h2>Article 7&nbsp;: Litiges</h2>

            <h3>7.1. Droit applicable</h3>

            <p>
                La présente Politique de Confidentialité est soumise à
                l’application du droit français et de la règlementation
                européenne, notamment le Règlement européen sur la protection
                des données.
            </p>

            <h3>7.2. Litiges</h3>

            <p>
                En vertu de l’ordonnance n°2015-1033 du 20 août 2015, tous
                litiges qui pourraient survenir dans le cadre de l’exécution
                des présentes conditions générales et dont la solution n’aura
                pu être trouvée préalablement à l’amiable entre les parties
                devra être soumis à un médiateur agréé.
            </p>

            <h3>7.3. Arbitrage</h3>

            <p>
                Tout litige relatif au présent contrat ou en relation avec
                celui-ci sera tranché par voie d’arbitrage conformément au
                règlement <a href="https://fast-arbitre.com/fr/">FastArbitre</a>
                de l’Institut digital d’arbitrage et de médiation.
            </p>

            <hr />

            <p class="text--center">
                <a class="button button--primary" href="<?= url('legal') ?>">
                    Retourner aux informations légales
                </a>
            </p>
        </div>
    </div>
</article>
