<p>
    Bonjour,
</p>

<p>
    Vous recevez ce courriel car vous possédez un compte Flus qui a expiré le
    <?= _d($expired_at, 'dd MMMM yyyy') ?>.
    Si vous voulez continuer à utiliser le service, vous devez renouveler votre
    abonnement.
</p>

<p>
    Pour cela, il vous suffit de suivre le lien suivant (valide une fois
    pendant 24h)&nbsp;:
</p>

<p>
    <a href="<?= $login_url ?>"><?= $login_url ?></a>
</p>

<?php if ($service === 'freshrss'): ?>
    <p>
        Si le lien précédent ne fonctionne pas, vous pouvez vous
        <a href="https://flus.io/i/?c=billing">connecter à FreshRSS, menu «&nbsp;Abonnement Flus&nbsp;»</a>,
        puis « Renouveler depuis votre compte de paiement ».
    </p>
<?php else: ?>
    <p>
        Si le lien précédent ne fonctionne pas, vous pouvez vous
        <a href="https://app.flus.fr/my/account">connecter à Flus, menu «&nbsp;Compte &amp; données&nbsp;»</a>,
        puis « Gérer votre abonnement ».
    </p>
<?php endif; ?>

<p>
    Si vous avez décidé d’arrêter d’utiliser Flus mais souhaitez récupérer vos
    données (ou pour toute autre question), vous pouvez me contacter à
    l’adresse suivante&nbsp;: <a href="mailto:support@flus.io">support@flus.io</a>
</p>

<p>
    En vous remerciant de votre soutien,
</p>

<p>
    Marien
</p>
