<p>
    Bonjour,
</p>

<p>
    Vous recevez ce courriel car vous possédez un compte Flus qui arrive à
    échéance le <?= _d($expired_at, 'dd MMMM yyyy') ?>.
    Si vous voulez continuer à utiliser le service après cette date, vous
    devrez renouveler votre abonnement.
</p>

<p>
    Si vous le souhaitez, vous pouvez effectuer ce renouvellement dès
    maintenant&nbsp;: votre nouvel abonnement prendra effet dès la fin de la
    période actuelle. Pour cela, il vous suffit de suivre le lien suivant
    (valide une fois pendant 24h)&nbsp;:
</p>

<p>
    <a href="<?= $login_url ?>"><?= $login_url ?></a>
</p>

<?php if ($service === 'freshrss'): ?>
    <p>
        Si le lien précédent ne fonctionne pas, vous pouvez vous
        <a href="https://rss.flus.fr/i/?c=billing">connecter à FreshRSS, menu «&nbsp;Abonnement Flus&nbsp;»</a>,
        puis « Renouveler depuis votre compte de paiement ».
    </p>
<?php else: ?>
    <p>
        Si le lien précédent ne fonctionne pas, vous pouvez vous
        <a href="https://app.flus.fr/my/account">connecter à Flus, menu «&nbsp;Compte &amp; données&nbsp;»</a>,
        puis « Gérer votre abonnement ».
    </p>
<?php endif; ?>

<p>
    En vous remerciant de votre soutien,
</p>

<p>
    Marien
</p>
