<p>
    Bonjour,
</p>

<p>
    Vous recevez ce courriel car vous possédez un compte Flus qui a expiré le
    <?= format_date($expired_at, '%d %B %Y') ?>.
    Si vous voulez continuer à utiliser le service, vous devez renouveler votre
    abonnement.
</p>

<p>
    Pour cela, il vous suffit de suivre le lien suivant (valide une fois
    pendant 24h)&nbsp;:
</p>

<p>
    <a href="<?= $login_url ?>"><?= $login_url ?></a>
</p>

<p>
    Si le lien précédent ne fonctionne pas, vous pouvez vous
    <a href="https://flus.io/">connecter à FreshRSS, menu «&nbsp;Facturation&nbsp;»</a>.
</p>

<p>
    Si vous avez décidé d’arrêter d’utiliser Flus mais souhaitez récupérer vos
    données (ou pour toute autre question), vous pouvez me contacter à
    l’adresse suivante&nbsp;: <a href="mailto:support@flus.io">support@flus.io</a>
</p>

<p>
    En vous remerciant de votre soutien,
</p>

<p>
    Marien
</p>
