<?php
    $this->layout('account.phtml', [
        'title' => 'Vos adresses',
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">
            Vos adresses
        </h1>
    </div>

    <form
        method="post"
        action="<?= url('account update address') ?>"
        class="form--address"
    >
        <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <div class="form-group <?= isset($errors['email']) ? 'form-group--invalid' : '' ?>">
            <label for="email">
                Adresse courriel
            </label>

            <input
                id="email"
                name="email"
                type="email"
                value="<?= $email ?>"
                required
            />

            <?php if (isset($errors['email'])): ?>
                <p class="form-group__error">
                    <?= $errors['email'] ?>
                </p>
            <?php endif; ?>
        </div>

        <fieldset>
            <legend>Adresse postale</legend>

            <p class="fieldset__caption">
                Cette adresse m’est nécessaire pour pouvoir établir des factures
                en bonne et due forme.
            </p>

            <div class="columns">
                <div class="columns__item">
                    <div class="form-group <?= isset($errors['address_first_name']) ? 'form-group--invalid' : '' ?>">
                        <label for="first-name">
                            Prénom
                        </label>

                        <input
                            id="first-name"
                            name="address[first_name]"
                            type="text"
                            value="<?= $address['first_name'] ?>"
                            required
                        />

                        <?php if (isset($errors['address_first_name'])): ?>
                            <p class="form-group__error">
                                <?= $errors['address_first_name'] ?>
                            </p>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="columns__item">
                    <div class="form-group <?= isset($errors['address_last_name']) ? 'form-group--invalid' : '' ?>">
                        <label for="last-name">
                            Nom
                        </label>

                        <input
                            id="last-name"
                            name="address[last_name]"
                            type="text"
                            value="<?= $address['last_name'] ?>"
                            required
                        />

                        <?php if (isset($errors['address_last_name'])): ?>
                            <p class="form-group__error">
                                <?= $errors['address_last_name'] ?>
                            </p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <div class="form-group <?= isset($errors['address_address1']) ? 'form-group--invalid' : '' ?>">
                <label for="address1">
                    Adresse
                </label>

                <input
                    id="address1"
                    name="address[address1]"
                    type="text"
                    value="<?= $address['address1'] ?>"
                    required
                />

                <?php if (isset($errors['address_address1'])): ?>
                    <p class="form-group__error">
                        <?= $errors['address_address1'] ?>
                    </p>
                <?php endif; ?>
            </div>

            <div class="columns">
                <div class="columns__item columns__item--postcode">
                    <div class="form-group <?= isset($errors['address_postcode']) ? 'form-group--invalid' : '' ?>">
                        <label for="postcode">
                            Code postal
                        </label>

                        <input
                            id="postcode"
                            name="address[postcode]"
                            type="text"
                            value="<?= $address['postcode'] ?>"
                            required
                        />

                        <?php if (isset($errors['address_postcode'])): ?>
                            <p class="form-group__error">
                                <?= $errors['address_postcode'] ?>
                            </p>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="columns__item columns__item--city">
                    <div class="form-group <?= isset($errors['address_city']) ? 'form-group--invalid' : '' ?>">
                        <label for="city">
                            Ville
                        </label>

                        <input
                            id="city"
                            name="address[city]"
                            type="text"
                            value="<?= $address['city'] ?>"
                            required
                        />

                        <?php if (isset($errors['address_city'])): ?>
                            <p class="form-group__error">
                                <?= $errors['address_city'] ?>
                            </p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <div class="form-group <?= isset($errors['address_country']) ? 'form-group--invalid' : '' ?>">
                <label for="country">
                    Pays
                </label>

                <select
                    id="country"
                    name="address[country]"
                    required
                >
                    <?php foreach ($countries as $code => $label): ?>
                        <option
                            value="<?= $code ?>"
                            <?= $address['country'] === $code ? 'selected' : '' ?>
                        >
                            <?= $label ?>
                        </option>
                    <?php endforeach; ?>
                </select>

                <?php if (isset($errors['address_country'])): ?>
                    <p class="form-group__error">
                        <?= $errors['address_country'] ?>
                    </p>
                <?php endif; ?>
            </div>
        </fieldset>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                Valider vos adresses
            </button>
        </div>

        <p class="paragraph--center">
            <a href="<?= url('account') ?>">
                Retour à votre abonnement
            </a>
        </p>
    </form>
</section>
