<?php
    $this->layout('account.phtml', [
        'title' => 'Votre abonnement',
    ]);
?>

<section class="panel">
    <div class="wrapper wrapper--small flow flow--larger">
        <h1>
            Votre abonnement
        </h1>

        <div class="panel panel--grey panel--rounded flow flow--large">
            <p>
                Votre abonnement est géré par un autre compte.
            </p>

            <p>
                N’hésitez pas à me contacter si vous pensez qu’il s’agit d’une erreur&nbsp;:
                <a href="<?= url('contact', ['subject' => 'Abonnement géré par un autre compte']) ?>">
                    accéder au formulaire de contact.
                </a>
            </p>

            <form class="text--center" method="post" action="<?= url('account logout') ?>">
                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

                <button class="button--primary" type="submit">
                    <?= icon('arrow-left') ?>

                    <?php if ($current_account->preferred_service === 'freshrss'): ?>
                        Revenir à FreshRSS
                    <?php else: ?>
                        Revenir à Flus
                    <?php endif; ?>
                </button>
            </form>
        </div>
    </div>
</section>
