<?php
    $this->layout('account.phtml', [
        'title' => 'Historique des paiements',
        'current_page' => 'invoices',
    ]);
?>

<section class="panel">
    <div class="wrapper flow flow--larger">
        <h1>
            Historique des paiements
        </h1>

        <?php if ($payments): ?>
            <ul class="list--nostyle list--border list--strip list--padded">
                <?php foreach ($payments as $payment): ?>
                    <li class="cols cols--gap-large cols--center">
                        <div class="col--extend">
                            <?php if ($payment->type === 'subscription' && $payment->frequency === 'month'): ?>
                                Abonnement mensuel
                            <?php elseif ($payment->type === 'subscription' && $payment->frequency === 'year'): ?>
                                Abonnement annuel
                            <?php elseif ($payment->type === 'common_pot'): ?>
                                Cagnotte
                            <?php elseif ($payment->type === 'credit'): ?>
                                Crédit
                            <?php else: ?>
                                Inconnu
                            <?php endif; ?>
                        </div>

                        <div class="col--size2">
                            <?= format_amount($payment->totalAmount()) ?>
                        </div>

                        <div class="col--size2">
                            <?php if ($payment->completed_at): ?>
                                <?= _d($payment->completed_at, 'dd MMM yyyy') ?>
                            <?php else: ?>
                                traitement en cours
                            <?php endif; ?>
                        </div>

                        <div class="col--size3">
                            <?php if ($payment->invoice_number): ?>
                                <a class="button button--block" href="<?= url('invoice download pdf', ['id' => $payment->id]) ?>">
                                    <?= icon('link') ?>
                                    <?= $payment->invoice_number ?>
                                </a>
                            <?php endif; ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ul>
        <?php else: ?>
            <div class="wrapper wrapper--small">
                <p class="panel panel--grey panel--rounded text--center text--bold">
                    Il n’y a aucune facture à afficher.
                </p>
            </div>
        <?php endif; ?>
    </div>
</section>
