<?php
    $this->layout('account.phtml', [
        'title' => 'Gestion des comptes abonnés',
        'current_page' => 'subscription',
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">
            Gestion des comptes abonnés
        </h1>
    </div>

    <p class="section__intro">
        Ici, vous pouvez décider de renouveler l’abonnement d’autres comptes.<br>
        <a href="<?= url('subscription init') ?>">Retourner au renouvellement</a>
    </p>

    <form
        method="post"
        action="<?= url('add managed account') ?>"
    >
        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <div class="form-group <?= isset($errors['email']) ? 'form-group--invalid' : '' ?>">
            <label for="email">
                Ajouter une adresse courriel
            </label>

            <div class="columns columns--center">
                <div class="columns__item columns__item--size9">
                    <input
                        id="email"
                        name="email"
                        type="email"
                        value="<?= $email ?>"
                        required
                    />

                    <?php if (isset($errors['email'])): ?>
                        <p class="form-group__error">
                            <?= $errors['email'] ?>
                        </p>
                    <?php endif; ?>
                </div>

                <div class="columns__item columns__item--size3">
                    <button type="submit" class="button--primary">
                        Ajouter
                    </button>
                </div>
            </div>
        </div>
    </form>

    <table>
        <thead>
            <tr>
                <th>Compte</th>
                <th>Expire le</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
            <?php array_unshift($managedAccounts, $account); ?>

            <?php foreach ($managedAccounts as $managedAccount): ?>
                <tr>
                    <td>
                        <?= $managedAccount->email ?>
                        <?php if ($managedAccount->id === $account->id): ?>
                            (vous)
                        <?php endif; ?>
                    </td>

                    <td>
                        <?= _d($managedAccount->expired_at, 'dd MMM yyyy') ?>
                    </td>

                    <td>
                        <?php if ($managedAccount->id !== $account->id): ?>
                            <form method="post" action="<?= url('delete managed account', ['id' => $managedAccount->id]) ?>">
                                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                                <button type="submit" class="button--default">
                                    Supprimer
                                </button>
                            </form>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</section>
