<?php
    $this->layout('account.phtml', [
        'title' => 'Votre profil de facturation',
        'current_page' => 'profile',
    ]);
?>

<section class="panel">
    <div class="wrapper wrapper--small flow flow--larger">
        <h1>
            Votre profil de facturation
        </h1>

        <?php if ($account->mustSetAddress()): ?>
            <div class="panel panel--topaz panel--rounded">
                <p>
                    <strong>Vous êtes sur le point de renouveler votre abonnement.</strong>
                </p>

                <p>
                    Avant cela, j’ai besoin de quelques informations pour pouvoir
                    établir vos factures.
                </p>
            </div>
        <?php endif; ?>

        <?php $count_managed_accounts = $account->countManagedAccounts(); ?>
        <?php if ($count_managed_accounts > 0): ?>
            <p class="panel panel--grey panel--rounded">
                Information&nbsp;: vous ne pouvez pas changer pour un
                compte «&nbsp;particulier&nbsp;» car vous gérer les
                abonnements d’autres comptes.
            </p>
        <?php endif; ?>

        <form
            method="post"
            action="<?= url('account update profile') ?>"
            class="flow flow--large"
            data-controller="profile"
        >
            <?php if ($form->isInvalid('@base')): ?>
                <p class="form-group__error">
                    Erreur&nbsp;:
                    <?= $form->error('@base') ?>
                </p>
            <?php endif; ?>

            <div class="cols cols--gap">
                <div class="col--size3">
                    Vous êtes
                </div>

                <div class="col--size4">
                    <input
                        id="entity-type-natural"
                        name="entity_type"
                        value="natural"
                        type="radio"
                        <?= $form->entity_type === 'natural' ? 'checked' : '' ?>
                        <?= $count_managed_accounts > 0 ? 'disabled' : '' ?>
                        data-action="profile#switchEntityType"
                    />

                    <label for="entity-type-natural">
                        un particulier
                    </label>
                </div>

                <div class="col--size4">
                    <input
                        id="entity-type-legal"
                        name="entity_type"
                        value="legal"
                        type="radio"
                        <?= $form->entity_type === 'legal' ? 'checked' : '' ?>
                        data-action="profile#switchEntityType"
                    />

                    <label for="entity-type-legal">
                        une structure
                    </label>
                </div>
            </div>

            <div class="flow flow--small">
                <label for="email">
                    Adresse courriel
                </label>

                <?php if ($form->isInvalid('email')): ?>
                    <p class="form-group__error" id="email-error">
                        Erreur&nbsp;:
                        <?= $form->error('email') ?>
                    </p>
                <?php endif; ?>

                <input
                    id="email"
                    name="email"
                    type="email"
                    value="<?= $form->email ?>"
                    required
                    <?php if ($form->isInvalid('email')): ?>
                        aria-invalid="true"
                        aria-errormessage="email-error"
                    <?php endif; ?>
                />
            </div>

            <div data-target="profile.sectionNatural">
                <div class="cols cols--gap">
                    <div class="col--size6 flow flow--small">
                        <label for="first-name">
                            Prénom
                        </label>

                        <?php if ($form->isInvalid('address_first_name')): ?>
                            <p class="form-group__error" id="first-name-error">
                                Erreur&nbsp;:
                                <?= $form->error('address_first_name') ?>
                            </p>
                        <?php endif; ?>

                        <input
                            id="first-name"
                            name="address_first_name"
                            type="text"
                            value="<?= $form->address_first_name ?>"
                            required
                            data-target="profile.firstName"
                            <?php if ($form->isInvalid('address_first_name')): ?>
                                aria-invalid="true"
                                aria-errormessage="first-name-error"
                            <?php endif; ?>
                        />
                    </div>

                    <div class="col--size6 flow flow--small">
                        <label for="last-name">
                            Nom
                        </label>

                        <?php if ($form->isInvalid('address_last_name')): ?>
                            <p class="form-group__error" id="last-name-error">
                                Erreur&nbsp;:
                                <?= $form->error('address_last_name') ?>
                            </p>
                        <?php endif; ?>

                        <input
                            id="last-name"
                            name="address_last_name"
                            type="text"
                            value="<?= $form->address_last_name ?>"
                            required
                            data-target="profile.lastName"
                            <?php if ($form->isInvalid('address_last_name')): ?>
                                aria-invalid="true"
                                aria-errormessage="last-name-error"
                            <?php endif; ?>
                        />
                    </div>
                </div>
            </div>

            <div class="flow flow--large" data-target="profile.sectionLegal">
                <div class="flow flow--small">
                    <label for="legal-name">
                        Raison sociale
                    </label>

                    <?php if ($form->isInvalid('address_legal_name')): ?>
                        <p class="form-group__error" id="legal-name-error">
                            Erreur&nbsp;:
                            <?= $form->error('address_legal_name') ?>
                        </p>
                    <?php endif; ?>

                    <input
                        id="legal-name"
                        name="address_legal_name"
                        type="text"
                        value="<?= $form->address_legal_name ?>"
                        required
                        data-target="profile.legalName"
                        <?php if ($form->isInvalid('address_legal_name')): ?>
                            aria-invalid="true"
                            aria-errormessage="legal-name-error"
                        <?php endif; ?>
                    />
                </div>

                <div class="flow flow--small">
                    <label for="company-department">
                        Service destinataire (optionel)
                    </label>

                    <?php if ($form->isInvalid('company_department')): ?>
                        <p class="form-group__error" id="company-department-error">
                            Erreur&nbsp;:
                            <?= $form->error('company_department') ?>
                        </p>
                    <?php endif; ?>

                    <input
                        id="company-department"
                        name="company_department"
                        type="text"
                        value="<?= $form->company_department ?>"
                        <?php if ($form->isInvalid('company_department')): ?>
                            aria-invalid="true"
                            aria-errormessage="company-department-error"
                        <?php endif; ?>
                    />
                </div>

                <div class="flow flow--small">
                    <label for="company-vat-number">
                        Numéro de <abbr>TVA</abbr> (optionel)
                    </label>

                    <?php if ($form->isInvalid('company_vat_number')): ?>
                        <p class="form-group__error" id="company-vat-number-error">
                            Erreur&nbsp;:
                            <?= $form->error('company_vat_number') ?>
                        </p>
                    <?php endif; ?>

                    <input
                        id="company-vat-number"
                        name="company_vat_number"
                        type="text"
                        minlength="10"
                        maxlength="20"
                        value="<?= $form->company_vat_number ?>"
                        <?php if ($form->isInvalid('company_vat_number')): ?>
                            aria-invalid="true"
                            aria-errormessage="company-vat-number-error"
                        <?php endif; ?>
                    />
                </div>
            </div>

            <div class="flow flow--small">
                <input
                    id="show-address"
                    name="show_address"
                    type="checkbox"
                    data-action="profile#switchAddress"
                    data-target="profile.controlAddress"
                    <?= $form->show_address ? 'checked' : '' ?>
                />

                <label for="show-address">
                    Faire apparaître votre adresse postale sur les factures (optionel)
                </label>
            </div>

            <fieldset id="address">
                <legend>Adresse postale</legend>

                <div class="flow flow--large">
                    <div class="flow flow--small">
                        <label for="address1">
                            Adresse
                        </label>

                        <?php if ($form->isInvalid('address_address1')): ?>
                            <p class="form-group__error" id="address1-error">
                                Erreur&nbsp;:
                                <?= $form->error('address_address1') ?>
                            </p>
                        <?php endif; ?>

                        <input
                            id="address1"
                            name="address_address1"
                            type="text"
                            value="<?= $form->address_address1 ?>"
                            <?php if ($form->isInvalid('address_address1')): ?>
                                aria-invalid="true"
                                aria-errormessage="address1-error"
                            <?php endif; ?>
                        />
                    </div>

                    <div class="cols cols--gap">
                        <div class="col--size3 flow flow--small">
                            <label for="postcode">
                                Code postal
                            </label>

                            <?php if ($form->isInvalid('address_postcode')): ?>
                                <p class="form-group__error" id="postcode-error">
                                    Erreur&nbsp;:
                                    <?= $form->error('address_postcode') ?>
                                </p>
                            <?php endif; ?>

                            <input
                                id="postcode"
                                name="address_postcode"
                                type="text"
                                value="<?= $form->address_postcode ?>"
                                <?php if ($form->isInvalid('address_postcode')): ?>
                                    aria-invalid="true"
                                    aria-errormessage="postcode-error"
                                <?php endif; ?>
                            />
                        </div>

                        <div class="col--extend flow flow--small">
                            <label for="city">
                                Ville
                            </label>

                            <?php if ($form->isInvalid('address_city')): ?>
                                <p class="form-group__error" id="city-error">
                                    Erreur&nbsp;:
                                    <?= $form->error('address_city') ?>
                                </p>
                            <?php endif; ?>

                            <input
                                id="city"
                                name="address_city"
                                type="text"
                                value="<?= $form->address_city ?>"
                                <?php if ($form->isInvalid('address_city')): ?>
                                    aria-invalid="true"
                                    aria-errormessage="city-error"
                                <?php endif; ?>
                            />
                        </div>
                    </div>

                    <div class="flow flow--small">
                        <label for="country">
                            Pays
                        </label>

                        <?php if ($form->isInvalid('address_country')): ?>
                            <p class="form-group__error" id="country-error">
                                Erreur&nbsp;:
                                <?= $form->error('address_country') ?>
                            </p>
                        <?php endif; ?>

                        <select
                            id="country"
                            name="address_country"
                            <?php if ($form->isInvalid('address_country')): ?>
                                aria-invalid="true"
                                aria-errormessage="country-error"
                            <?php endif; ?>
                        >
                            <?php foreach ($form->countries() as $code => $label): ?>
                                <option
                                    value="<?= $code ?>"
                                    <?= $form->address_country === $code ? 'selected' : '' ?>
                                >
                                    <?= $label ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                </div>
            </fieldset>

            <div class="text--center">
                <button type="submit" class="button--primary">
                    Enregistrer les modifications
                </button>
            </div>

            <input type="hidden" name="csrf_token" value="<?= $form->csrfToken() ?>" />
        </form>

        <?php if (!$account->isFree()): ?>
            <hr />

            <form
                class="panel panel--grey panel--rounded flow text--center"
                method="post"
                action="<?= url('account set reminder') ?>"
            >
                <?php if ($account->reminder): ?>
                    <p>
                        Vous recevrez un courriel à l’approche de l’échéance de
                        votre abonnement.
                    </p>

                    <button type="submit" name="reminder" value="false">
                        Désactiver le rappel
                    </button>
                <?php else: ?>
                    <p>
                        Vous pouvez recevoir un courriel à l’approche de l’échéance
                        de votre abonnement.
                    </p>

                    <button type="submit" name="reminder" value="true">
                        Activer le rappel
                    </button>
                <?php endif; ?>

                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                <input type="hidden" name="from" value="account profile" />
            </form>
        <?php endif; ?>
    </div>
</section>
