<?php
    $this->layout('account.phtml', [
        'title' => 'Votre profil de facturation',
        'current_page' => 'profile',
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">
            Votre profil de facturation
        </h1>
    </div>

    <?php if ($account->mustSetAddress()): ?>
        <div class="section__intro">
            <p>
                <strong>Vous êtes sur le point de renouveler votre abonnement.</strong>
            </p>

            <p>
                Avant cela, j’ai besoin de quelques informations pour pouvoir
                établir vos factures.
            </p>
        </div>
    <?php endif; ?>

    <form
        method="post"
        action="<?= url('account update profile') ?>"
        class="form--address"
    >
        <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />

        <?php if ($error): ?>
            <p class="form__error">
                <?= $error ?>
            </p>
        <?php endif; ?>

        <div class="form-group <?= isset($errors['email']) ? 'form-group--invalid' : '' ?>">
            <label for="email">
                Adresse courriel
            </label>

            <input
                id="email"
                name="email"
                type="email"
                value="<?= $email ?>"
                required
            />

            <?php if (isset($errors['email'])): ?>
                <p class="form-group__error">
                    <?= $errors['email'] ?>
                </p>
            <?php endif; ?>
        </div>

        <div class="columns">
            <div class="columns__item">
                <div class="form-group <?= isset($errors['address_first_name']) ? 'form-group--invalid' : '' ?>">
                    <label for="first-name">
                        Prénom
                    </label>

                    <input
                        id="first-name"
                        name="address[first_name]"
                        type="text"
                        value="<?= $address['first_name'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_first_name'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_first_name'] ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>

            <div class="columns__item">
                <div class="form-group <?= isset($errors['address_last_name']) ? 'form-group--invalid' : '' ?>">
                    <label for="last-name">
                        Nom
                    </label>

                    <input
                        id="last-name"
                        name="address[last_name]"
                        type="text"
                        value="<?= $address['last_name'] ?>"
                        required
                    />

                    <?php if (isset($errors['address_last_name'])): ?>
                        <p class="form-group__error">
                            <?= $errors['address_last_name'] ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="form-group" data-controller="checkboxes">
            <?php
                $is_checked = (
                    !empty($address['address1']) ||
                    !empty($address['postcode']) ||
                    !empty($address['city'])
                );
            ?>

            <input
                id="show-address"
                name="show_address"
                type="checkbox"
                data-action="checkboxes#switch"
                data-target="checkboxes.control"
                data-checkboxes-control="#address"
                <?= $is_checked ? 'checked' : '' ?>
            />

            <label for="show-address">
                Faire apparaître votre adresse postale sur les factures
            </label>
        </div>

        <fieldset id="address">
            <legend>Adresse postale</legend>

            <div class="form-group <?= isset($errors['address_address1']) ? 'form-group--invalid' : '' ?>">
                <label for="address1">
                    Adresse
                </label>

                <input
                    id="address1"
                    name="address[address1]"
                    type="text"
                    value="<?= $address['address1'] ?>"
                />

                <?php if (isset($errors['address_address1'])): ?>
                    <p class="form-group__error">
                        <?= $errors['address_address1'] ?>
                    </p>
                <?php endif; ?>
            </div>

            <div class="columns">
                <div class="columns__item columns__item--postcode">
                    <div class="form-group <?= isset($errors['address_postcode']) ? 'form-group--invalid' : '' ?>">
                        <label for="postcode">
                            Code postal
                        </label>

                        <input
                            id="postcode"
                            name="address[postcode]"
                            type="text"
                            value="<?= $address['postcode'] ?>"
                        />

                        <?php if (isset($errors['address_postcode'])): ?>
                            <p class="form-group__error">
                                <?= $errors['address_postcode'] ?>
                            </p>
                        <?php endif; ?>
                    </div>
                </div>

                <div class="columns__item columns__item--city">
                    <div class="form-group <?= isset($errors['address_city']) ? 'form-group--invalid' : '' ?>">
                        <label for="city">
                            Ville
                        </label>

                        <input
                            id="city"
                            name="address[city]"
                            type="text"
                            value="<?= $address['city'] ?>"
                        />

                        <?php if (isset($errors['address_city'])): ?>
                            <p class="form-group__error">
                                <?= $errors['address_city'] ?>
                            </p>
                        <?php endif; ?>
                    </div>
                </div>
            </div>

            <div class="form-group <?= isset($errors['address_country']) ? 'form-group--invalid' : '' ?>">
                <label for="country">
                    Pays
                </label>

                <select
                    id="country"
                    name="address[country]"
                >
                    <?php foreach ($countries as $code => $label): ?>
                        <option
                            value="<?= $code ?>"
                            <?= $address['country'] === $code ? 'selected' : '' ?>
                        >
                            <?= $label ?>
                        </option>
                    <?php endforeach; ?>
                </select>

                <?php if (isset($errors['address_country'])): ?>
                    <p class="form-group__error">
                        <?= $errors['address_country'] ?>
                    </p>
                <?php endif; ?>
            </div>
        </fieldset>

        <?php if ($account->company_vat_number): ?>
            <p>
                Numéro <abbr>TVA</abbr> : <?= $account->company_vat_number ?>
            </p>
        <?php endif; ?>

        <div class="form__actions">
            <button type="submit" class="button--primary">
                Enregistrer les modifications
            </button>
        </div>
    </form>

    <hr />

    <?php if (!$account->isFree()): ?>
        <form method="post" action="<?= url('account set reminder') ?>">
            <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
            <input type="hidden" name="from" value="account profile" />

            <?php if ($account->reminder): ?>
                <p class="paragraph--center paragraph--limit">
                    Vous recevrez un courriel à l’approche de l’échéance de
                    votre abonnement.
                </p>

                <div class="paragraph--center">
                    <button type="submit" class="button--ghost" name="reminder" value="false">
                        Désactiver le rappel
                    </button>
                </div>
            <?php else: ?>
                <p class="paragraph--center paragraph--limit">
                    Vous pouvez recevoir un courriel à l’approche de l’échéance
                    de votre abonnement.
                </p>

                <div class="paragraph--center">
                    <button type="submit" class="button--default" name="reminder" value="true">
                        Activer le rappel
                    </button>
                </div>
            <?php endif; ?>
        </form>
    <?php endif; ?>
</section>
