<?php
    $this->layout('account.phtml', [
        'title' => 'Votre compte de paiement Flus',
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">
            Votre compte de paiement Flus
        </h1>
    </div>

    <div class="section__intro">
        <p>
            <?= $this->protect($account->email) ?><br />

            <?php if ($ongoing_payment): ?>
                <strong>
                    Votre paiement est en cours de traitement…
                </strong>
            <?php elseif ($account->isFree()): ?>
                Vous bénéficiez d’un abonnement gratuit, veinard‧e.
            <?php elseif ($account->hasExpired()): ?>
                <strong>
                    Votre abonnement a expiré le <?= _d($account->expired_at, 'dd MMMM yyyy') ?>.
                </strong>
            <?php else: ?>
                Votre abonnement expirera le <strong><?= _d($account->expired_at, 'dd MMMM yyyy') ?>.</strong>
                <?php if ($account->reminder): ?>
                    Vous recevrez un courriel à l’approche de l’échéance.
                <?php endif; ?>
            <?php endif; ?>
        </p>

        <?php if (!$account->isFree()): ?>
            <form method="post" action="<?= url('account set reminder') ?>">
                <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                <input type="hidden" name="from" value="account" />

                <p class="paragraph--center">
                    <?php if ($account->reminder): ?>
                        <button type="submit" class="button--ghost" name="reminder" value="false">
                            Désactiver le rappel
                        </button>
                    <?php else: ?>
                        <button type="submit" class="button--default" name="reminder" value="true">
                            Activer un rappel
                        </button>
                    <?php endif; ?>
                </p>
            </form>
        <?php endif; ?>
    </div>

    <nav class="navaccount">
        <ul class="navaccount__container">
            <?php if (!$account->isFree()): ?>
                <li class="navaccount__item <?= $account->hasExpired() ? 'navaccount__item--featured' : '' ?>">
                    <a class="navaccount__link navaccount__link--subscription" href="<?= url('subscription init') ?>">
                        Renouveler votre abonnement
                    </a>
                </li>
            <?php endif; ?>

            <li class="navaccount__item">
                <a class="navaccount__link navaccount__link--address" href="<?= url('account address') ?>">
                    Gérer vos adresses
                </a>
            </li>

            <li class="navaccount__item">
                <form method="post" action="<?= url('account logout') ?>">
                    <input type="hidden" name="csrf" value="<?= $csrf_token ?>" />
                    <button class="navaccount__button navaccount__button--leave" type="submit">
                        <?php if ($account->preferred_service === 'flusio'): ?>
                            <img alt="" src="<?= url_static('flus.svg') ?>" width="70"/>
                        <?php else: ?>
                            <img alt="" src="<?= url_static('freshrss.svg') ?>" width="70"/>
                        <?php endif; ?>
                        <br />
                        Revenir à l’application
                    </button>
                </form>
            </li>
        </ul>
    </nav>

    <div class="header">
        <h2 class="header__title">
            Vos paiements passés
        </h2>
    </div>

    <?php if ($payments): ?>
        <table>
            <tbody>
                <?php foreach ($payments as $payment): ?>
                    <tr <?= !$payment->completed_at ? 'class="row--ghost"' : ''?> >
                        <td class="cell--right">
                            <?= format_amount($payment->amount) ?>
                        </td>

                        <td>
                            <?php if ($payment->type === 'subscription' && $payment->frequency === 'month'): ?>
                                Abonnement mois
                            <?php elseif ($payment->type === 'subscription' && $payment->frequency === 'year'): ?>
                                Abonnement année
                            <?php elseif ($payment->type === 'common_pot'): ?>
                                Cagnotte
                            <?php elseif ($payment->type === 'credit'): ?>
                                Crédit
                            <?php else: ?>
                                Heu… non
                            <?php endif; ?>
                        </td>

                        <td>
                            <?php if ($payment->completed_at): ?>
                                <?= _d($payment->completed_at, 'dd MMM yyyy') ?>
                            <?php else: ?>
                                traitement en cours
                            <?php endif; ?>
                        </td>

                        <td>
                            <?php if ($payment->invoice_number): ?>
                                <a href="<?= url('invoice download pdf', ['id' => $payment->id]) ?>">
                                    <?= $payment->invoice_number ?>
                                </a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p class="paragraph--center paragraph--secondary">
            Il n’y a aucun paiement à afficher.
        </p>
    <?php endif; ?>
</section>
