<?php
    $this->layout('account.phtml', [
        'title' => 'Votre abonnement à Flus',
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">
            Votre abonnement à Flus
        </h1>
    </div>

    <div class="section__intro">
        <p>
            <?= $this->protect($account->email) ?><br />

            <?php if ($account->isFree()): ?>
                Vous bénéficiez d’un abonnement gratuit, veinard‧e.
            <?php elseif ($account->hasExpired()): ?>
                <strong>
                    Votre abonnement a expiré le <?= format_date($account->expired_at, '%d %B %Y') ?>.
                </strong>
            <?php else: ?>
                Votre abonnement expirera le <strong><?= format_date($account->expired_at, '%d %B %Y') ?>.</strong>
                <?php if ($account->reminder): ?>
                    Vous recevrez un courriel à l’approche de l’échéance.
                <?php endif; ?>
            <?php endif; ?>
        </p>

        <?php if (!$account->isFree()): ?>
            <form method="post" action="<?= url('account set reminder') ?>">
                <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />
                <?php if ($account->reminder): ?>
                    <button type="submit" class="button--ghost" name="reminder" value="false">
                        Désactiver le rappel
                    </button>
                <?php else: ?>
                    <button type="submit" class="button--default" name="reminder" value="true">
                        Activer un rappel
                    </button>
                <?php endif; ?>
            </form>
        <?php endif; ?>
    </div>

    <?php if (!$account->isFree()): ?>
        <p class="paragraph--center">
            <?php if ($account->hasExpired()): ?>
                <a class="call-to-action" href="<?= url('subscription init') ?>">
                    Renouveler votre abonnement
                </a>
            <?php else: ?>
                <a href="<?= url('subscription init') ?>">
                    Renouveler votre abonnement
                </a>
            <?php endif; ?>
        </p>
    <?php endif; ?>

    <p class="paragraph--center">
        <a href="<?= url('common pot contribution') ?>">
            Contribuer à la cagnotte
        </a>
    </p>

    <?php if (!$account->isFree()): ?>
        <p class="paragraph--center">
            <a href="<?= url('common pot usage') ?>">
                Bénéficier de la cagnotte
            </a>
        </p>
    <?php endif; ?>

    <p class="paragraph--center">
        <a href="<?= url('account address') ?>">
            Gérer vos adresses
        </a>
    </p>

    <div class="columns columns--center columns--spaced columns--background">
        <div class="columns__item columns__item--center">
            <p>
                <a href="https://flus.io/">
                    <img alt="" src="<?= url_static('freshrss.svg') ?>" width="70"/><br />
                    Accéder à Flus 1
                </a>
            </p>
        </div>

        <div class="columns__item columns__item--center">
            <p>
                <a href="https://app.flus.fr/">
                    <img alt="" src="<?= url_static('flus.svg') ?>" width="75"/><br />
                    Accéder à Flus 2
                </a>
            </p>
        </div>
    </div>

    <div class="header">
        <h2 class="header__title">
            Vos paiements passés
        </h2>
    </div>

    <?php if ($payments): ?>
        <table>
            <tbody>
                <?php foreach ($payments as $payment): ?>
                    <tr <?= !$payment->completed_at ? 'class="row--ghost"' : ''?> >
                        <td class="cell--right">
                            <?= format_amount($payment->amount) ?>
                        </td>

                        <td>
                            <?php if ($payment->type === 'subscription' && $payment->frequency === 'month'): ?>
                                Abonnement mois
                            <?php elseif ($payment->type === 'subscription' && $payment->frequency === 'year'): ?>
                                Abonnement année
                            <?php elseif ($payment->type === 'common_pot'): ?>
                                Cagnotte
                            <?php else: ?>
                                Heu… non
                            <?php endif; ?>
                        </td>

                        <td>
                            <?php if ($payment->completed_at): ?>
                                <?= format_date($payment->completed_at, '%d %b %Y') ?>
                            <?php else: ?>
                                en attente
                            <?php endif; ?>
                        </td>

                        <td>
                            <?php if ($payment->invoice_number): ?>
                                <a href="<?= url('invoice download pdf', ['id' => $payment->id]) ?>">
                                    <?= $payment->invoice_number ?>
                                </a>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php else: ?>
        <p class="paragraph--center paragraph--secondary">
            Il n’y a aucun paiement à afficher.
        </p>
    <?php endif; ?>
</section>
