<?php
    $this->layout('admin.phtml', [
        'title' => 'Connexion à l’administration',
    ]);
?>

<div class="header">
    <h1 class="header__title">Connexion à l’administration</h1>
</div>

<form method="post" action="<?= url('create_session') ?>">
    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

    <?php if (isset($from)): ?>
        <input type="hidden" name="from" value="<?= $from ?>" />
    <?php endif; ?>

    <div class="form-group">
        <label for="password">Mot de passe</label>
        <input
            type="password"
            name="password"
            id="password"
            required
            value="<?= isset($password) ? $password : '' ?>"
        />
    </div>

    <div class="form__actions">
        <button type="submit" class="button--primary">
            Se connecter
        </button>
    </div>
</form>

<p class="paragraph--center">
    <a href="<?= url('home#index') ?>">
        Retour à l’accueil
    </a>
</p>
