<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="initial-scale=1.0" />
        <link rel="stylesheet" href="<?= url_static('style/stripe_redirection.css') ?>">
    </head>

    <body>
        <noscript>
            <p>
                Vous devez activer le JavaScript sur cette page et la suivante
                pour pouvoir continuer, déso&nbsp;!
            </p>
        </noscript>

        <p id="waiting-message">
            Vous allez être redirigé·e vers Stripe dans quelques instants,
            veuillez patienter…
        </p>

        <div id="spinner"></div>

        <p id="stripe-error">
        </p>

        <script src="https://js.stripe.com/v3/"></script>
        <script>
            document.getElementById('waiting-message').style.display = 'block';
            document.getElementById('spinner').style.display = 'block';
            document.getElementById('stripe-error').style.display = 'block';

            window.setTimeout(function() {
                var stripe = Stripe('<?= $stripe_public_key ?>');
                stripe.redirectToCheckout({
                    sessionId: '<?= $stripe_session_id ?>',
                }).then(function (result) {
                    document.getElementById('spinner').remove();
                    document.getElementById('stripe-error').innerText = result.error.message;
                });
            }, 3000);
        </script>
    </body>
</html>
