<?php
    $this->layout('account.phtml', [
        'title' => 'Bénéficier de la cagnotte commune',
    ]);
?>

<section class="section section--text">
    <div class="header">
        <h1 class="header__title">
            Bénéficier de la cagnotte commune
        </h1>
    </div>

    <p class="paragraph--featured">
        Elle s’élève à <?= $this->safe('common_pot_amount') ?>&nbsp;€
    </p>

    <p class="section__intro">
        Si vous n’avez pas les moyens de payer un abonnement, vous pouvez
        bénéficier d’un renouvellement grâce à la cagnotte que d’autres
        personnes ont financé. Aucun justificatif ne vous sera demandé.<br />
        <a href="<?= url('common pot account') ?>">
            Des questions&nbsp;?
        </a>
    </p>

    <?php if ($error): ?>
        <p class="form__error">
            <?= $error ?>
        </p>
    <?php endif; ?>

    <?php if ($free_account): ?>
        <p class="paragraph--center">
            Vous bénéficiez déjà d’un compte gratuit, en quoi ça vous serez utile&nbsp;?
        </p>
    <?php elseif (!$expire_soon): ?>
        <p class="paragraph--center">
            Vous pourrez utiliser la cagnotte lorsque votre abonnement sera sur le point d’expirer (à 7 jours ou moins). Patience&nbsp;!
        </p>
    <?php elseif (!$full_enough): ?>
        <p class="paragraph--center">
            Malheureusement, il n’y a plus assez d’argent dans la cagnotte pour
            vous faire bénéficier d’un mois supplémentaire d’abonnement.
        </p>
    <?php else: ?>
        <form
             method="post"
             action="<?= url('use common pot') ?>"
             class="form--common-pot"
         >
            <input type="hidden" name="csrf" value="<?= csrf_token() ?>" />

            <p class="paragraph--featured">
                Vous êtes sur le point de renouveler un mois d’abonnement (soit l’équivalent de 3&nbsp;€)
            </p>

            <div class="form-group form-group--cgv <?= isset($errors['cgv']) ? 'form-group--invalid' : '' ?>">
                <p class="form-group__caption">
                    Vous devriez prendre le temps de
                    <a href="<?= url('cgv') ?>" target="_blank" rel="noopener noreferrer nofollow">
                        lire les Conditions Générales de Vente</a>
                    pour vous assurer que celles-ci vous conviennent.<br/>
                </p>

                <input
                    id="cgv"
                    name="accept_cgv"
                    type="checkbox"
                    required
                />

                <label for="cgv">
                    Accepter les Conditions Générales de Vente
                </label>

                <?php if (isset($errors['cgv'])): ?>
                    <p class="form-group__error">
                        <?= $errors['cgv'] ?>
                    </p>
                <?php endif; ?>
            </div>

            <div class="form__actions">
                <button type="submit" class="button--primary">
                    Renouveler votre abonnement
                </button>
            </div>
        </form>
    <?php endif; ?>

    <p class="paragraph--center">
        <a href="<?= url('account') ?>">
            Retour à votre abonnement
        </a>
    </p>
</section>
