<?php
    $this->layout('base.phtml', [
        'title' => 'Conditions Générales de Vente · Flus',
        'canonical' => url_full('cgv'),
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">Conditions Générales de Vente</h1>
    </div>

    <p class="section__intro">
        Afin de souscrire à un abonnement ou de participer à
        <a href="<?= url('common pot') ?>">la cagnotte commune</a>, vous devez
        accepter les conditions suivantes. Bonne lecture&nbsp;!
    </p>

    <img
        class="illustration illustration--centered terms"
        alt=""
        src="<?= url_static('illustrations/terms.svg') ?>"
        height="250"
    />

    <p>
        Ces conditions générales de vente (<abbr>CGV</abbr>) s’appliquent depuis
        <strong>le 14 octobre 2020</strong> (<a href="https://github.com/flusio/flus.fr/commits/master/src/views/home/cgv.phtml">historique</a>).
    </p>

    <h2 id="informations-sur-le-vendeur">Informations sur le vendeur</h2>

    <p>
        Le vendeur désigne Marien Fressinaud.
        Adresse&nbsp;: 57 rue du Vercors – 38000 Grenoble – France.
        <a href="<?= url('contact') ?>">Contact</a>
    </p>

    <p>
        Flus, micro-entreprise<br />
        <abbr>RCS</abbr> Grenoble 878 196 278<br />
        N° Siret : 878 196 278 00013<br />
        TVA non applicable, article 293 B du <abbr>CGI</abbr>
    </p>

    <h2 id="informations-sur-le-service">Informations sur le service</h2>

    <p>
        Le service mis à disposition par le vendeur consiste en un portail
        Internet de veille de l’actualité. Il se présente sous la forme de deux
        logiciels libres (c’est-à-dire dont le code est placé sous une licence
        libre)&nbsp;:
    </p>

    <ul>
        <li>
            FreshRSS, un agrégateur de flux <abbr>RSS</abbr>, qui offre la
            possibilité pour l’acheteur d’indiquer des sites et blogs qu’il
            souhaite suivre. Le logiciel se charge alors de récupérer
            automatiquement à intervalle régulier les nouveaux articles publiés
            par ces sites et les afficher à l’acheteur au sein du service. Ces
            sites doivent mettre à disposition un flux RSS et / ou Atom pour
            que le service fonctionne correctement.
        </li>

        <li>
            Flus, un média social, qui offrira la possibilité à ses
            utilisateurs et utilisatrices de stocker des liens sous forme de
            collections, afin de les organiser et pouvoir les retrouver
            aisément plus tard. Ces collections pourront être partagées
            publiquement à travers une page publique, ou au sein de communautés
            créées par les utilisateur·ices. Chaque utilsateur·ice pourra
            suivre les collections qui l’intéressent et être tenu·e informé·e
            des ajouts et modifications à ces collections. Le service permettra
            également la discussion intra et inter communautés. Les collections
            pourront être, à terme, alimentées automatiquement grâce à des flux
            <abbr>RSS</abbr> et Atom. Des fonctionnalités pour faciliter la
            découverte et la lecture de contenu seront également
            présentes.<br/>
            <strong>L’acheteur reconnaît avoir été informé que ce logiciel est
                cours de développement et que le service ouvrira ses portes
                courant décembre.</strong>
        </li>
    </ul>

    <p>
        Le service est amené à évoluer régulièrement à travers les mises à jour
        des logiciels, développées à la fois par une communauté de développeurs
        et développeuses, et par le vendeur du service qui s’engage de ce fait
        à contribuer au développement d’un bien commun. Cet engagement sera
        tenu aussi longtemps que le vendeur pourra vivre du service.
    </p>

    <p>
         L’utilisation du service est soumise aux conditions édictées dans les
         Conditions Générales d’Utilisation (<abbr>CGU</abbr>) que l’acheteur
         a accepté en créant un compte sur l’un ou l’autre des logiciels. Son
         abonnement pourra être annulé et l’accès au service refusé en cas de
         non-respect de ces conditions.
    </p>

    <h2 id="clause-abonnement">Clause liée à l’abonnement</h2>

    <p>
        L’abonnement permet d’accéder au service régi par ces <abbr>CGV</abbr>
        au-delà de la période d’essai garantie d’un mois.
    </p>

    <p>
        Le prix de l’abonnement permettant d’accéder au service est de 3&nbsp;€
        toutes taxes comprises (<abbr>TTC</abbr>). L’abonnement donne accès au
        service pour une période d’un mois à compter de la validation du paiement.
    </p>

    <p>
        Il est également possible de prendre un abonnement pour une période d’un
        an. Le prix de l’abonnement est alors de 30&nbsp;€ <abbr>TTC</abbr>.
    </p>

    <p>
        Le vendeur n’étant pas soumis à la <abbr>TVA</abbr>, les prix donnés
        correspondent également aux prix hors-taxe (<abbr>HT</abbr>).
    </p>

    <h2 id="clause-cagnotte">Clause liée à la cagnotte commune</h2>

    <p>
        L’acheteur reconnaît participer librement à un système qui permettra
        d’offrir à n’importe qui un abonnement mensuel gratuit&nbsp;: la
        cagnotte commune. Il ne pourra pas faire valoir cette participation
        pour bénéficier lui-même d’un abonnement gratuit, sauf à en faire la
        demande via le mécanisme de renouvellement de son abonnement, de la
        même manière que les autres utilisateur·ices du service. Il ne pourra
        pas non plus diriger cette participation pour en faire bénéficier une
        personne spécifique de son choix.
    </p>

    <p>
        La cagnotte pourra bénéficier à n’importe qui en faisant la demande. La
        cagnotte sera plus spécifiquement dirigée vers les personnes
        bénéficiant de revenus modestes, mais aucun justificatif ne sera
        demandé.
    </p>

    <p>
        L’acheteur est libre de fixer lui-même le montant de sa participation,
        dans une fourchette de 1&nbsp;€ à 1&nbsp;000&nbsp;€. Le nombre
        d’abonnements offerts par la participation de l’acheteur sera calculé
        en fonction du montant versé, divisé par le prix d’un abonnement
        mensuel, situé actuellement à 3&nbsp;€ <abbr>TTC</abbr>. Ainsi, une
        participation de 30&nbsp;€ offrira 10 abonnements mensuels. Il n’est
        pas prévu de permettre l’offre d’abonnements annuels.
    </p>

    <h2 id="livraison-et-conditions">Livraison et conditions</h2>

    <p>
        L’acheteur peut bénéficier de l’utilisation du service selon les termes
        édictés par les <abbr>CGU</abbr> et les <abbr>CGV</abbr> aussitôt que
        le paiement de son abonnement a été validé par le prestataire de
        paiement retenu (en l’occurrence, <a href="https://stripe.com/fr">Stripe</a>).
        En cas d’échec de l’application de cet engagement, le vendeur s’engage
        à faire bénéficier à l’acheteur d’une période de gratuité au service
        dès lors qu’il en aura été tenu au courant, calculée par le vendeur en
        fonction du préjudice.
    </p>

    <p>
        Dans le cas d’une participation de l’acheteur à la cagnotte, celle-ci
        pourra bénéficier aux autres utilisateurs et utilisatrices du service
        dès lors que la cagnotte sera «&nbsp;activée&nbsp;». Cette activation
        se fera au moment de l’ouverture du logiciel Flus. Cette ouverture
        devrait se faire sous la forme d’une version bêta durant le mois de
        décembre 2020, mais le vendeur tient à souligner qu’il ne s’agit que
        d’une estimation et que cette date est amenée à évoluer s’il l’estime
        nécessaire.
    </p>

    <p>
        Aucune donnée de paiement (ex. numéro de carte bancaire) n’est
        manipulée directement par le vendeur. Le paiement est considéré comme
        validé à partir du moment où le prestataire le fait savoir au vendeur
        (ex. à travers un message de retour automatique). Si le prestataire
        retourne un message indiquant l’échec du paiement, l’acheteur ne
        saurait faire valoir ses droits auprès du vendeur.
    </p>

    <h2 id="informations-sur-le-droit-de-rétractation">Droit de rétractation</h2>

    <p>
        L’acheteur accepte renoncer à son droit de rétractation de 14 jours. Ce
        renoncement est justifié par la période d’essai gratuite de 1 mois dont
        il dispose.
    </p>

    <p>
        L’acheteur peut toutefois faire une réclamation auprès du vendeur
        <a href="<?= url('contact', ['subject' => 'Droit de rétractation']) ?>">
            en le contactant par message
        </a>.
    </p>
</section>

<hr />
