<?php
    $this->layout('base.phtml', [
        'title' => 'Conditions Générales de Vente · Flus',
        'canonical' => url_full('cgv'),
    ]);
?>

<nav class="layout__breadcrumb" aria-label="Fil d’Ariane">
    <ul class="list--nostyle">
        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('home') ?>" rel="home">

                Accueil
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('legal') ?>">

                Mentions légales
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" aria-current="page" href="<?= url('cgv') ?>">

                Conditions Générales de Vente
            </a>
        </li>
    </ul>
</nav>

<article>
    <header class="panel panel--primary panel--header">
        <div class="wrapper wrapper--larger wrapper--center text--center">
            <h1>
                Conditions Générales de Vente
            </h1>
        </div>
    </header>

    <div class="panel">
        <div class="wrapper wrapper--text wrapper--center text-container">
            <p>
                Ces conditions générales de vente (<abbr>CGV</abbr>) s’appliquent depuis
                <strong>le 12 juillet 2023</strong> (<a href="https://github.com/flusio/flus.fr/commits/main/src/views/home/cgv.phtml">historique</a>).
            </p>

            <h2 id="informations-sur-le-vendeur">Informations sur le vendeur</h2>

            <p>
                Le vendeur désigne Marien Fressinaud.
                Adresse&nbsp;: 4 bis rue Germain – 38100 Grenoble – France.
                <a href="<?= url('contact') ?>">Contact</a>
            </p>

            <p>
                Flus, micro-entreprise<br />
                <abbr>RCS</abbr> Grenoble 878 196 278<br />
                N° Siret : 878 196 278 00021<br />
                <abbr>TVA</abbr> non applicable, article 293 B du <abbr>CGI</abbr>
            </p>

            <h2 id="informations-sur-le-service">Informations sur le service</h2>

            <p>
                Le service mis à disposition par le vendeur consiste en un portail
                Internet de veille de l’actualité. Il se présente sous la forme de deux
                logiciels libres (c’est-à-dire dont le code est placé sous une licence
                libre)&nbsp;:
            </p>

            <ul>
                <li>
                    FreshRSS, un agrégateur de flux <abbr>RSS</abbr>, qui offre la
                    possibilité pour l’acheteur d’indiquer des sites et blogs qu’il
                    souhaite suivre. Le logiciel se charge alors de récupérer
                    automatiquement à intervalle régulier les nouveaux articles publiés
                    par ces sites et les afficher à l’acheteur au sein du service. Ces
                    sites doivent mettre à disposition un flux RSS et / ou Atom pour
                    que le service fonctionne correctement.
                </li>

                <li>
                    Flus, un média de veille qui, en plus des possibilités décrites
                    ci-dessus, offre la possibilité à ses utilisateurs et utilisatrices
                    de stocker des liens sous forme de collections, afin de les
                    organiser, les partager et en discuter avec les autres
                    utilisateurs.
                </li>
            </ul>

            <p>
                Le service est amené à évoluer régulièrement à travers les mises à jour
                des logiciels, développés à la fois par une communauté de développeurs
                et développeuses, et par le vendeur du service qui s’engage de ce fait
                à contribuer au développement d’un bien commun. Cet engagement sera
                tenu aussi longtemps que le vendeur pourra vivre du service.
            </p>

            <p>
                 L’utilisation du service est soumise aux conditions édictées dans les
                 Conditions Générales d’Utilisation (<abbr>CGU</abbr>) que l’acheteur
                 a accepté en créant un compte sur l’un ou l’autre des logiciels. Son
                 abonnement pourra être annulé et l’accès au service refusé en cas de
                 non-respect de ces conditions.
            </p>

            <h2 id="clause-abonnement">Clause liée à l’abonnement individuel</h2>

            <p>
                L’abonnement permet d’accéder au service régi par ces <abbr>CGV</abbr>
                au-delà de la période d’essai garantie d’un mois. L’abonnement donne
                accès au service pour une période d’un an à compter de la validation du
                paiement.
            </p>

            <p>
                L’abonnement ne peut être renouvelé qu’à un mois de l’expiration de
                celui-ci.
            </p>

            <p>
                Le prix de l’abonnement permettant d’accéder au service est décidé au
                moment du renouvellement par l’acheteur. Le prix peut être fixé entre 0
                et 120 € toutes taxes comprises (<abbr>TTC</abbr>).
            </p>

            <p>
                L’acheteur bénéficie d’une aide fournie par le vendeur pour déterminer
                le prix qui correspond le mieux à son budget :
            </p>

            <ul>
                <li>le tarif « solidaire » à 15 € par an permet de soutenir le projet à un prix réduit ;</li>
                <li>le tarif « équilibre » à 30 € par an est le prix de référence ;</li>
                <li>le tarif « soutien » correspond au montant que chaque acheteur
                    ayant un abonnement actif devrait payer pour que le vendeur
                    atteigne son objectif financier annuel.</li>
            </ul>

            <p>
                Le tarif « soutien » évolue constamment. Il est calculé en divisant
                l’objectif financier par le nombre d’abonnements actifs. Le prix
                minimum de ce tarif est de 1 €. Son prix maximum est de 120 € (soit
                l’équivalent de 10 € par mois). L’objectif financier est défini une
                fois au début de chaque année par le vendeur et est indiqué sur la page
                « Tarifs » du site <a href="https://flus.fr">flus.fr</a>. Un abonnement
                actif est défini par le fait que sa date d’expiration n’a pas expiré et
                par le fait que l’acheteur associé ait effectué au moins un paiement
                supérieur à 0 euro.
            </p>

            <p>
                Le vendeur n’étant pas soumis à la <abbr>TVA</abbr>, les prix donnés
                correspondent également aux prix hors-taxe (<abbr>HT</abbr>).
            </p>

            <h2 id="clause-abonnement">Clause liée à l’abonnement groupé</h2>

            <p>
                L’acheteur ayant le statut de personne morale (ou « structure ») peut,
                s’il le souhaite, gérer les abonnements d’autres comptes que le sien.
                La clause liée à l’abonnement individuel s’applique à l’abonnement
                groupé avec les précisions données ci-dessous.
            </p>

            <p>
                Avant de gérer un autre compte que le sien, l’acheteur s’engage à
                demander le consentement de la personne possédant cet autre compte.
            </p>

            <p>
                Si les comptes gérés par l’acheteur doivent expirer à une date
                antérieure que le sien, ceux-ci sont synchronisés sur la date du compte
                de l’acheteur.
            </p>

            <p>
                Le prix total payé par l’acheteur correspond au prix décidé par
                l’acheteur multiplié par le nombre de comptes gérés par l’acheteur.
                Ainsi, pour un prix choisi de 30 € et 3 comptes gérés (incluant le
                sien), l’acheteur aura à payer un total de 90 € <abbr>TTC</abbr>.
            </p>

            <p>
                L’acheteur peut décider à n’importe quel moment d’arrêter de gérer un
                compte autre que le sien. Cela n’impacte pas la date d’expiration
                d’aucun des comptes.
            </p>

            <h2 id="livraison-et-conditions">Livraison et conditions</h2>

            <p>
                L’acheteur peut bénéficier de l’utilisation du service selon les termes
                édictés par les <abbr>CGU</abbr> et les <abbr>CGV</abbr> aussitôt que
                le paiement de son abonnement a été validé. En cas d’échec de
                l’application de cet engagement, le vendeur s’engage à faire bénéficier
                à l’acheteur d’une période de gratuité au service dès lors qu’il en
                aura été tenu au courant, calculée par le vendeur en fonction du
                préjudice.
            </p>

            <p>
                Si l’acheteur paye par carte bancaire, la validation est faite par le
                prestataire de paiement retenu (en l’occurrence, <a href="https://stripe.com/fr">Stripe</a>).
            </p>

            <p>
                Aucune donnée de paiement (ex. numéro de carte bancaire) n’est
                manipulée directement par le vendeur. Le paiement est considéré comme
                validé à partir du moment où le prestataire le fait savoir au vendeur
                (ex. à travers un message de retour automatique). Si le prestataire
                retourne un message indiquant l’échec du paiement, l’acheteur ne
                saurait faire valoir ses droits auprès du vendeur.
            </p>

            <h2 id="informations-sur-le-droit-de-rétractation">Droit de rétractation</h2>

            <p>
                L’acheteur accepte renoncer à son droit de rétractation de 14 jours. Ce
                renoncement est justifié par la période d’essai gratuite de 1 mois dont
                il dispose et par la possibilité de choisir lui-même un prix de 0 euro.
            </p>

            <p>
                L’acheteur peut toutefois faire une réclamation auprès du vendeur
                <a href="<?= url('contact', ['subject' => 'Droit de rétractation']) ?>">
                    en le contactant par message
                </a>.
            </p>
        </div>
    </div>
</article>
