<?php
    $this->layout('base.phtml', [
        'title' => 'Conditions Générales de Vente · Flus',
        'canonical' => url_full('cgv'),
    ]);
?>

<section class="section">
    <div class="header">
        <h1 class="header__title">Conditions Générales de Vente</h1>
    </div>

    <p class="section__intro">
        Afin de participer à <a href="<?= url('common pot') ?>">la cagnotte
        commune</a>, vous devez accepter les conditions suivantes. Bonne lecture&nbsp;!
    </p>

    <img
        class="illustration illustration--centered terms"
        alt=""
        src="<?= url_static('illustrations/terms.svg') ?>"
        height="250"
    />

    <p>
        Ces conditions générales de vente (<abbr>CGV</abbr>) s’appliquent depuis
        <strong>le 27 mai 2020</strong> (<a href="https://github.com/flusio/flus.fr/commits/master/src/views/home/cgv.phtml">historique</a>).
    </p>

    <h2 id="informations-sur-le-vendeur">Informations sur le vendeur</h2>

    <p>
        Le vendeur désigne Marien Fressinaud.
        Adresse : 57 rue du Vercors – 38000 Grenoble – France.
        <a href="<?= url('contact') ?>">Contact</a>
    </p>

    <p>
        Flus, micro-entreprise<br />
        <abbr>RCS</abbr> Grenoble 878 196 278<br />
        N° Siret : 878 196 278 00013<br />
        TVA non applicable, article 293 B du <abbr>CGI</abbr>
    </p>

    <h2 id="informations-sur-le-service">Informations sur le service</h2>

    <p>
        Le service mis à disposition par le vendeur consistera en un portail
        Internet de veille de l’actualité. Il offrira la possibilité à ses
        utilisateurs et utilisatrices de stocker des liens sous forme de listes de
        lecture, afin de les organiser et pouvoir les retrouver aisément plus tard.
        Ces listes pourront être partagées publiquement à travers une page
        publique, ou au sein de communautés créées par les utilisateur·ices. Chaque
        utilsateur·ice pourra suivre les listes qui l’intéressent et être tenu·e
        informé·e des ajouts et modifications à ces listes. Le service permettra
        également la discussion intra et inter communautés. Les listes pourront
        être alimentées automatiquement grâce à des flux <abbr>RSS</abbr> et Atom.
        Des fonctionnalités pour faciliter la découverte et la lecture de contenu
        seront également présentes.
    </p>

    <p>
        Le service sera fourni à travers l’installation et la maintenance d’un
        logiciel libre développé par le vendeur, et dont le nom et le code source
        seront disponibles ici dès qu’ils seront connus. Il sera accessible sur la
        base d’un abonnement mensuel ou annuel.
    </p>

    <p>
        <strong>L’acheteur reconnaît avoir été informé que le logiciel n’a pas
            encore été développé et que le service n’est donc pas encore en service.</strong>
    </p>

    <h2 id="participation-cagnotte">Participation à la cagnotte</h2>

    <p>
        L’acheteur reconnaît participer librement à un système qui permettra
        d’offrir à n’importe qui un abonnement mensuel gratuit&nbsp;: la cagnotte
        commune. Il ne pourra pas faire valoir cette participation pour bénéficier
        lui-même d’un abonnement gratuit, sauf à en faire la demande explicite, de
        la même manière que les autres utilisateur·ices du service. Il ne pourra
        pas non plus diriger cette participation pour en faire bénéficier une
        personne spécifique de son choix.
    </p>

    <p>
        La cagnotte pourra bénéficier à n’importe qui en faisant la demande. La
        cagnotte sera plus spécifiquement dirigée vers les personnes bénéficiant de
        revenus modestes, mais aucun justificatif ne sera demandé.
    </p>

    <p>
        L’acheteur est libre de fixer lui-même le montant de sa participation, dans
        une fourchette de 1&nbsp;€ à 1&nbsp;000&nbsp;€. Le nombre d’abonnements
        offerts par la participation de l’acheteur sera calculé en fonction du
        montant versé, divisé par le prix d’un abonnement mensuel, situé
        actuellement à 3&nbsp;€ toutes taxes comprises (<abbr>TTC</abbr>). Ainsi,
        une participation de 30&nbsp;€ offrira 10 abonnements mensuels. Il n’est
        pas prévu de permettre l’offre d’abonnements annuels.
    </p>

    <p>
        Le vendeur n’étant pas soumis à la <abbr>TVA</abbr>, la participation de
        l’acheteur correspond également au prix hors-taxe (<abbr>HT</abbr>).
    </p>

    <h2 id="livraison-et-conditions">Livraison et conditions</h2>

    <p>
        La participation de l’acheteur pourra bénéficier aux autres utilisateurs et
        utilisatrices du service dès lors que la cagnotte sera «&nbsp;activée&nbsp;».
        Cette activation se fera au moment de l’ouverture des inscriptions au
        service susnommé. Cette ouverture devrait se faire sous la forme d’une
        version bêta durant l’automne 2020, mais le vendeur tient à souligner qu’il
        ne s’agit que d’une estimation et que cette date est amenée à évoluer s’il
        l’estime nécessaire.
    </p>

    <p>
        La participation de l’acheteur à la cagnotte sera effective dès lors que son
        paiement aura été validé par le prestataire de paiement retenu, en
        l’occurrence la société <a href="https://stripe.com/fr">Stripe</a>.
    </p>

    <p>
        Aucune donnée de paiement (ex. numéro de carte bancaire) n’est manipulée
        directement par le vendeur. Le paiement est considéré comme validé à partir
        du moment où le prestataire le fait savoir au vendeur (ex. à travers un
        message de retour automatique). Si le prestataire retourne un message
        indiquant l’échec du paiement, l’acheteur ne saurait faire valoir ses
        droits auprès du vendeur.
    </p>

    <h2 id="informations-sur-le-droit-de-rétractation">Droit de rétractation</h2>

    <p>
        L’acheteur bénéficie d’une période de 14 jours à compter de la validation
        de son paiement pour appliquer son droit de rétractation. S’il décide
        d’appliquer ce droit, sa participation sera retirée de la cagnotte commune
        et les frais engagés lui seront remboursés. L’acheteur n’a pas à motiver ou
        justifier sa décision.
    </p>

    <p>
        L’acheteur peut faire une réclamation ou appliquer son droit de
        rétractation auprès du vendeur
        <a href="<?= url('contact', ['subject' => 'Droit de rétractation']) ?>">
            en le contactant par message
        </a>.
    </p>
</section>

<hr />
