<?php
    $this->layout('base.phtml', [
        'title' => 'Crédits · Flus',
        'canonical' => url_full('credits'),
    ]);
?>

<section class="section section--text">
    <div class="header">
        <h1 class="header__title">Crédits</h1>
    </div>

    <p class="section__intro">
        Flus se repose en partie sur le travail d’autres personnes. Cette page me sert à les en remercier très sincèrement.
    </p>

    <img
        class="illustration illustration--centered link"
        alt=""
        src="<?= url_static('illustrations/link.svg') ?>"
        height="250"
    />

    <p>
        Tout d’abord, j’ai reçu une aide immense de la part de <a href="https://www.maiwann.net/">Maiwann</a> pour ce qui concerne l’expérience utilisateur. Le projet n’en serait sans doute pas là aujourd’hui sans elle 😊
    </p>

    <p>
        Le logo a été réalisé par <a href="https://www.clara-chambon.fr/">Clara Chambon</a>.
    </p>

    <p>
        La police utilisée dans le logo ainsi que pour les titres du site est la
        «&nbsp;<a href="https://fonts.google.com/specimen/Comfortaa">Comfortaa</a>&nbsp;»,
        conçue par Johan Aakerlund.
    </p>

    <p>
        La police de texte est
        l’«&nbsp;<a href="https://fonts.google.com/specimen/Open+Sans">Open Sans</a>&nbsp;»,
        conçue par Steve Matteson.
    </p>

    <p>
        Les icônes sont issues du projet <a href="https://clarity.design/">Clarity</a>.
    </p>

    <p>
        Les illustrations viennent du génialissime projet
        <a lang="en" href="https://undraw.co/">unDraw</a>, par
        <a href="https://twitter.com/ninaLimpi">Katerina Limpitsouni</a>.
    </p>

    <p>
        Enfin, un bon paquet des idées déposées ici sont le fruit des échanges que
        j’ai eus avec quelques-un·es d’entre vous. Merci encore&nbsp;!
    </p>
</section>
