<?php
    $this->layout('base.phtml', [
        'title' => 'Crédits · Flus',
        'canonical' => url_full('home#credits'),
    ]);
?>

<section class="section">
    <div class="title">
        <h1 class="title__header">Crédits</h1>
    </div>

    <p class="section__intro">
        Flus se repose en partie sur le travail d’autres personnes. Cette page me sert à les en remercier très sincèrement.
    </p>

    <p>
        Le logo, tout d’abord, a été réalisé par <a href="https://www.clara-chambon.fr/">Clara Chambon</a>.
    </p>

    <p>
        La police utilisée dans le logo ainsi que pour les titres du site est la
        «&nbsp;<a href="https://fonts.google.com/specimen/Comfortaa">Comfortaa</a>&nbsp;»,
        conçue par Johan Aakerlund.
    </p>

    <p>
        La police de texte est
        l’«&nbsp;<a href="https://fonts.google.com/specimen/Open+Sans">Open Sans</a>&nbsp;»,
        conçue par Steve Matteson.
    </p>

    <p>
        Les icônes sont issues du générateur <a href="https://icomoon.io/">IcoMoon</a>.
    </p>

    <p>
        Les illustrations viennent du génialissime projet
        <a lang="en" href="https://undraw.co/">unDraw</a>, par
        <a href="https://twitter.com/ninaLimpi">Katerina Limpitsouni</a>.
    </p>

    <p>
        La photo de profil a été prise par Yann Kervran et est sous licence
        <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC&nbsp;BY&nbsp;SA</a>.
    </p>

    <p>
        Enfin, un bon paquet des idées déposées ici sont le fruit des échanges que
        j’ai eus avec quelques-un·es d’entre vous. Merci encore&nbsp;!
    </p>
</section>

<hr />
