<?php
    $this->layout('base.phtml', [
        'title' => 'Flus, le complément éditorial de votre veille',
        'canonical' => url_full('home'),
        'current_page' => 'home',
        'description' => 'Collectez, commentez et retrouvez vos liens favoris en un instant.',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('og-card.png'),
            'twitter_card' => 'summary_large_image',
        ],
    ]);
?>

<section class="panel panel--primary panel--header home__panel--header">
    <div class="wrapper wrapper--larger wrapper--center cols cols--gap-larger">
        <div class="col--size5 wrapper wrapper--text flow flow--large">
            <h1>
                Flus, le complément éditorial de votre veille
            </h1>

            <p>
                Collectez, organisez et partagez votre veille facilement.
            </p>

            <p class="cols cols--gap">
                <a class="button button--primary" href="https://app.flus.fr/registration">
                    <?= icon('arrow-right') ?>
                    S’inscrire sur Flus
                </a>

                <a class="button button--ghost" href="https://demo.flus.fr/">
                    Essayer la démo
                </a>
            </p>
        </div>

        <div class="col--size6 text--right">
            <img
                class="panel--header__illustration"
                alt=""
                src="<?= url_static('illustrations/project-team.svg') ?>"
            />
        </div>
    </div>

    <a class="home__anchor--bigscroll" href="#avantages">
        <?= icon('arrow-right', 'rotate90') ?>
        <span class="sr-only">
            Découvrir les avantages de Flus
        </span>
    </a>
</section>

<section class="panel panel--grey home__panel--advantages" id="avantages">
    <div class="wrapper wrapper--large wrapper--center flow flow--larger">
        <div class="wrapper wrapper--text wrapper--center text--center flow">
            <h2>
                Quels sont les avantages de Flus&nbsp;?
            </h2>

            <p>
                Flus combine l’agrégation de flux, les listes « à lire plus tard » et le partage de signets pour vous éviter d’avoir à jongler entre trop d’outils.
            </p>
        </div>

        <div class="flow flow--large">
            <div class="cols cols--gap-large">
                <div class="col--size6 card card--topaz">
                    <div class="card__body flow flow--large">
                        <h3 class="text--bold">
                            <?= icon('feed') ?>
                            Suivre
                        </h3>

                        <p>
                            Suivez des sources telles que des blogs, des podcasts ou des chaînes vidéo (flux RSS, Atom et JSON), ainsi que des collections partagées sur Flus, organisées en fils thématiques.
                        </p>
                    </div>
                </div>

                <div class="col--size6 card card--caribbean">
                    <div class="card__body flow flow--large">
                        <h3 class="text--bold">
                            <?= icon('reading') ?>
                            Lire
                        </h3>

                        <p>
                            Lisez à votre rythme grâce au Journal qui vous propose une sélection configurable de liens issus des sources que vous suivez, ainsi qu’aux listes « À lire » et « Liens lus ».
                        </p>
                    </div>
                </div>
            </div>

            <div class="cols cols--gap-large">
                <div class="col--size6 card card--caribbean">
                    <div class="card__body flow flow--large">
                        <h3 class="text--bold">
                            <?= icon('collection') ?>
                            Conserver
                        </h3>

                        <p>
                            Rangez vos liens dans des collections pour les retrouver facilement.
                            Ajoutez-y vos notes et des #tags pour mémoriser ce que vous en avez pensé et préparer vos prochaines productions.
                        </p>
                    </div>
                </div>

                <div class="col--size6 card card--gable">
                    <div class="card__body flow flow--large">
                        <h3 class="text--bold">
                            <?= icon('share') ?>
                            Partager
                        </h3>

                        <p>
                            Partagez vos liens, vos collections et vos fils
                            publiquement sur votre profil pour que d’autres personnes puissent vous suivre, ou en privé pour collaborer avec des personnes en particulier.
                        </p>
                    </div>
                </div>
            </div>

            <p class="wrapper wrapper--large wrapper--center text--center">
                <a class="button button--primary" href="<?= url('features') ?>">
                    <?= icon('arrow-right') ?>
                    Découvrir toutes les fonctionnalités
                </a>
            </p>
        </div>
    </div>
</section>

<section class="panel flow flow--large">
    <div class="wrapper wrapper--large wrapper--center cols cols--center cols--gap-larger">
        <div class="col--size6 wrapper wrapper--text flow flow--large">
            <h2>
                Nouveauté Flus 3.0 : les fils de veille
            </h2>

            <ul class="flow">
                <li>Organisez vos sources en fils thématiques pour, entre autres, séparer votre veille professionnelle et personnelle.</li>
                <li>Filtrez leur contenu (date, mots-clés, statut de lecture, sources) pour suivre les sources les plus verbeuses.</li>
                <li>Enregistrez vos filtres sous forme de vues pour les réutiliser.</li>
                <li>Partagez vos fils publiquement, ou en privé pour construire une veille commune avec vos collègues.</li>
            </ul>

            <p class="text--center">
                <a class="button" href="<?= url_full('home') ?>carnet/flus-3.0.html">
                    Les nouveautés de la 3.0 🎁
                </a>
            </p>
        </div>

        <div class="col--size6">
            <div class="home__screenshot-panel">
                <img
                    class="illustration"
                    loading="lazy"
                    alt="L’écran Lecture de Flus affiche trois onglets : Journal, Signets et Liens lus."
                    src="<?= url_static('screenshots/onglet-lecture.webp') ?>"
                />
            </div>
        </div>
    </div>
</section>

<section class="panel panel--grey">
    <div class="wrapper wrapper--large wrapper--center flow flow--large">
        <div class="wrapper wrapper--text wrapper--center text--center flow">
            <h2>
                La veille accessible à toutes et tous
            </h2>

            <p>
                La veille est une pratique d’information qui touche un vaste public.
            </p>
        </div>

        <div class="cols cols--gap">
            <div class="card col--size4 flow flow--large">
                <div class="card__body flow">
                    <h3>
                        Professionnel·les
                    </h3>

                    <p>
                        Vous êtes documentaliste, juriste ou encore développeuse, Flus vous aide à rester à jour dans votre domaine, tout en faisant bénéficier les autres utilisateurices de votre expertise en partageant votre propre veille.
                    </p>
                </div>
            </div>

            <div class="card col--size4 flow flow--large">
                <div class="card__body flow">
                    <h3>
                        Citoyen·nes engagées
                    </h3>

                    <p>
                        Que vous soyez militante, syndicaliste ou simple citoyen soucieux de la société, Flus vous prémâche vos newsletters et articles de veille.
                        Ne polluez plus vos canaux militants de liens que personne ne lit.
                    </p>
                </div>
            </div>

            <div class="card col--size4 flow flow--large">
                <div class="card__body flow">
                    <h3>
                        Profs et étudiant·es
                    </h3>

                    <p>
                        Son interface facile d’accès fait de Flus l’outil idéal pour faire ses premiers pas dans le monde de la veille.
                        Son prix libre en fait l’allié parfait des budgets étudiants, tout en sensibilisant au coût d’un numérique éthique et positif.
                    </p>
                </div>
            </div>
        </div>

        <div class="flow flow--large">
            <h3 class="text--center text--bold">
                Témoignages
            </h3>

            <div class="cols cols--gap-large">
                <figure class="home__testimonial col--extend flow">
                    <blockquote class="home__testimonial-quote">
                        <p>
                            L’ensemble est vraiment super agréable, ça donne une sensation de maitriser l’information à laquelle on est exposé et de pouvoir vraiment prendre le temps de lire de façon intelligente.
                        </p>
                    </blockquote>

                    <figcaption class="home__testimonial-author">
                        <cite class="text--bold">David Louapre</cite>, vidéaste sur la chaîne <a href="https://www.youtube.com/scienceetonnante">Science Étonnante</a>.
                    </figcaption>
                </figure>

                <figure class="home__testimonial col--extend flow">
                    <blockquote class="home__testimonial-quote">
                        <p>
                            J’aime beaucoup l’extension navigateur, je peux ajouter un article à ma veille et le classer dans mes thématiques en un seul clic.
                            Bonus, j’améliore ma technique de veille grâce aux articles de blog dédiés, j’ai beaucoup appris grâce à Flus !
                        </p>
                    </blockquote>

                    <figcaption class="home__testimonial-author">
                        <cite class="text--bold">Mélissa Richard</cite>, chargée d’animation numérique chez <a href="https://www.ritimo.org/">ritimo</a>.
                    </figcaption>
                </figure>
            </div>

            <div class="cols cols--gap-large">
                <figure class="home__testimonial col--extend flow">
                    <blockquote class="home__testimonial-quote">
                        <p>
                            J’utilise Flus quotidiennement depuis plus de 4 ans maintenant, et j’alimente très simplement, à mon rythme, <a href="https://app.flus.fr/collections/1732141437309404145">une collection</a> qui me permet de diffuser ma veille sur le numérique vers mes abonné·es sur Mastodon.
                        </p>
                    </blockquote>

                    <figcaption class="home__testimonial-author">
                        <cite class="text--bold">Thierry Joffredo</cite>, ingénieur de recherche à l’Académie de Rennes.
                    </figcaption>
                </figure>

                <figure class="home__testimonial col--extend flow">
                    <blockquote class="home__testimonial-quote">
                        <p>
                            Flus va largement au delà d'un simple agrégateur de flux : grâce aux signets, il me permet d'intégrer la totalité de ma veille et de régler finement le rythme des contenus que je dois lire. Il est aujourd'hui devenu incontournable dans mon quotidien.
                        </p>
                    </blockquote>

                    <figcaption class="home__testimonial-author">
                        <cite class="text--bold">Thomas Citharel</cite>, directeur de l’association <a href="https://framasoft.org/">Framasoft</a>.
                    </figcaption>
                </figure>
            </div>
        </div>

        <div class="text--center">
            <img
                alt=""
                src="<?= url_static('illustrations/people.svg') ?>"
            />
        </div>
    </div>
</section>

<section class="panel">
    <div class="wrapper wrapper--large wrapper--center flow flow--large">
        <h2 class="text--center">
            La philosophie de Flus en 3 mots
        </h2>

        <div class="cols cols--gap">
            <div class="card col--size4 flow flow--large">
                <div class="card__illustration">
                    <img
                        alt=""
                        src="<?= url_static('illustrations/online-connection.svg') ?>"
                    />
                </div>

                <div class="card__body flow">
                    <h3>
                        Positif
                    </h3>

                    <p>
                        Le projet derrière Flus se revendique d’un numérique plus
                        accessible et plus humain.
                    </p>
                </div>

                <p>
                    <a class="button button--primary" href="<?= url_full('home') ?>carnet/">
                        <?= icon('arrow-right') ?>
                        Accéder au blog
                    </a>
                </p>
            </div>

            <div class="card col--size4 flow flow--large">
                <div class="card__illustration">
                    <img
                        alt=""
                        src="<?= url_static('illustrations/open-source.svg') ?>"
                    />
                </div>

                <div class="card__body flow">
                    <h3>
                        Libre
                    </h3>

                    <p>
                        Le code de Flus est ouvert afin de permettre à d’autres
                        personnes de l’installer et de l’auditer.
                    </p>
                </div>

                <p>
                    <a class="button button--primary" href="https://github.com/flusio/Flus">
                        <?= icon('arrow-right') ?>
                        Explorer le code source
                    </a>
                </p>
            </div>

            <div class="card col--size4 flow flow--large">
                <div class="card__illustration">
                    <img
                        alt=""
                        src="<?= url_static('illustrations/online-payment.svg') ?>"
                    />
                </div>

                <div class="card__body flow">
                    <h3>
                        Pérenne
                    </h3>

                    <p>
                        Auto-financé et sans publicité, vous assurez
                        l’existence de Flus depuis ses débuts.
                    </p>
                </div>

                <p>
                    <a class="button button--primary" href="<?= url('pricing') ?>">
                        <?= icon('arrow-right') ?>
                        Découvrir le prix libre
                    </a>
                </p>
            </div>
        </div>
    </div>
</section>

<section class="panel">
    <div class="wrapper wrapper--large wrapper--center text--center flow flow--larger">
        <h2>
            Les différents services offerts par Flus
        </h2>

        <img
            class="no-mobile"
            loading="lazy"
            alt="Un schéma montrant des sites agrégés vers Flus, d’où ressortent différents services."
            src="<?= url_static('illustrations/flus-services.svg') ?>"
            aria-describedby="flus-services-longdesc"
        />

        <img
            class="only-mobile"
            loading="lazy"
            alt="Un schéma montrant des sites agrégés vers Flus, d’où ressortent différents services."
            src="<?= url_static('illustrations/flus-services-mobile.svg') ?>"
            aria-describedby="flus-services-longdesc"
        />

        <p class="sr-only" id="flus-services-longdesc">
            Différents sites Web (Youtube, RSS, Mastodon, Le Monde, podcasts) sont agrégés vers le logo de Flus.
            De celui-ci sortent 5 services&nbsp;: Accès mobile et extension, éditorialisation de votre veille, prix libre et adapté, respect de votre vie privée, support professionnel dédié.
        </p>
    </div>
</section>

<section class="panel">
    <div class="wrapper wrapper--large wrapper--center cols cols--gap">
        <div class="col--size4 flow flow--larger">
            <h2>
                Un mot du créateur, Marien
            </h2>

            <img
                alt=""
                src="<?= url_static('illustrations/hello.svg') ?>"
            />
        </div>

        <div class="col--size2"></div>

        <div class="col--size6 wrapper wrapper--text flow">
            <p>
                J’ai commencé à travailler sur Flus car j’avais besoin d’une
                plateforme de veille différente. Je cherchais un logiciel qui
                soit complet, agréable à utiliser, libre et qui respecte mes
                données. Dans le même temps, je souhaitais pouvoir vivre de mon
                métier de développeur tout en prenant du plaisir dans mon
                travail. Fin 2019, ayant l’opportunité de me mettre à mon
                compte, j’ai décidé d’allier ces deux composantes.
            </p>

            <p>
                Désormais, mon activité est suffisamment rentable pour que je
                puisse continuer d’investir mon temps dans l’amélioration de ce
                service. En apportant un soin particulier à ce que je fais
                —&nbsp;ou en m’entourant de personnes expertes dans leur
                domaine&nbsp;—, je suis en mesure de vous apporter un service à
                taille humaine qui soit à la fois de qualité et pérenne. C’est,
                je crois, plus que nécessaire aujourd’hui sur Internet.
            </p>
        </div>
    </div>
</section>
