<?php
    $this->layout('base.phtml', [
        'title' => 'Flus, le complément éditorial de votre veille',
        'canonical' => url_full('home'),
        'current_page' => 'home',
        'description' => 'Collectez, commentez et retrouvez vos liens favoris en un instant.',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('og-card.png'),
            'twitter_card' => 'summary_large_image',
        ],
    ]);
?>

<section class="panel panel--primary panel--header home__panel--header">
    <div class="wrapper wrapper--larger wrapper--center cols cols--gap-larger">
        <div class="col--size5 wrapper wrapper--text flow flow--large">
            <h1>
                Flus, le complément éditorial de votre veille
            </h1>

            <p>
                Collectez, commentez et retrouvez vos liens favoris en un instant.
            </p>

            <p class="cols cols--gap">
                <a class="button button--primary" href="https://app.flus.fr/registration">
                    <?= icon('arrow-left', 'rotate180') ?>
                    S’inscrire sur Flus
                </a>

                <a class="button button--ghost" href="https://demo.flus.fr/">
                    Essayer la démo
                </a>
            </p>
        </div>

        <div class="col--size6 text--right">
            <img
                class="panel--header__illustration"
                alt=""
                src="<?= url_static('illustrations/project-team.svg') ?>"
            />
        </div>
    </div>

    <a class="home__anchor--bigscroll" href="#avantages">
        <?= icon('arrow-left', 'rotate270') ?>
        <span class="sr-only">
            Découvrir les avantages de Flus
        </span>
    </a>
</section>

<section class="panel panel--grey home__panel--advantages" id="avantages">
    <div class="wrapper wrapper--large wrapper--center flow flow--larger">
        <div class="wrapper wrapper--text wrapper--center text--center flow">
            <h2>
                Quels sont les avantages de Flus&nbsp;?
            </h2>

            <p>
                Flus est le compagnon idéal de votre veille en ligne.<br>
                Lisez, rangez, commentez, et partagez facilement les contenus
                qui vous ont intéressés et marqués.
            </p>
        </div>

        <div class="cols cols--gap-large">
            <div class="col--size4 card card--gable">
                <div class="card__body flow flow--large">
                    <h3>
                        Veille enrichie
                    </h3>

                    <p>
                        Rangez les liens issus de votre veille dans des
                        collections thématiques, puis commentez-les.
                        Retrouvez-les ensuite grâce au moteur de recherche
                        intégré.
                    </p>
                </div>
            </div>

            <div class="col--size4 card card--topaz">
                <div class="card__body flow flow--large">
                    <h3>
                        Veille apaisée
                    </h3>

                    <p>
                        Ne vous laissez plus inonder de choses à lire. Le
                        journal se connecte aux flux d’actualité de vos sites
                        favoris et vous en présente une sélection digeste.
                    </p>
                </div>
            </div>

            <div class="col--size4 card card--caribbean">
                <div class="card__body flow flow--large">
                    <h3>
                        Veille adaptée
                    </h3>

                    <p>
                        Emportez Flus dans votre poche ou utilisez l’extension
                        navigateur pour accomplir votre veille sans bousculer
                        vos habitudes.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="panel">
    <div class="wrapper wrapper--large wrapper--center cols cols--center cols--gap-larger">
        <div class="col--size6 wrapper wrapper--text flow flow--large">
            <h2>
                Un espace lecture sur-mesure
            </h2>

            <p>
                Suivez vos sites, podcasts ou encore chaînes YouTube favorites
                grâce au journal. Rangez vos liens à consulter plus tard dans
                vos signets, tout en conservant une trace des liens déjà lus.
            </p>

            <p>
                <a class="button button--primary" href="<?= url('features') ?>">
                    <?= icon('arrow-left', 'rotate180') ?>
                    Découvrir plus de fonctionnalités
                </a>
            </p>
        </div>

        <div class="col--size6">
            <div class="panel panel--rounded panel--grey">
                <img
                    class="illustration"
                    loading="lazy"
                    alt="L’écran Lecture de Flus affiche trois onglets : Journal, Signets et Liens lus."
                    src="<?= url_static('screenshots/onglet-lecture.webp') ?>"
                />
            </div>
        </div>
    </div>
</section>

<section class="panel panel--grey">
    <div class="wrapper wrapper--large wrapper--center flow flow--large">
        <div class="wrapper wrapper--text wrapper--center text--center flow">
            <h2>
                La veille accessible à toutes et tous
            </h2>

            <p>
                La veille est une pratique saine d’information qui touche un
                vaste public.
            </p>
        </div>

        <div class="cols cols--gap">
            <div class="card col--size4 flow flow--large">
                <div class="card__body flow">
                    <h3>
                        Professionnel·les
                    </h3>

                    <p>
                        Vous êtes documentaliste, juriste ou encore développeuse,
                        Flus vous aide à rester à jour dans votre domaine, tout
                        en faisant bénéficier les autres utilisateurices de
                        votre expertise en partageant votre propre veille.
                    </p>
                </div>
            </div>

            <div class="card col--size4 flow flow--large">
                <div class="card__body flow">
                    <h3>
                        Citoyen·nes engagées
                    </h3>

                    <p>
                        Que vous soyez militante, syndicaliste ou simple
                        citoyen soucieux de la société, Flus vous prémâche vos
                        newsletters et articles de veille. Ne polluez plus
                        vos canaux militants de liens que personne ne lit.
                    </p>
                </div>
            </div>

            <div class="card col--size4 flow flow--large">
                <div class="card__body flow">
                    <h3>
                        Profs et étudiant·es
                    </h3>

                    <p>
                        Son interface facile d’accès fait de Flus l’outil
                        idéal pour faire ses premiers pas dans le monde de la
                        veille. Son prix libre en fait l’allié parfait des
                        budgets étudiants, tout en sensibilisant au coût d’un
                        numérique éthique et positif.
                    </p>
                </div>
            </div>
        </div>

        <div class="text--center">
            <img
                alt=""
                src="<?= url_static('illustrations/people.svg') ?>"
            />
        </div>
    </div>
</section>

<section class="panel">
    <div class="wrapper wrapper--large wrapper--center flow flow--large">
        <h2 class="text--center">
            La philosophie de Flus en 3 mots
        </h2>

        <div class="cols cols--gap">
            <div class="card col--size4 flow flow--large">
                <div class="card__illustration">
                    <img
                        alt=""
                        src="<?= url_static('illustrations/online-connection.svg') ?>"
                    />
                </div>

                <div class="card__body flow">
                    <h3>
                        Positif
                    </h3>

                    <p>
                        Le projet derrière Flus se revendique d’un numérique plus
                        accessible et plus humain.
                    </p>
                </div>

                <p>
                    <a class="button button--primary" href="<?= url_full('home') ?>carnet/">
                        <?= icon('arrow-left', 'rotate180') ?>
                        Accéder au blog
                    </a>
                </p>
            </div>

            <div class="card col--size4 flow flow--large">
                <div class="card__illustration">
                    <img
                        alt=""
                        src="<?= url_static('illustrations/open-source.svg') ?>"
                    />
                </div>

                <div class="card__body flow">
                    <h3>
                        Libre
                    </h3>

                    <p>
                        Le code de Flus est ouvert afin de permettre à d’autres
                        personnes de l’installer et de l’auditer.
                    </p>
                </div>

                <p>
                    <a class="button button--primary" href="https://github.com/flusio/Flus">
                        <?= icon('arrow-left', 'rotate180') ?>
                        Explorer le code source
                    </a>
                </p>
            </div>

            <div class="card col--size4 flow flow--large">
                <div class="card__illustration">
                    <img
                        alt=""
                        src="<?= url_static('illustrations/online-payment.svg') ?>"
                    />
                </div>

                <div class="card__body flow">
                    <h3>
                        Pérenne
                    </h3>

                    <p>
                        Auto-financé et sans publicité, vous assurez
                        l’existence de Flus depuis ses débuts.
                    </p>
                </div>

                <p>
                    <a class="button button--primary" href="<?= url('pricing') ?>">
                        <?= icon('arrow-left', 'rotate180') ?>
                        Découvrir le prix libre
                    </a>
                </p>
            </div>
        </div>
    </div>
</section>

<section class="panel">
    <div class="wrapper wrapper--large wrapper--center text--center flow flow--larger">
        <h2>
            Les différents services offerts par Flus
        </h2>

        <img
            class="no-mobile"
            loading="lazy"
            alt="Un schéma montrant des sites agrégés vers Flus, d’où ressortent différents services."
            src="<?= url_static('illustrations/flus-services.svg') ?>"
            aria-describedby="flus-services-longdesc"
        />

        <img
            class="only-mobile"
            loading="lazy"
            alt="Un schéma montrant des sites agrégés vers Flus, d’où ressortent différents services."
            src="<?= url_static('illustrations/flus-services-mobile.svg') ?>"
            aria-describedby="flus-services-longdesc"
        />

        <p class="sr-only" id="flus-services-longdesc">
            Différents sites Web (Youtube, RSS, Mastodon, Le Monde, podcasts) sont agrégés vers le logo de Flus.
            De celui-ci sortent 5 services&nbsp;: Accès mobile et extension, éditorialisation de votre veille, prix libre et adapté, respect de votre vie privée, support professionnel dédié.
        </p>
    </div>
</section>

<section class="panel">
    <div class="wrapper wrapper--large wrapper--center cols cols--gap">
        <div class="col--size4 flow flow--larger">
            <h2>
                Un mot du créateur, Marien
            </h2>

            <img
                alt=""
                src="<?= url_static('illustrations/hello.svg') ?>"
            />
        </div>

        <div class="col--size2"></div>

        <div class="col--size6 wrapper wrapper--text flow">
            <p>
                J’ai commencé à travailler sur Flus car j’avais besoin d’une
                plateforme de veille différente. Je cherchais un logiciel qui
                soit complet, agréable à utiliser, libre et qui respecte mes
                données. Dans le même temps, je souhaitais pouvoir vivre de mon
                métier de développeur tout en prenant du plaisir dans mon
                travail. Fin 2019, ayant l’opportunité de me mettre à mon
                compte, j’ai décidé d’allier ces deux composantes.
            </p>

            <p>
                Désormais, mon activité est suffisamment rentable pour que je
                puisse continuer d’investir mon temps dans l’amélioration de ce
                service. En apportant un soin particulier à ce que je fais
                —&nbsp;ou en m’entourant de personnes expertes dans leur
                domaine&nbsp;—, je suis en mesure de vous apporter un service à
                taille humaine qui soit à la fois de qualité et pérenne. C’est,
                je crois, plus que nécessaire aujourd’hui sur Internet.
            </p>
        </div>
    </div>
</section>
