<?php
    $this->layout('base.phtml', [
        'title' => 'Mentions légales · Flus',
        'canonical' => url_full('legal'),
    ]);
?>

<nav class="layout__breadcrumb" aria-label="Fil d’Ariane">
    <ul class="list--nostyle">
        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('home') ?>">

                Accueil
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" aria-current="page" href="<?= url('legal') ?>">

                Mentions légales
            </a>
        </li>
    </ul>
</nav>

<article>
    <header class="panel panel--primary panel--header">
        <div class="wrapper wrapper--larger wrapper--center text--center">
            <h1>Mentions légales</h1>
        </div>
    </header>

    <div class="panel">
        <div class="wrapper wrapper--text wrapper--center text-container">
            <h2 id="éditeur-et-directeur-de-la-publication">Éditeur et directeur de la publication</h2>

            <p>
                L’éditeur et directeur de la publication de ce site est Marien Fressinaud.
                Adresse&nbsp;: 4 bis rue Germain – 38100 Grenoble – France.
                <a href="<?= url('contact') ?>">Contact</a>
            </p>

            <p>
                Flus, micro-entreprise<br />
                <abbr>RCS</abbr> Grenoble 878 196 278<br />
                N° Siret&nbsp;: 878 196 278 00013
            </p>

            <h2 id="hébergeur">Hébergeur</h2>

            <p>
                Ce site est hébergé chez <a href="https://www.hetzner.com">Hetzner Online GmbH</a>.
                Adresse&nbsp;: Industriestr. 25 – 91710 Gunzenhausen – Allemagne.
                Téléphone&nbsp;: +49 (0)9831 505-0
            </p>

            <h2 id="conditions-générales">Conditions générales</h2>

            <ul>
                <li><a href="https://app.flus.fr/terms">Conditions Générales d’Utilisation (<abbr>CGU</abbr>) pour le service app.flus.fr</a></li>
                <li><a href="https://flus.io/i/?a=tos">Conditions Générales d’Utilisation (<abbr>CGU</abbr>) pour le service flus.io</a></li>
                <li><a href="<?= url('cgv') ?>">Conditions Générales de Vente (<abbr>CGV</abbr>)</a></li>
            </ul>

            <h2 id="données-personnelles">Données personnelles</h2>

            <p>
                Cette section traite de la gestion des données personnelles du site
                <a href="https://flus.fr">flus.fr</a>, ainsi que les services
                accessibles aux adresses <a href="https://app.flus.fr">app.flus.fr</a>
                et <a href="https://flus.io">flus.io</a>. Pour toute question ou
                réclamation, vous pouvez
                <a href="<?= url('contact', ['subject' => 'Question relative aux données personnelles']) ?>">
                    me contacter par message
                </a>.
            </p>

            <p>
                Si vous souhaitez vous protéger plus efficacement le temps de faire
                connaissance avec le service, <a href="https://flus.fr/carnet/protegez-vous.html">voici un guide</a>.
            </p>

            <p>
                Conformément aux dispositions du règlement général sur la protection des
                données (<abbr>RGPD</abbr>), vous disposez d’un droit d’accès et de
                modification des données vous concernant.
            </p>

            <h3 id="finalités">Finalités des traitements de données</h3>

            <p>
                Les finalités (et bases légales) des différentes collectes de données
                concernant les services Flus sont les suivantes :
            </p>

            <ul>
                <li>connecter les utilisateurs aux services (intérêt légitime) ;</li>
                <li>adapter les interfaces des utilisateurs (intérêt légitime) ;</li>
                <li>identifier les connexions illégitimes pour détecter des attaques (intérêt légitime) ;</li>
                <li>mesurer les statistiques de visites (intérêt légitime) ;</li>
                <li>personnaliser le profil des utilisateurs (consentement) ;</li>
                <li>conserver les logs des visites (obligation légale) ;</li>
                <li>établir des factures (obligation légale) ;</li>
            </ul>

            <h3 id="données-collectées">Données collectées</h3>

            <h4>De manière générale</h4>

            <p>
                Votre visite sur l’un des sites mentionnés génère sur le ou les
                serveurs, et en toutes circonstances des logs, conservés pour une durée
                de 365 jours. Ces logs incluent adresse <abbr>IP</abbr>, date et heure
                de connexion, user agent et page visitée. Ceux-ci sont utilisés pour
                connaître l’activité sur la plateforme et répondre aux requêtes
                judiciaires. Ils peuvent être utilisés pour retrouver la source d’un
                problème survenant sur le site.
            </p>

            <p>
                Des cookies de session et de connexion sont déposés sur le périphérique
                de l’utilisateur. Ils servent uniquement au bon fonctionnement du
                service (maintenir une connexion permanente avec le serveur) et en
                aucun cas à tracer l’utilisateur.
            </p>

            <h4>Concernant app.flus.fr</h4>

            <p>Les données collectées pour le service <a href="https://app.flus.fr">app.flus.fr</a>&nbsp;:</p>

            <ul>
                <li>une adresse courriel, permet la connexion au service et la communication avec l’utilisateur (obligatoire, privée, doit être validée)&nbsp;;</li>
                <li>un mot de passe, permet la connexion au service (obligatoire, privé, hashé)&nbsp;;</li>
                <li>un nom d’utilisateur, utilisé pour identifier publiquement l’utilisateur sur le service (obligatoire, public, peut être un pseudonyme).</li>
                <li>l’adresse <abbr>IP</abbr> et le « <em lang="en">user agent</em> » de l’utilisateur (obligatoires, privés, le dernier octet de l’<abbr>IP</abbr> est anonymisé)</li>
                <li>une langue, pour traduire l’interface de l’application (obligatoire, semi-publique).</li>
                <li>une image de profil (avatar), pour distinguer visuellement les utilisateurs (facultative, publique).</li>
            </ul>

            <p>
                Note : la langue n’est pas directement révélée publiquement, mais elle peut être devinée facilement.
            </p>

            <p>
                Pour ce service, le document faisant foi <a href="https://github.com/flusio/Flus/blob/main/GDPR.txt">se trouve sur GitHub</a>.
            </p>

            <h4>Concernant flus.io</h4>

            <p>Les données collectées pour le service <a href="https://flus.io">flus.io</a>&nbsp;:</p>

            <ul>
                <li>une adresse courriel, permet la communication avec l’utilisateur (obligatoire, privée, doit être validée)&nbsp;;</li>
                <li>un mot de passe, permet la connexion au service (obligatoire, privé, hashé)&nbsp;;</li>
                <li>un nom d’utilisateur, permet la connexion au service (obligatoire, privé, peut être un pseudonyme).</li>
            </ul>

            <h4>Concernant l’abonnement</h4>

            <p>Les données collectées dans le cadre de votre abonnement&nbsp;:</p>

            <ul>
                <li>une adresse courriel (obligatoire)&nbsp;;</li>
                <li>les nom et prénom de l’acheteur (obligatoire)&nbsp;;</li>
                <li>une adresse de facturation (facultative).</li>
            </ul>

            <p>
                Ces données sont utilisées pour établir les factures et vous
                l’envoyer. <strong>Elles ne sont pas rendues publiques.</strong>
                Je suis tenu <a href="https://www.legifrance.gouv.fr/affichCodeArticle.do?idArticle=LEGIARTI000006219327&amp;cidTexte=LEGITEXT000005634379">légalement</a>
                de conserver ces factures sur une période de 10 ans.
            </p>

            <p>
                L’adresse courriel est également transmise au prestataire de paiement,
                <a href="https://stripe.com/fr">Stripe</a> afin de faciliter la saisie
                du formulaire de paiement (ça fait un champ en moins à remplir
                manuellement).
            </p>

            <p>
                Par ailleurs, Stripe place deux cookies (<code>__stripe_mid</code> et
                <code>__stripe_sid</code>) lors de la redirection vers son service.
                Ceux-ci sont nécessaires au bon déroulé du paiement, mais sont
                supprimés dès lors que vous revenez sur le site. Cette suppression ne
                concerne pas d’éventuels cookies placés sur le domaine
                checkout.stripe.com, ce qui me serait techniquement impossible à
                réaliser.
            </p>

            <h4>Concernant les statistiques</h4>

            <p>Certaines données sont collectées dans le cadre du suivi des statistiques des visites&nbsp;:</p>

            <ul>
                <li>l’<abbr>URL de la page</abbr> (obligatoire) ;</li>
                <li>le site de référence (obligatoire) ;</li>
                <li>votre navigateur, votre système d’exploitation et le type d’appareil (obligatoire) ;</li>
                <li>votre pays (obligatoire).</li>
            </ul>

            <p>
                Ces données sont collectées par <a href="https://plausible.io/">Plausible</a>
                qui est conçu pour ne pas vous suivre de manière intrusive. Cette solution
                est conforme au <abbr>RGPD</abbr> par conception et ne nécessite pas de
                dépose de cookie. Votre adresse <abbr>IP</abbr> est utilisée uniquement
                pour calculer certaines informations, mais n’est pas stockée.
            </p>

            <h3 id="destinataires-des-données">Destinataires des données</h3>

            <p>
                Il existe un unique destinataire interne en la qualité de l’éditeur
                désigné plus haut dans ces mentions légales.
            </p>

            <p>
                Les sous-traitants suivants peuvent également être amenés à avoir accès
                aux données&nbsp;:
            </p>

            <ul>
                <li>
                    <a href="https://www.hetzner.com/">Hetzner</a>, en qualité
                    d’hébergeur du serveur physique, a accès aux machines (Nuremberg,
                    Allemagne)&nbsp;;
                </li>

                <li>
                    <a href="https://www.rsync.net/">rsync.net</a> héberge les
                    sauvegardes <strong>chiffrées</strong> des données sur un serveur
                    dont je ne dispose pas de l’accès <code>root</code> (Zurich,
                    Suisse)&nbsp;;
                </li>

                <li>
                    <a href="https://www.stripe.com/">Stripe</a> (qui fournit l’interface
                    de paiement) accède à votre adresse courriel. Il vous demandera par
                    ailleurs les informations liées à votre carte bleue et peut être
                    amené à vous redemander votre adresse postale s’il juge que le
                    paiement est « risqué » (voir leur
                    <a href="https://stripe.com/fr/privacy#translation">politique de confidentialité</a>) ;
                </li>

                <li>
                    <a href="https://plausible.io">Plausible</a> assure le suivi des
                    statistiques de visites de mes sites.
                    Voir <a href="https://plausible.io/data-policy">leur politique des données</a> et <a href="https://plausible.io/privacy">leur politique de confidentialité</a>).
                </li>
            </ul>

            <h3 id="sécurité">Sécurité</h3>

            <p>Les éléments suivants sont mis en œuvre pour assurer la sécurité du service&nbsp;:</p>

            <ul>
                <li>Site accessible en <abbr>HTTPS</abbr> avec des configurations de sécurité modernes</li>
                <li>Échanges chiffrés avec le prestataire de paiement</li>
                <li>Traçabilité à travers la journalisation des accès (logs)</li>
                <li>Mise à jour système et du service appliquée régulièrement</li>
                <li>Sauvegarde journalière des données chiffrées sur un serveur externe
                    avec <a href="https://www.borgbackup.org/">BorgBackup</a></li>
                <li>Une <a href="<?= url('security') ?>">procédure existe</a> en cas de
                    faille de sécurité dans un ou plusieurs services</li>
            </ul>
        </div>
    </div>
</article>
