<?php
    $this->layout('base.phtml', [
        'title' => 'Tarifs · Flus',
        'canonical' => url_full('pricing'),
        'current_page' => 'pricing',
        'description' => 'Un prix libre pour financer directement le projet.',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('flus.png'),
            'twitter_card' => 'summary',
        ],
    ]);
?>

<section class="section section--text">
    <div class="header">
        <h1 class="header__title">Tarifs</h1>
    </div>

    <p class="price">
        <span class="price__unique">Un prix unique : <strong>le vôtre.</strong></span>
        <span class="price__choose">De 0 à 120 €, le prix est libre.</span>
    </p>

    <p class="paragraph--center">
        <a class="price__more" href="#choisir">En savoir plus sur le prix libre</a>
    </p>

    <p class="paragraph--featured">
        <a class="call-to-action" href="https://app.flus.fr/registration">
            Commencer par un mois gratuit
        </a>
    </p>

    <img
        class="illustration illustration--centered savings"
        alt=""
        src="<?= url_static('illustrations/savings.svg') ?>"
        height="250"
    />
</section>

<section class="section" id="choisir">
    <div class="header">
        <h2 class="header__title">Choisir le « juste » prix</h2>
    </div>

    <p class="section--text">
        Si Flus est payant, c’est que je souhaite vivre de cette activité
        pour m’y consacrer. Le prix libre permet à tout un chacun de déterminer
        combien il ou elle est prête à payer pour un service en ligne.
    </p>

    <p class="section--text">
        Choisir un prix n’est pas chose aisée. Ainsi, je propose trois
        tarifs de base pour vous aider à choisir :
    </p>

    <ol class="tariffs">
        <li class="tariffs__item">
            <strong class="tariffs__name">Tarif « solidaire »<br>à 15 € par an.</strong>
            <span class="tariffs__description">
                Pour celles et ceux qui ne sont pas prêts à dépenser plus, mais
                qui souhaitent tout de même soutenir le projet.
            </span>
        </li>

        <li class="tariffs__item">
            <strong class="tariffs__name">Tarif « équilibre »<br>à 30 € par an.</strong>
            <span class="tariffs__description">
                C’est le tarif de base, celui que je juge le plus juste au regard
                du service que je propose et de mon objectif financier.
            </span>
        </li>

        <li class="tariffs__item">
            <strong class="tariffs__name">Tarif « soutien »<br>à <?= $contribution_price ?> € * par an.</strong>
            <span class="tariffs__description">
                Il faudrait que tous et toutes les abonnées actuelles payent ce
                prix pour que j’atteigne mon objectif financier.
            </span>
        </li>
    </ol>

    <p class="section--text">
        * Le tarif « soutien » a de particulier qu’il évolue ! Plus vous êtes
        nombreux et nombreuses à payer pour le service, plus le prix diminue.
    </p>

    <p class="paragraph--featured">
        <?php if ($account): ?>
            <a class="call-to-action" href="<?= url('subscription init') ?>">
                Retour au renouvellement
            </a>
        <?php else: ?>
            <a class="call-to-action" href="https://app.flus.fr/registration">
                Commencer à utiliser Flus
            </a>
        <?php endif; ?>
    </p>
</section>

<section class="section section--text">
    <div class="header">
        <h2 class="header__title">Financement</h2>
    </div>

    <p class="section__intro">
        Curieux de connaître mes objectifs financiers et de savoir comment
        j’utilise mon chiffre d’affaires&nbsp;?
    </p>

    <div class="gauge" style="--gauge-value: <?= $percent_target ?>%;">
        <p class="gauge__status">
            Objectif 2023&nbsp;:
            <strong><?= $this->safe('total_revenue') ?> sur <?= $this->safe('revenue_target') ?>&nbsp;€</strong>
        </p>

        <ul class="gauge__container">
            <li class="gauge__current"></li>

            <li class="gauge__item gauge__item--purchases">
                Achats<br />30&nbsp;%
            </li>

            <li class="gauge__item gauge__item--salary">
                Rémunération (dont cotisations)<br />70&nbsp;%
            </li>
        </ul>
    </div>

    <p>
        Les <strong>achats</strong> incluent le paiement des serveurs, des
        noms de domaine et fournitures éventuelles. On y trouve également
        les frais liés aux paiements, ainsi que les frais bancaires et de
        mutuelle.
    </p>

    <p>
        La <strong>rémunération</strong> correspond à mon salaire si j’atteins
        le palier des 5&nbsp;000&nbsp;€, représentant un peu plus de
        2&nbsp;500&nbsp;€ dans ma poche. Mon but est bien sûr d’aller au-delà
        afin de pouvoir en vivre.
    </p>

    <p>
        <strong>
            <a href="https://flus.fr/carnet/bilan-2022.html">→ Lire mon bilan de l’année 2022</a>
        </strong>
    </p>
</section>
