<?php
    $this->layout('base.phtml', [
        'title' => 'Tarifs · Flus',
        'canonical' => url_full('pricing'),
        'current_page' => 'pricing',
        'description' => 'Un prix unique, accessible pour financer directement le projet.',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('flus.png'),
            'twitter_card' => 'summary',
        ],
    ]);
?>

<section class="section section--text">
    <div class="header">
        <h1 class="header__title">Tarifs</h1>
    </div>

    <p class="price">
        <span class="price__month">3&nbsp;€ par mois</span>
        <span class="price__year">ou 30&nbsp;€ par an</span>
        <span class="price__all-inclusive">tout inclus, y’a pas de surprise</span>
    </p>

    <p class="paragraph--featured">
        <a class="call-to-action" href="https://app.flus.fr/registration">
            Commencer par un mois gratuit
        </a>
    </p>

    <p class="paragraph--center">
        abonnements gratuits via la <a href="<?= url('common pot') ?>">cagnotte</a>
    </p>

    <img
        class="illustration illustration--centered savings"
        alt=""
        src="<?= url_static('illustrations/savings.svg') ?>"
        height="250"
    />

    <p>
        Si Flus est payant, c’est que je souhaite vivre de cette activité
        pour m’y consacrer. <strong>À 3 euros par mois, je pense que ce n’est
            pas si cher payé pour un Web de meilleure qualité.</strong>
    </p>

    <p>
        J’ai exclu le modèle publicitaire sur lequel repose une large
        partie du Web car il pose de nombreux problèmes de vie privée et de
        captation de l’attention. <strong>Le système d’abonnements a le mérite
            d’être transparent et de faire vivre le service de manière
            soutenable.</strong>
    </p>

    <p>
        Les utilisateurs et utilisatrices de Flus alimentent également
        une cagnotte qui débloquent des abonnements mensuels gratuits pour
        celles et ceux qui ne peuvent ou ne veulent payer. <strong>C’est un
            modèle alternatif et solidaire.</strong>
    </p>

    <p>
        <strong>
            <a href="<?= url('common pot') ?>">→ En apprendre plus sur la cagnotte</a>
        </strong>
    </p>
</section>

<section class="section section--text">
    <div class="header">
        <h2 class="header__title">Financement</h2>
    </div>

    <p class="section__intro">
        Curieux de connaître mes objectifs financiers et de savoir comment
        j’utilise mon chiffre d’affaires&nbsp;?
    </p>

    <div class="gauge" style="--gauge-value: <?= $percent_target ?>%;">
        <p class="gauge__status">
            Objectif 2022&nbsp;:
            <strong><?= $this->safe('total_revenue') ?> sur <?= $this->safe('revenue_target') ?>&nbsp;€</strong>
        </p>

        <ul class="gauge__container">
            <li class="gauge__current"></li>

            <li class="gauge__item gauge__item--purchases">
                Achats<br />30&nbsp;%
            </li>

            <li class="gauge__item gauge__item--salary">
                Rémunération (dont cotisations)<br />70&nbsp;%
            </li>
        </ul>
    </div>

    <ul class="revenues">
        <li class="revenues__item">
            <div class="revenues__amount">
                <?= $this->safe('subscriptions_revenue') ?>&nbsp;€
            </div>
            <div class="revenues__label">
                abonnements
            </div>
        </li>

        <li class="revenues__item">
            <div class="revenues__amount">
                <?= $this->safe('common_pot_revenue') ?>&nbsp;€
            </div>
            <div class="revenues__label">
                en cagnotte
            </div>
        </li>
    </ul>

    <p>
        Les <strong>achats</strong> incluent le paiement des serveurs, des
        noms de domaine et fournitures éventuelles. On y trouve également
        les frais liés aux paiements, ainsi que les frais bancaires et de
        mutuelle.
    </p>

    <p>
        La <strong>rémunération</strong> correspond à mon salaire si j’atteins
        le palier des 5&nbsp;000&nbsp;€, représentant un peu plus de
        2&nbsp;500&nbsp;€ dans ma poche. Mon but est bien sûr d’aller au-delà
        afin de pouvoir en vivre.
    </p>

    <p>
        <strong>
            <a href="https://flus.fr/carnet/bilan-2022.html">→ Lire mon bilan de l’année 2022</a>
        </strong>
    </p>
</section>
