<?php
    $this->layout('base.phtml', [
        'title' => 'Le projet · Flus',
        'canonical' => url_full('project'),
        'current_page' => 'project',
        'description' => 'L’idée de Flus est née d’une frustration prenant racine dans mon usage du Web.',
        'og' => [
            'type' => 'website',
            'image' => url_full_static('flus.png'),
            'twitter_card' => 'summary',
        ],
    ]);
?>

<section class="section section--text">
    <div class="header">
        <h1 class="header__title">Le projet</h1>
    </div>

    <p>
        <strong>J’ai commencé à travailler sur Flus car j’avais besoin d’une
            plateforme de veille différente. Je cherchais un logiciel qui soit
            complet, agréable à utiliser, libre et qui respecte mes données.</strong>
    </p>

    <p>
        Dans le même temps, je souhaitais pouvoir vivre de mon métier de
        développeur tout en me faisant plaisir. Fin 2019, ayant l’opportunité
        de me mettre à mon compte, j’ai décidé d’allier ces deux composantes.
    </p>

    <p>
        J’ai d’abord proposé un premier service —&nbsp;<a href="https://flus.io">Flus 1</a>&nbsp;—
        sur la base d’un logiciel que j’avais initié quand j’étais étudiant :
        <a href="https://freshrss.org">FreshRSS</a>.
    </p>

    <p>
        Ce logiciel, tel qu’il était conçu, ne me permettait pas de faire ce
        que j’avais en tête. J’ai donc débuté la conception d’un nouvel outil
        sur des bases différentes : <a href="https://github.com/flusio/flusio">flusio</a>.
        Le service nommé Flus —&nbsp;ou parfois Flus 2&nbsp;—, présenté sur ce
        site, repose sur ce logiciel.
    </p>

    <p>
        <strong>Grâce à mon statut d’indépendant et au temps dont je dispose,
            je peux m’impliquer à fond dans la conception de cet outil et le
            service associé.</strong>
        J’apporte un soin particulier à tout ce que je fais —&nbsp;code, design,
        support, etc.&nbsp;— tout simplement parce que je considère que c’est la
        bonne manière de faire. Et aussi parce que je prends du plaisir à faire
        ainsi, c’est tout bénef ! 🙂
    </p>

    <p>
        Lorsque je ne sais pas faire, je n’hésite pas à faire appel à des
        personnes qui savent mieux que moi. C’est pourquoi je travaille
        avec <a href="https://www.maiwann.net/">Maiwann</a>, une
        <em lang="en"><abbr>UX</abbr> designer</em> professionnelle qui m’aide
        à concevoir l’interface.
    </p>

    <p>
        Grâce <a href="https://flus.fr/carnet">au carnet</a> qui me suit depuis
        le début, je partage un maximum de choses autour du projet. J’espère
        réussir à transmettre mon idée d’un numérique plus accessible, plus
        indépendant et, d’une certaine manière, plus humain.
    </p>

    <p>
        <strong>Mon ambition, à court terme, est de réussir à me dégager un
            salaire suffisant pour ne plus dépendre de mes économies et aides
            sociales.</strong>
        À plus long terme, j’aimerais monter un
        petit studio de conception et développement de logiciels libres qui
        suivent la même philosophie que Flus.
    </p>

    <div class="signature">
        — Marien
    </div>
</section>
