<?php
    $this->layout('base.phtml', [
        'title' => 'Remonter un problème de sécurité · Flus',
        'canonical' => url_full('security'),
    ]);
?>

<nav class="layout__breadcrumb" aria-label="Fil d’Ariane">
    <ul class="list--nostyle">
        <li class="breadcrumb__item">
            <a class="breadcrumb__link" href="<?= url('home') ?>" rel="home">

                Accueil
            </a>
        </li>

        <li class="breadcrumb__item">
            <a class="breadcrumb__link" aria-current="page" href="<?= url('security') ?>">

                Sécurité
            </a>
        </li>
    </ul>
</nav>

<article>
    <header class="panel panel--primary panel--header">
        <div class="wrapper wrapper--larger wrapper--center text--center">
            <h1>
                Remonter un problème de sécurité
            </h1>
        </div>
    </header>

    <div class="panel">
        <div class="wrapper wrapper--text wrapper--center flow">
            <p>
                Si vous avez détecté une faille de sécurité liée aux services fournis
                par Flus, vous êtes au bon endroit pour m’en avertir.
            </p>

            <p>
                <strong>Pour la sécurité de toutes et tous, il est important de ne pas
                    publier cette faille publiquement sans m’en avertir !</strong>
            </p>

            <ol>
                <li>Rendez-vous sur <a href="<?= url('contact') ?>">le formulaire de contact</a> pour me contacter&nbsp;;</li>
                <li>Si vous avez une raison de croire que le formulaire est compromis, envoyez-moi un courriel directement à <a href="mailto:security@flus.fr">security@flus.fr</a>&nbsp;;</li>
                <li>Je ferai mon possible pour vous confirmer la prise en compte de votre ticket dans les 48 heures, mais notez que cela peut monter jusqu’à 7 jours (il m’arrive de prendre des vacances&nbsp;🍹)&nbsp;;</li>
                <li>S’il s’agit bien d’une faille de sécurité, je la corrigerai aussi vite que possible en fonction de ma disponibilité et du danger qu’elle représente&nbsp;;</li>
                <li>Vous serez averti‧e de la correction par courriel&nbsp;;</li>
                <li>En fonction de la gravité de la faille, un incident sera créé sur le site <a href="https://status.flus.fr/">status.flus.fr</a> et un article pourra également être publié sur le blog <a href="https://flus.fr/carnet">flus.fr/carnet</a>&nbsp;;</li>
                <li>En cas de compromission ou de perte de données, un courriel sera envoyé aux utilisateurs et utilisatrices concernées.</li>
            </ol>

            <p>
                Les services suivants sont concernés par cette procédure&nbsp;:
            </p>

            <ul>
                <li><a href="https://flus.fr">flus.fr</a> (site vitrine et service de paiement)</li>
                <li><a href="https://app.flus.fr">app.flus.fr</a> (Flus)</li>
                <li><a href="https://rss.flus.fr">rss.flus.fr</a> (FreshRSS)</li>
                <li><a href="https://status.flus.fr">status.flus.fr</a></li>
                <li><a href="https://websub.flus.io">websub.flus.io</a></li>
            </ul>

            <p>
                Les personnes me remontant des failles sont remerciées ci-dessous&nbsp;:
            </p>

            <ul>
                <li>Rishabh Pardeshi (<a href="https://status.flus.fr/a/1714046090571815001">voir l’annonce</a>)</li>
            </ul>

        </div>
    </div>
</article>
